'use client';

import { FormEvent, useMemo, useState, useTransition } from 'react';
import { controlCreateCustomer, controlFiscalDetail, controlLogout, controlSavePricing, controlUpdateLicense, controlDashboard } from './actions';
import UpdateCenter from './update-center';

type Row=Record<string,unknown>;
type View='overview'|'clients'|'fiscal'|'pricing'|'updates';
const MODULES=[
 ['people','Pessoas','Clientes, fornecedores e usuários'],['sales','Vendas','Operações, vendas e caixas'],['products','Produtos','Cadastro e ficha técnica'],['pricing','Tabela de Preços','Tabelas, promoções e ajustes'],['stock','Estoque','Movimentações, inventário e transferências'],['purchases','Compras','Entradas e compras'],['finance','Financeiro','Receber, pagar e conciliação'],['fiscal','Fiscal','NF-e e NFC-e'],['production','Produção','Cozinha e produção sob demanda'],['reports','Relatórios','Relatórios gerenciais'],['administration','Administrativo','Empresas, filiais e configurações'],['integrations','Integrações','Integrações externas'],['support','Atendimento','Chamados e mensagens'],['pdv','ThorPDV','Frente de caixa Desktop'],
] as const;
const money=(v:unknown)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const text=(v:unknown)=>v==null?'':String(v);
const num=(v:unknown)=>Number(v||0);
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR'):'—';
const allModules=()=>Object.fromEntries(MODULES.map(([k])=>[k,true])) as Record<string,boolean>;
const statusName:Record<string,string>={trial:'Teste',active:'Ativa',suspended:'Suspensa',cancelled:'Cancelada',draft:'Rascunho',processing:'Processando',authorized:'Autorizada',rejected:'Rejeitada'};

function normalized(r:Record<string,unknown>){return {clients:Array.isArray(r.clients)?r.clients as Row[]:[],fiscal:Array.isArray(r.fiscal)?r.fiscal as Row[]:[],pricing:(r.pricing&&typeof r.pricing==='object'?r.pricing:{}) as Row,summary:(r.summary&&typeof r.summary==='object'?r.summary:{}) as Row};}

export function ControlClient({initial}:{initial:Record<string,unknown>}){
 const [data,setData]=useState(normalized(initial));const [view,setView]=useState<View>('overview');const [pending,startTransition]=useTransition();const [message,setMessage]=useState('');
 const [newOpen,setNewOpen]=useState(false);const [newModules,setNewModules]=useState<Record<string,boolean>>(allModules());const [created,setCreated]=useState<Row|null>(null);
 const [editing,setEditing]=useState<Row|null>(null);const [editModules,setEditModules]=useState<Record<string,boolean>>({});const [fiscalDetail,setFiscalDetail]=useState<Row|null>(null);
 const [clientSearch,setClientSearch]=useState('');const [fiscalSearch,setFiscalSearch]=useState('');const [fiscalStatus,setFiscalStatus]=useState('');
 async function refresh(){const r=await controlDashboard();if(r.ok)setData(normalized(r as Record<string,unknown>));else setMessage(text(r.error||'Falha ao atualizar o portal.'))}
 function run(fn:()=>Promise<void>){startTransition(()=>{void fn()})}
 const clients=useMemo(()=>data.clients.filter(c=>`${text(c.name)} ${text(c.legal_name)} ${text(c.cnpj)}`.toLowerCase().includes(clientSearch.toLowerCase())),[data.clients,clientSearch]);
 const fiscal=useMemo(()=>data.fiscal.filter(f=>{const q=`${text(f.tenant_name)} ${text(f.company)} ${text(f.branch)} ${text(f.access_key)} ${text(f.number)} ${text(f.rejection_message)}`.toLowerCase();return q.includes(fiscalSearch.toLowerCase())&&(!fiscalStatus||text(f.status)===fiscalStatus)}),[data.fiscal,fiscalSearch,fiscalStatus]);
 const pricing=data.pricing;
 async function savePricing(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const r=await controlSavePricing(Object.fromEntries(fd.entries()));if(!r.ok){setMessage(text(r.error||'Falha ao salvar tabela comercial.'));return}setMessage('Tabela comercial atualizada. Novas licenças usarão estes valores.');await refresh()}
 async function createCustomer(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const payload:Object=Object.fromEntries(fd.entries());const r=await controlCreateCustomer({...payload,modules:newModules});if(!r.ok){setMessage(text(r.error||'Não foi possível cadastrar o cliente.'));return}setCreated(r as Row);setNewOpen(false);setMessage('Cliente, loja, licença e acesso inicial criados com sucesso.');await refresh()}
 function openEdit(c:Row){setEditing(c);setEditModules({...allModules(),...((c.modules&&typeof c.modules==='object'?c.modules:{}) as Record<string,boolean>)})}
 async function saveLicense(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const fd=new FormData(e.currentTarget);const r=await controlUpdateLicense(text(editing.tenant_id),{...Object.fromEntries(fd.entries()),modules:editModules});if(!r.ok){setMessage(text(r.error||'Falha ao atualizar licença.'));return}setEditing(null);setMessage('Licença atualizada e aplicada ao ERP/ThorPDV.');await refresh()}
 async function openFiscal(f:Row){const r=await controlFiscalDetail(text(f.id));setFiscalDetail((r.ok&&r.document&&typeof r.document==='object'?r.document:f) as Row)}
 const nav=(id:View,label:string,icon:string)=><button className={view===id?'active':''} onClick={()=>setView(id)}><span>{icon}</span>{label}</button>;
 return <main className="control-shell">
  <aside className="control-sidebar"><div className="control-brand side"><span>ϟ</span><div><strong>THOR CONTROL</strong><small>Owner Console</small></div></div><nav>{nav('overview','Visão Geral','⌂')}{nav('clients','Clientes & Licenças','▦')}{nav('fiscal','Monitor Fiscal','⌁')}{nav('updates','Atualizações','↻')}{nav('pricing','Tabela Comercial','R$')}</nav><div className="control-side-note"><small>GESTÃO</small><strong>5 usuários incluídos</strong><span>Limites e módulos são aplicados por licença.</span></div><form action={controlLogout}><button className="control-logout" type="submit">Sair</button></form></aside>
  <section className="control-main"><header className="control-top"><div><small>ADMINISTRAÇÃO DA PLATAFORMA</small><h1>{view==='overview'?'Visão Geral':view==='clients'?'Clientes & Licenças':view==='fiscal'?'Monitor Fiscal':view==='updates'?'Controle de Atualizações':'Tabela Comercial'}</h1><p>{view==='fiscal'?'Acompanhe NF-e/NFC-e de todas as lojas em um só lugar.':view==='updates'?'Libere versões, acompanhe a frota e faça rollback controlado do ThorPDV.':'Controle comercial e operacional do ecossistema Thor.'}</p></div>{view!=='updates'&&<button className="control-primary" onClick={()=>setNewOpen(true)}>+ Novo cliente</button>}</header>{message&&<div className="control-alert ok">{message}</div>}
  {view==='overview'&&<><section className="control-kpis"><article><span>Clientes</span><strong>{num(data.summary.clients)}</strong><small>tenants cadastrados</small></article><article><span>Licenças ativas</span><strong>{num(data.summary.active_licenses)}</strong><small>ativas ou em teste</small></article><article><span>Receita mensal</span><strong>{money(data.summary.monthly_recurring)}</strong><small>licenças ativas</small></article><article><span>ThorPDV ativos</span><strong>{num(data.summary.pdv_devices)}</strong><small>terminais vinculados</small></article></section><section className="control-grid-two"><article className="control-card"><div className="control-card-head"><div><small>PORTFÓLIO</small><h2>Sistema ERP + ThorPDV</h2></div><button onClick={()=>setView('pricing')}>Configurar preços</button></div><div className="control-plan"><div><strong>Gestão</strong><span>{num(pricing.included_management_users)||5} usuários incluídos</span></div><b>{money(pricing.base_erp_price)}<small>/mês</small></b></div><div className="control-plan"><div><strong>Usuário adicional</strong><span>por usuário acima do pacote</span></div><b>{money(pricing.extra_management_user_price)}<small>/mês</small></b></div><div className="control-plan"><div><strong>ThorPDV adicional</strong><span>por terminal acima de {num(pricing.included_pdv_terminals)||1} incluído(s)</span></div><b>{money(pricing.extra_pdv_terminal_price)}<small>/mês</small></b></div></article><article className="control-card"><div className="control-card-head"><div><small>FISCAL</small><h2>Monitor de emissões</h2></div><button onClick={()=>setView('fiscal')}>Abrir monitor</button></div><div className="fiscal-summary"><strong>{num(data.summary.fiscal_today)}</strong><span>documentos fiscais registrados hoje</span></div><div className="fiscal-mini">{data.fiscal.slice(0,4).map(f=><div key={text(f.id)}><span className={`status-dot ${text(f.status)}`}/><div><strong>{text(f.document_type).toUpperCase()} {text(f.number)||'sem número'}</strong><small>{text(f.company)} · {statusName[text(f.status)]||text(f.status)}</small></div></div>)}</div></article></section><section className="control-card"><div className="control-card-head"><div><small>CLIENTES</small><h2>Licenças recentes</h2></div><button onClick={()=>setView('clients')}>Ver todos</button></div><ClientTable rows={data.clients.slice(0,6)} onEdit={openEdit}/></section></>}
  {view==='clients'&&<section className="control-card"><div className="control-toolbar"><div><h2>Clientes do ERP</h2><p>Cadastre a loja e escolha exatamente quais módulos ela poderá utilizar.</p></div><input placeholder="Buscar cliente, razão social ou CNPJ..." value={clientSearch} onChange={e=>setClientSearch(e.target.value)}/></div><ClientTable rows={clients} onEdit={openEdit}/></section>}
  {view==='fiscal'&&<section className="control-card"><div className="control-toolbar"><div><h2>Emissões de todas as lojas</h2><p>Autorizações, rejeições, erros e arquivos fiscais centralizados.</p></div><div className="control-inline-filters"><input placeholder="Loja, chave, número ou erro..." value={fiscalSearch} onChange={e=>setFiscalSearch(e.target.value)}/><select value={fiscalStatus} onChange={e=>setFiscalStatus(e.target.value)}><option value="">Todos os status</option><option value="authorized">Autorizadas</option><option value="rejected">Rejeitadas</option><option value="processing">Processando</option><option value="draft">Rascunhos</option><option value="cancelled">Canceladas</option></select></div></div><div className="control-table-wrap"><table><thead><tr><th>Data</th><th>Loja</th><th>Documento</th><th>Ambiente</th><th>Status</th><th>Chave / Erro</th><th>Ações</th></tr></thead><tbody>{fiscal.length===0?<tr><td colSpan={7} className="empty">Nenhum documento encontrado.</td></tr>:fiscal.map(f=><tr key={text(f.id)}><td>{dt(f.created_at)}</td><td><strong>{text(f.company)}</strong><small>{text(f.branch)}</small></td><td><strong>{text(f.document_type).toUpperCase()} {text(f.number)||'—'}</strong><small>Série {text(f.series)||'—'}</small></td><td>{text(f.environment)==='production'?'Produção':'Homologação'}</td><td><span className={`control-status ${text(f.status)}`}>{statusName[text(f.status)]||text(f.status)}</span></td><td>{f.rejection_message?<span className="fiscal-error">{text(f.rejection_code)} · {text(f.rejection_message)}</span>:<span className="fiscal-key">{text(f.access_key)||'—'}</span>}</td><td><div className="table-actions"><button onClick={()=>run(()=>openFiscal(f))}>Detalhes</button>{f.xml_path?<a href={text(f.xml_path)} target="_blank" rel="noreferrer">XML</a>:null}</div></td></tr>)}</tbody></table></div></section>}
  {view==='updates'&&<UpdateCenter/>}
  {view==='pricing'&&<section className="control-grid-two pricing-grid"><form className="control-card control-form" onSubmit={e=>run(()=>savePricing(e))}><div className="control-card-head"><div><small>TABELA COMERCIAL</small><h2>Valores padrão</h2></div></div><div className="form-grid"><label>Mensalidade base do ERP<input name="base_erp_price" type="number" min="0" step="0.01" defaultValue={num(pricing.base_erp_price)}/></label><label>Usuários Gestão incluídos<input name="included_management_users" type="number" min="0" defaultValue={num(pricing.included_management_users)||5}/></label><label>Valor usuário adicional<input name="extra_management_user_price" type="number" min="0" step="0.01" defaultValue={num(pricing.extra_management_user_price)}/></label><label>ThorPDV incluídos<input name="included_pdv_terminals" type="number" min="0" defaultValue={num(pricing.included_pdv_terminals)||1}/></label><label>Valor ThorPDV adicional<input name="extra_pdv_terminal_price" type="number" min="0" step="0.01" defaultValue={num(pricing.extra_pdv_terminal_price)}/></label></div><button className="control-primary" disabled={pending}>Salvar tabela comercial</button></form><article className="control-card commercial-preview"><small>COMO A LICENÇA É CALCULADA</small><h2>Plano alinhado ao uso</h2><div className="formula"><span>ERP base</span><strong>{money(pricing.base_erp_price)}</strong><i>+</i><span>Usuários acima de {num(pricing.included_management_users)||5}</span><strong>{money(pricing.extra_management_user_price)} cada</strong><i>+</i><span>PDVs acima de {num(pricing.included_pdv_terminals)||1}</span><strong>{money(pricing.extra_pdv_terminal_price)} cada</strong></div><p>Os valores ficam centralizados no Thor Control. Cada licença guarda o valor contratado e seus limites.</p></article></section>}
  </section>
  {newOpen&&<div className="control-modal-bg"><form className="control-modal wide" onSubmit={e=>run(()=>createCustomer(e))}><header><div><small>NOVO CLIENTE</small><h2>Cadastrar ERP + licença</h2></div><button type="button" onClick={()=>setNewOpen(false)}>×</button></header><div className="modal-columns"><section><h3>Empresa e loja</h3><div className="form-grid"><label>Razão social *<input name="legal_name" required/></label><label>Nome fantasia<input name="trade_name"/></label><label>CNPJ<input name="cnpj"/></label><label>Inscrição Estadual<input name="state_registration"/></label><label>Regime tributário<select name="tax_regime"><option value="">Selecione</option><option value="simples_nacional">Simples Nacional</option><option value="lucro_presumido">Lucro Presumido</option><option value="lucro_real">Lucro Real</option></select></label><label>Email da empresa<input name="company_email" type="email"/></label><label>Telefone<input name="phone"/></label><label>Filial inicial<input name="branch_name" defaultValue="Matriz"/></label><label>Cidade<input name="city"/></label><label>UF<input name="state" maxLength={2}/></label></div><h3>Acesso inicial</h3><label>Email do administrador do ERP *<input name="admin_email" type="email" required/></label></section><section><h3>Licença</h3><div className="form-grid"><label>Status<select name="license_status" defaultValue="trial"><option value="trial">Teste</option><option value="active">Ativa</option></select></label><label>Usuários Gestão<input name="management_user_limit" type="number" min="1" defaultValue={num(pricing.included_management_users)||5}/></label><label>Terminais ThorPDV<input name="pdv_terminal_limit" type="number" min="0" defaultValue={num(pricing.included_pdv_terminals)||1}/></label><label>Validade<input name="expires_at" type="date"/></label></div><h3>Módulos habilitados</h3><div className="module-grid">{MODULES.map(([k,n,d])=><label className={`module-choice ${newModules[k]?'on':''}`} key={k}><input type="checkbox" checked={!!newModules[k]} onChange={e=>setNewModules(m=>({...m,[k]:e.target.checked}))}/><span><strong>{n}</strong><small>{d}</small></span></label>)}</div></section></div><footer><button type="button" onClick={()=>setNewOpen(false)}>Cancelar</button><button className="control-primary" disabled={pending}>Criar cliente e licença</button></footer></form></div>}
  {editing&&<div className="control-modal-bg"><form className="control-modal wide" onSubmit={e=>run(()=>saveLicense(e))}><header><div><small>EDITAR LICENÇA</small><h2>{text(editing.name)}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></header><div className="form-grid four"><label>Status<select name="status" defaultValue={text(editing.license_status)}><option value="trial">Teste</option><option value="active">Ativa</option><option value="suspended">Suspensa</option><option value="cancelled">Cancelada</option></select></label><label>Usuários Gestão<input name="management_user_limit" type="number" min="0" defaultValue={num(editing.management_user_limit)}/></label><label>ThorPDV<input name="pdv_terminal_limit" type="number" min="0" defaultValue={num(editing.pdv_terminal_limit)}/></label><label>Validade<input name="expires_at" type="date" defaultValue={editing.expires_at?new Date(text(editing.expires_at)).toISOString().slice(0,10):''}/></label></div><div className="module-grid edit">{MODULES.map(([k,n,d])=><label className={`module-choice ${editModules[k]?'on':''}`} key={k}><input type="checkbox" checked={!!editModules[k]} onChange={e=>setEditModules(m=>({...m,[k]:e.target.checked}))}/><span><strong>{n}</strong><small>{d}</small></span></label>)}</div><label>Observação<textarea name="notes" rows={3} defaultValue={text(editing.license_notes)}/></label><footer><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="control-primary" disabled={pending}>Aplicar licença</button></footer></form></div>}
  {created&&<div className="control-modal-bg"><section className="control-modal success-modal"><header><div><small>CLIENTE CRIADO</small><h2>Acesso inicial gerado</h2></div><button onClick={()=>setCreated(null)}>×</button></header><div className="success-icon">✓</div><p>Entregue a senha temporária ao administrador da loja. O sistema exigirá a troca no primeiro acesso.</p><div className="credential"><span>Senha temporária</span><strong>{text(created.temporary_password)}</strong></div><div className="credential"><span>Mensalidade calculada</span><strong>{money(created.monthly_amount)}</strong></div><button className="control-primary" onClick={()=>setCreated(null)}>Concluir</button></section></div>}
  {fiscalDetail&&<div className="control-drawer-bg" onClick={()=>setFiscalDetail(null)}><aside className="control-drawer" onClick={e=>e.stopPropagation()}><header><div><small>DOCUMENTO FISCAL</small><h2>{text(fiscalDetail.document_type).toUpperCase()} {text(fiscalDetail.number)||'—'}</h2></div><button onClick={()=>setFiscalDetail(null)}>×</button></header><dl><div><dt>Loja</dt><dd>{text(fiscalDetail.company)} · {text(fiscalDetail.branch)}</dd></div><div><dt>Status</dt><dd><span className={`control-status ${text(fiscalDetail.status)}`}>{statusName[text(fiscalDetail.status)]||text(fiscalDetail.status)}</span></dd></div><div><dt>Ambiente</dt><dd>{text(fiscalDetail.environment)==='production'?'Produção':'Homologação'}</dd></div><div><dt>Chave</dt><dd className="mono">{text(fiscalDetail.access_key)||'—'}</dd></div><div><dt>Protocolo</dt><dd>{text(fiscalDetail.protocol)||'—'}</dd></div><div><dt>Autorização</dt><dd>{dt(fiscalDetail.authorization_at)}</dd></div><div><dt>Rejeição / erro</dt><dd className="fiscal-error">{text(fiscalDetail.rejection_code)} {text(fiscalDetail.rejection_message)||'—'}</dd></div></dl><div className="drawer-actions">{fiscalDetail.xml_path?<a href={text(fiscalDetail.xml_path)} target="_blank" rel="noreferrer">Baixar XML</a>:<button disabled>XML indisponível</button>}{fiscalDetail.pdf_path?<a href={text(fiscalDetail.pdf_path)} target="_blank" rel="noreferrer">Abrir DANFE</a>:null}</div><details><summary>Resposta técnica</summary><pre>{JSON.stringify(fiscalDetail.response_payload??{},null,2)}</pre></details></aside></div>}
 </main>;
}

function ClientTable({rows,onEdit}:{rows:Row[];onEdit:(r:Row)=>void}){return <div className="control-table-wrap"><table><thead><tr><th>Cliente</th><th>Licença</th><th>Módulos</th><th>Gestão</th><th>ThorPDV</th><th>Mensalidade</th><th></th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={7} className="empty">Nenhum cliente encontrado.</td></tr>:rows.map(c=><tr key={text(c.tenant_id)}><td><strong>{text(c.name)}</strong><small>{text(c.cnpj)||text(c.legal_name)}</small></td><td><span className={`control-status ${text(c.license_status)}`}>{statusName[text(c.license_status)]||text(c.license_status)}</span><small>{text(c.plan_name)}</small></td><td><strong>{Object.values((c.modules??{}) as Record<string,boolean>).filter(Boolean).length}</strong><small>habilitados</small></td><td><strong>{num(c.management_user_limit)}</strong><small>usuários</small></td><td><strong>{num(c.pdv_devices)} / {num(c.pdv_terminal_limit)}</strong><small>ativos / licença</small></td><td><strong>{money(c.monthly_amount)}</strong><small>mensal</small></td><td><button className="row-button" onClick={()=>onEdit(c)}>Editar licença</button></td></tr>)}</tbody></table></div>}
