const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('thor', {
  status: () => ipcRenderer.invoke('thor:status'),
  enroll: (payload) => ipcRenderer.invoke('thor:enroll', payload),
  sync: () => ipcRenderer.invoke('thor:sync'),
  syncDiagnostics: () => ipcRenderer.invoke('thor:sync-diagnostics'),
  performanceMetrics: (limit = 200) => ipcRenderer.invoke('thor:performance-metrics', limit),
  recoverSync: () => ipcRenderer.invoke('thor:recover-sync'),
  disconnectDevice: () => ipcRenderer.invoke('thor:disconnect-device'),
  searchProducts: (query) => ipcRenderer.invoke('thor:search-products', query),
  allProducts: () => ipcRenderer.invoke('thor:all-products'),
  customers: (query) => ipcRenderer.invoke('thor:customers', query),
  salesOrders: (query = '') => ipcRenderer.invoke('thor:sales-orders', query),
  paymentTerms: () => ipcRenderer.invoke('thor:payment-terms'),
  setCommercialContext: (payload = {}) => ipcRenderer.invoke('thor:set-commercial-context', payload),
  quoteSale: (items, discount = 0) => ipcRenderer.invoke('thor:quote-sale', items, discount),
  quoteCheckout: (payload) => ipcRenderer.invoke('thor:quote-checkout', payload),
  operators: () => ipcRenderer.invoke('thor:operators'),
  operatorLogin: (payload) => ipcRenderer.invoke('thor:operator-login', payload),
  operatorLogout: () => ipcRenderer.invoke('thor:operator-logout'),
  supervisorAuthorize: (payload) => ipcRenderer.invoke('thor:supervisor-authorize', payload),
  openCash: (payload) => ipcRenderer.invoke('thor:open-cash', payload),
  cashMovement: (payload) => ipcRenderer.invoke('thor:cash-movement', payload),
  cashPreview: (options = {}) => ipcRenderer.invoke('thor:cash-preview', options),
  cashSessions: (filters = {}) => ipcRenderer.invoke('thor:cash-sessions', filters),
  closeHistoricalCash: (payload) => ipcRenderer.invoke('thor:close-historical-cash', payload),
  closeCash: (payload) => ipcRenderer.invoke('thor:close-cash', payload),
  lastCashClose: () => ipcRenderer.invoke('thor:last-cash-close'),
  printCashClose: (summary) => ipcRenderer.invoke('thor:print-cash-close', summary),
  printCashMovement: (receipt) => ipcRenderer.invoke('thor:print-cash-movement', receipt),
  receivables: (query = '', customerId = null) => ipcRenderer.invoke('thor:receivables', query, customerId),
  receiveReceivables: (payload = {}) => ipcRenderer.invoke('thor:receive-receivables', payload),
  printReceivableReceipt: (receipt) => ipcRenderer.invoke('thor:print-receivable-receipt', receipt),
  finalizeSale: (payload) => ipcRenderer.invoke('thor:finalize-sale', payload),
  saveTermDuplicatesPdf: (payload) => ipcRenderer.invoke('thor:save-term-duplicates-pdf', payload),
  cancelSale: (payload) => ipcRenderer.invoke('thor:cancel-sale', payload),
  returnSale: (payload) => ipcRenderer.invoke('thor:return-sale', payload),
  storeCreditVoucher: (number) => ipcRenderer.invoke('thor:store-credit-voucher', number),
  storeCreditVouchers: (query = '', limit = 50) => ipcRenderer.invoke('thor:store-credit-vouchers', query, limit),
  printStoreCreditVoucher: (voucher) => ipcRenderer.invoke('thor:print-store-credit-voucher', voucher),
  requestNfce: (payload) => ipcRenderer.invoke('thor:request-nfce', payload),
  fiscalSales: (query = '') => ipcRenderer.invoke('thor:fiscal-sales', query),
  fiscalSale: (key) => ipcRenderer.invoke('thor:fiscal-sale', key),
  printers: () => ipcRenderer.invoke('thor:printers'),
  serialPorts: () => ipcRenderer.invoke('thor:serial-ports'),
  settings: () => ipcRenderer.invoke('thor:settings'),
  saveSettings: (settings) => ipcRenderer.invoke('thor:save-settings', settings),
  v3Settings: () => ipcRenderer.invoke('thor:v3-settings'),
  saveV3Settings: (settings) => ipcRenderer.invoke('thor:save-v3-settings', settings),
  setPrinter: (name) => ipcRenderer.invoke('thor:set-printer', name),
  openDrawer: () => ipcRenderer.invoke('thor:open-drawer'),
  readScale: () => ipcRenderer.invoke('thor:read-scale'),
  paymentIntegrations: () => ipcRenderer.invoke('thor:payment-integrations'),
  beginPayment: (payload) => ipcRenderer.invoke('thor:begin-payment', payload),
  printSale: (saleKey, type = 'pre_sale', reprint = false) => ipcRenderer.invoke('thor:print-sale', saleKey, type, reprint),
  shareSaleWhatsapp: (saleKey, type = 'pre_sale', phone = '') => ipcRenderer.invoke('thor:share-sale-whatsapp', saleKey, type, phone),
  updateInfo: () => ipcRenderer.invoke('thor:update-info'),
  checkForUpdates: () => ipcRenderer.invoke('thor:check-update'),
  installUpdate: () => ipcRenderer.invoke('thor:install-update'),
  onUpdateProgress: (callback) => { const handler=(_event,payload)=>callback(payload); ipcRenderer.on('thor:update-progress',handler); return ()=>ipcRenderer.removeListener('thor:update-progress',handler); },
  onUpdateStatus: (callback) => { const handler=(_event,payload)=>callback(payload); ipcRenderer.on('thor:update-status',handler); return ()=>ipcRenderer.removeListener('thor:update-status',handler); },
  printLast: () => ipcRenderer.invoke('thor:print-last'),
});
