export const RTC_TABLE_REFERENCE = {
  informe: 'IT 2025.002 v1.60',
  publishedAt: '2026-06-23',
  publishedAtLabel: '23/06/2026',
  source: 'Portal NF-e / SVRS',
  totalCst: 18,
  totalClassifications: 164,
} as const;

export type RtcCstOption = { code: string; label: string };
export type RtcClassTribOption = { code: string; cst: string; label: string };

export const RTC_CST_OPTIONS: RtcCstOption[] = [
  { code: '000', label: 'Tributação integral' },
  { code: '010', label: 'Tributação com alíquotas uniformes' },
  { code: '011', label: 'Tributação com alíquotas uniformes reduzidas' },
  { code: '200', label: 'Alíquota reduzida' },
  { code: '220', label: 'Alíquota fixa' },
  { code: '221', label: 'Alíquota fixa proporcional' },
  { code: '222', label: 'Redução de Base de Cálculo' },
  { code: '400', label: 'Isenção' },
  { code: '410', label: 'Imunidade e não incidência' },
  { code: '510', label: 'Diferimento' },
  { code: '515', label: 'Diferimento com redução de alíquota' },
  { code: '550', label: 'Suspensão' },
  { code: '620', label: 'Tributação Monofásica' },
  { code: '800', label: 'Transferência de crédito' },
  { code: '810', label: 'Ajuste de IBS na ZFM' },
  { code: '811', label: 'Ajustes' },
  { code: '820', label: 'Tributação em documento específico' },
  { code: '830', label: 'Exclusão de base de cálculo' },
];

const rtc = (code: string, label: string): RtcClassTribOption => ({ code, cst: code.slice(0, 3), label });

export const RTC_CLASS_TRIB_OPTIONS: RtcClassTribOption[] = [
  rtc('000001', 'Situações tributadas integralmente pelo IBS e CBS.'),
  rtc('000002', 'Exploração de via'),
  rtc('000003', 'Regime automotivo - projetos incentivados (art. 311)'),
  rtc('000004', 'Regime automotivo - projetos incentivados (art. 312)'),
  rtc('000005', 'Operação com EAC destinado à mistura com gasolina A, mas com saída do biocombustível com destinação diversa'),
  rtc('010001', 'Operações do FGTS não realizadas pela Caixa Econômica Federal'),
  rtc('010002', 'Operações do serviço financeiro'),
  rtc('011001', 'Planos de assistência funerária'),
  rtc('011002', 'Planos de assistência à saúde'),
  rtc('011003', 'Intermediação de planos de assistência à saúde'),
  rtc('011004', 'Concursos e prognósticos'),
  rtc('011005', 'Planos de assistência à saúde de animais domésticos'),
  rtc('200001', 'Serviços de transporte de bens até as zonas de processamento de exportação e bens exportados a partir das zonas de processamento de exportação'),
  rtc('200002', 'Fornecimento ou importação para produtor rural não contribuinte ou TAC'),
  rtc('200003', 'Vendas de produtos destinados à alimentação humana (Anexo I)'),
  rtc('200004', 'Fornecimento de dispositivos médicos (Anexo XII)'),
  rtc('200005', 'Fornecimento de dispositivos médicos para órgãos da administração pública e entidades de saúde imunes (Anexo IV)'),
  rtc('200006', 'Situação de emergência de saúde pública reconhecida pelo Poder público'),
  rtc('200007', 'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo XIII)'),
  rtc('200008', 'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência adquiridos por órgãos da administração pública (Anexo V)'),
  rtc('200009', 'Fornecimento dos medicamentos registrados na Anvisa'),
  rtc('200010', 'Fornecimento dos medicamentos registrados na Anvisa, adquiridos por órgãos da administração pública'),
  rtc('200011', 'Fornecimento das composições para nutrição enteral e parenteral quando adquiridas por órgãos da administração pública (Anexo VI)'),
  rtc('200012', 'Situação de emergência de saúde pública reconhecida pelo Poder público'),
  rtc('200013', 'Fornecimento de tampões higiênicos, absorventes higiênicos internos ou externos'),
  rtc('200014', 'Fornecimento dos produtos hortícolas, frutas e ovos (Anexo XV)'),
  rtc('200015', 'Venda de automóveis de passageiros de fabricação nacional adquiridos por motoristas profissionais ou pessoas com deficiência'),
  rtc('200016', 'Prestação de serviços de pesquisa e desenvolvimento por Instituição Científica, Tecnológica e de Inovação (ICT)'),
  rtc('200017', 'Operações relacionadas ao FGTS'),
  rtc('200018', 'Operações de resseguro e retrocessão'),
  rtc('200019', 'Importador dos serviços financeiros contribuinte'),
  rtc('200020', 'Operação praticada por sociedades cooperativas optantes por regime específico do IBS e CBS'),
  rtc('200021', 'Serviços de transporte público coletivo de passageiros ferroviário e hidroviário'),
  rtc('200022', 'Operação originada fora da ZFM que destine bem material industrializado a contribuinte estabelecido na ZFM'),
  rtc('200023', 'Operação realizada por indústria incentivada que destine bem material intermediário para outra indústria incentivada na ZFM'),
  rtc('200024', 'Operação originada fora das Áreas de Livre Comércio destinada a contribuinte estabelecido nas Áreas de Livre Comércio'),
  rtc('200025', 'Fornecimento dos serviços de educação relacionados ao Programa Universidade para Todos (Prouni)'),
  rtc('200026', 'Locação de imóveis localizados nas zonas reabilitadas'),
  rtc('200027', 'Operações de locação, cessão onerosa e arrendamento de bens imóveis'),
  rtc('200028', 'Fornecimento dos serviços de educação (Anexo II)'),
  rtc('200029', 'Fornecimento dos serviços de saúde humana (Anexo III)'),
  rtc('200030', 'Venda dos dispositivos médicos (Anexo IV)'),
  rtc('200031', 'Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo V)'),
  rtc('200032', 'Fornecimento dos medicamentos registrados na Anvisa ou produzidos por farmácias de manipulação, ressalvados os sujeitos à alíquota zero'),
  rtc('200033', 'Fornecimento das composições para nutrição enteral e parenteral (Anexo VI)'),
  rtc('200034', 'Fornecimento dos alimentos destinados ao consumo humano (Anexo VII)'),
  rtc('200035', 'Fornecimento dos produtos de higiene pessoal e limpeza (Anexo VIII)'),
  rtc('200036', 'Fornecimento de produtos agropecuários, aquícolas, pesqueiros, florestais e extrativistas vegetais in natura'),
  rtc('200037', 'Fornecimento de serviços ambientais de conservação ou recuperação da vegetação nativa'),
  rtc('200038', 'Fornecimento dos insumos agropecuários e aquícolas (Anexo IX)'),
  rtc('200039', 'Fornecimento dos bens e serviços relacionados com produções nacionais artísticas, culturais, de eventos, jornalísticas e audiovisuais (Anexo X)'),
  rtc('200040', 'Fornecimento de serviços de comunicação institucional à administração pública'),
  rtc('200041', 'Fornecimento de serviço de educação desportiva (art. 141, I)'),
  rtc('200042', 'Fornecimento de serviço de gestão e exploração do desporto (art. 141, II)'),
  rtc('200043', 'Fornecimento à administração pública dos serviços e dos bens relativos à soberania (Anexo XI)'),
  rtc('200044', 'Operações e prestações de serviços de segurança da informação e segurança cibernética desenvolvidos por sociedade que tenha sócio brasileiro (Anexo XI)'),
  rtc('200045', 'Operações relacionadas a projetos de reabilitação urbana de zonas históricas e de áreas críticas de recuperação e reconversão urbanística'),
  rtc('200046', 'Operações com bens imóveis'),
  rtc('200047', 'Bares e Restaurantes'),
  rtc('200048', 'Hotelaria, Parques de Diversão e Parques Temáticos'),
  rtc('200049', 'Transporte coletivo de passageiros rodoviário, ferroviário e hidroviário'),
  rtc('200050', 'Serviços de transporte aéreo regional coletivo de passageiros ou de carga'),
  rtc('200051', 'Agências de Turismo'),
  rtc('200052', 'Prestação de serviços de profissões intelectuais'),
  rtc('200053', 'Fornecimento de medicamentos registrados na Anvisa, quando classificados como soros ou vacinas'),
  rtc('200054', 'Fornecimento de bem material pela cooperativa de produção agropecuária a associado não sujeito ao regime regular do IBS e da CBS'),
  rtc('220001', 'Incorporação imobiliária submetida ao regime especial de tributação'),
  rtc('220002', 'Incorporação imobiliária submetida ao regime especial de tributação'),
  rtc('220003', 'Alienação de imóvel decorrente de parcelamento do solo'),
  rtc('221001', 'Locação, cessão onerosa ou arrendamento de bem imóvel com alíquota sobre a receita bruta'),
  rtc('221002', 'Incorporação imobiliária submetida ao regime especial de tributação'),
  rtc('221003', 'Incorporação imobiliária submetida ao regime especial de tributação'),
  rtc('221004', 'Alienação de imóvel decorrente de parcelamento do solo'),
  rtc('222001', 'Transporte internacional de passageiros, caso os trechos de ida e volta sejam vendidos em conjunto'),
  rtc('400001', 'Fornecimento de serviços de transporte público coletivo de passageiros rodoviário e metroviário'),
  rtc('400002', 'Fornecimento de serviços de transporte público coletivo de passageiros rodoviário e metroviário com medição por quilômetro rodado'),
  rtc('410001', 'Fornecimento de bonificações quando constem no documento fiscal e que não dependam de evento posterior'),
  rtc('410002', 'Transferências entre estabelecimentos pertencentes ao mesmo contribuinte'),
  rtc('410003', 'Doações sem contraprestação em benefício do doador'),
  rtc('410004', 'Exportações de bens e serviços'),
  rtc('410005', 'Fornecimentos realizados pela União, pelos Estados, pelo Distrito Federal e pelos Municípios'),
  rtc('410006', 'Fornecimentos realizados por entidades religiosas e templos de qualquer culto'),
  rtc('410007', 'Fornecimentos realizados por partidos políticos, entidades sindicais e instituições de educação e de assistência social'),
  rtc('410008', 'Fornecimentos de livros, jornais, periódicos e do papel destinado a sua impressão'),
  rtc('410009', 'Fornecimentos de fonogramas e videofonogramas musicais produzidos no Brasil'),
  rtc('410010', 'Fornecimentos de serviço de comunicação nas modalidades de radiodifusão sonora e de sons e imagens de recepção livre e gratuita'),
  rtc('410011', 'Fornecimentos de ouro, quando definido em lei como ativo financeiro ou instrumento cambial'),
  rtc('410012', 'Fornecimento de condomínio edilício não optante pelo regime regular'),
  rtc('410013', 'Exportações de combustíveis'),
  rtc('410014', 'Fornecimento de produtor rural não contribuinte'),
  rtc('410015', 'Fornecimento por transportador autônomo não contribuinte'),
  rtc('410016', 'Fornecimento ou aquisição de resíduos sólidos'),
  rtc('410017', 'Aquisição de bem móvel com crédito presumido sob condição de revenda realizada'),
  rtc('410018', 'Operações relacionadas aos fundos garantidores e executores de políticas públicas'),
  rtc('410019', 'Exclusão da gorjeta na base de cálculo no fornecimento de alimentação'),
  rtc('410020', 'Exclusão do valor de intermediação na base de cálculo no fornecimento de alimentação'),
  rtc('410021', 'Contribuição de que trata o art. 149-A da Constituição Federal'),
  rtc('410022', 'Consolidação da propriedade do bem pelo credor'),
  rtc('410023', 'Alienação de bens móveis ou imóveis que tenham sido objeto de garantia em que o prestador da garantia não seja contribuinte'),
  rtc('410024', 'Consolidação da propriedade do bem pelo grupo de consórcio'),
  rtc('410025', 'Alienação de bem que tenha sido objeto de garantia em que o prestador da garantia não seja contribuinte'),
  rtc('410026', 'Doação com anulação de crédito'),
  rtc('410027', 'Exportação de serviço ou de bem imaterial'),
  rtc('410028', 'Operações com bens imóveis realizadas por pessoas físicas não consideradas contribuintes'),
  rtc('410029', 'Operações acobertadas somente pelo ICMS'),
  rtc('410030', 'Estorno de crédito por perecimento, deteriorização, roubo, furto ou extravio'),
  rtc('410031', 'Fornecimento em período anterior ao início de vigência de incidências de CBS e IBS'),
  rtc('410032', 'Tributos incidentes na operação que não integram a base de cálculo do IBS e da CBS'),
  rtc('410033', 'Operações de Fundos de Investimento Imobiliário (FII) e Fundos de Investimento nas Cadeias Produtivas do Agronegócio (Fiagro)'),
  rtc('410034', 'Operações de fundos de investimento'),
  rtc('410035', 'Fornecimento realizado por nanoempreendedor'),
  rtc('410036', 'Descontos incondicionais'),
  rtc('410037', 'Importação de bens materiais sem incidência de IBS e CBS'),
  rtc('410999', 'Operações não onerosas sem previsão de tributação, não especificadas anteriormente'),
  rtc('510001', 'Operações, sujeitas a diferimento, com energia elétrica, relativas à importação, geração, comercialização, distribuição e transmissão'),
  rtc('515001', 'Operações, sujeitas a diferimento, com insumos agropecuários e aquícolas (Anexo IX)'),
  rtc('550001', 'Exportações de bens materiais'),
  rtc('550002', 'Regime de Trânsito'),
  rtc('550003', 'Regimes de Depósito (art. 85)'),
  rtc('550004', 'Regimes de Depósito (art. 87)'),
  rtc('550005', 'Regimes de Depósito (art. 87, Parágrafo único)'),
  rtc('550006', 'Regimes de Permanência Temporária'),
  rtc('550007', 'Regimes de Aperfeiçoamento'),
  rtc('550008', 'Importação de bens para o Regime de Repetro-Temporário'),
  rtc('550009', 'GNL-Temporário'),
  rtc('550010', 'Repetro-Permanente'),
  rtc('550011', 'Repetro-Industrialização'),
  rtc('550012', 'Repetro-Nacional'),
  rtc('550013', 'Repetro-Entreposto'),
  rtc('550014', 'Zona de Processamento de Exportação'),
  rtc('550015', 'Regime Tributário para Incentivo à Modernização e à Ampliação da Estrutura Portuária'),
  rtc('550016', 'Regime Especial de Incentivos para o Desenvolvimento da Infraestrutura'),
  rtc('550017', 'Regime Tributário para Incentivo à Atividade Econômica Naval'),
  rtc('550018', 'Desoneração da aquisição de bens de capital'),
  rtc('550019', 'Importação de bem material por indústria incentivada para utilização na ZFM'),
  rtc('550020', 'Áreas de livre comércio'),
  rtc('550021', 'Industrialização destinada a exportações'),
  rtc('550022', 'Regime Especial de Incentivos para a Produção de Hidrogênio de Baixa Emissão de Carbono (Rehidro)'),
  rtc('550023', 'Operações com hidrocarbonetos líquidos derivados de petróleo não combustíveis ou de gás natural, inclusive nafta'),
  rtc('550024', 'Regime Tributário para Incentivo à Atividade Naval - Renaval (Art. 107, II)'),
  rtc('550025', 'Regime Tributário para Incentivo à Atividade Naval - Renaval (Art. 107, III)'),
  rtc('620001', 'Tributação monofásica sobre combustíveis'),
  rtc('620002', 'Tributação monofásica com responsabilidade pela retenção sobre combustíveis'),
  rtc('620003', 'Tributação monofásica com responsabilidade de retenção de tributos por terceiros'),
  rtc('620004', 'Tributação monofásica sobre mistura de EAC com gasolina A em percentual superior ao obrigatório'),
  rtc('620005', 'Tributação monofásica sobre mistura de EAC com gasolina A em percentual inferior ao obrigatório'),
  rtc('620006', 'Tributação monofásica sobre combustíveis cobrada anteriormente'),
  rtc('620007', 'Perecimento, deteriorização, roubo, furto ou extravio no regime monofásico'),
  rtc('800001', 'Fusão, cisão ou incorporação'),
  rtc('800002', 'Transferência de crédito do associado, inclusive as cooperativas singulares'),
  rtc('810001', 'Crédito presumido sobre o valor apurado nos fornecimentos a partir da ZFM'),
  rtc('811001', 'Anulação de Crédito por Saídas Imunes/Isentas'),
  rtc('811002', 'Débitos de notas fiscais não processadas na apuração'),
  rtc('811003', 'Desenquadramento do Simples Nacional'),
  rtc('820001', 'Documento com informações de fornecimento de serviços de planos de assistência à saúde elencados no art. 234 da LC 214/2025'),
  rtc('820002', 'Documento com informações de fornecimento de serviços de planos de assistência funerária'),
  rtc('820003', 'Documento com informações de fornecimento de serviços de planos de assistência à saúde de animais domésticos'),
  rtc('820004', 'Documento com informações de prestação de serviços de concursos de prognósticos'),
  rtc('820005', 'Documento com informações de alienação de bens imóveis'),
  rtc('820006', 'Documento com informações de fornecimento de serviços de exploração de via'),
  rtc('820007', 'Documento com informações de fornecimento de serviços financeiros'),
  rtc('820008', 'Documento com informações de fornecimento, mas com tributação realizada em fatura anterior'),
  rtc('820009', 'Cobrança relativa a fornecimentos declarados em outro documento'),
  rtc('830001', 'Documento com exclusão da BC da CBS e do IBS de energia elétrica fornecida pela distribuidora à UC'),
];

export function rtcClassesForCst(cst: string) {
  return RTC_CLASS_TRIB_OPTIONS.filter((option) => option.cst === cst);
}
