export type MenuItem=[string,string];
export type MenuGroup=[string,string,MenuItem[]];
export const advancedMenu:MenuGroup[]=[
['Pessoas','◎',[['Clientes','/dashboard/clientes'],['Fornecedores','/dashboard/fornecedores'],['Perfis PDV','/dashboard/perfis-pdv'],['Usuários PDV','/dashboard/usuarios-pdv'],['Perfis ADM','/dashboard/perfis-adm'],['Usuários ADM','/dashboard/usuarios-adm']]],
['Vendas','▤',[['Operações de Caixa','/dashboard/vendas'],['Nova Venda','/dashboard/vendas/nova'],['Pedidos de Venda','/dashboard/vendas/pedidos']]],
['Produtos','▦',[['Produtos','/dashboard/produtos'],['Arquivos','/dashboard/produtos/arquivos'],['Marcas','/dashboard/produtos/marcas'],['Categorias','/dashboard/produtos/categorias'],['Atributos','/dashboard/produtos/atributos'],['Unidades de Medida','/dashboard/produtos/unidades'],['Grupos','/dashboard/grupos'],['Classes','/dashboard/classes'],['Modificadores','/dashboard/modificadores']]],
['Tabela de Preços','◇',[['Tabelas','/dashboard/tabelas-precos'],['Copiar','/dashboard/tabelas-precos/copiar'],['Ajustes Programados','/dashboard/tabelas-precos/ajustes'],['Promoções','/dashboard/promocoes']]],
['Estoque','▥',[['Movimentações','/dashboard/estoque'],['Locais de Estoque','/dashboard/estoque/locais'],['Compras / Entradas','/dashboard/compras'],['Inventário','/dashboard/estoque/inventario'],['Produção / Cozinha','/dashboard/estoque/producao'],['Ajustes','/dashboard/estoque/ajustes'],['Transferências','/dashboard/estoque/transferencias']]],
['Financeiro','$',[['Contas a Receber','/dashboard/financeiro/receber'],['Contas a Pagar','/dashboard/financeiro/pagar'],['Contas Bancárias','/dashboard/financeiro/contas-bancarias'],['Homologação Bancária','/dashboard/financeiro/homologacao-bancaria'],['Remessa / Retorno','/dashboard/financeiro/remessa-retorno'],['Fluxo de Caixa','/dashboard/financeiro/fluxo-caixa'],['Conciliação','/dashboard/financeiro/conciliacao']]],
['Administrativo','⚙',[['Matriz','/dashboard/administrativo/empresas'],['Lojas / Filiais','/dashboard/administrativo/filiais'],['Caixas e PDVs','/dashboard/administrativo/pdvs'],['PDV Desktop / Agentes','/dashboard/administrativo/pdv-desktop'],['Auditoria Gerencial','/dashboard/administrativo/auditoria'],['Fiscal','/dashboard/fiscal'],['Documentos Fiscais','/dashboard/documentos-fiscais'],['Integrações','/dashboard/integracoes'],['Configurações Operacionais','/dashboard/configuracoes'],['Opções de Vendas','/dashboard/configuracoes/opcoes-vendas']]],
['Relatórios','≡',[['Central de Relatórios','/dashboard/relatorios'],['Fechamento de Caixa','/dashboard/relatorios/fechamento-caixa'],['Fechamento Detalhado','/dashboard/relatorios/fechamento-caixa-detalhado'],['Relatório de Estoque','/dashboard/relatorios/estoque'],['Posição de Estoque','/dashboard/relatorios/posicao-estoque'],['Relatório de Inventário','/dashboard/relatorios/inventario'],['Produtos sem Giro','/dashboard/relatorios/produtos-sem-giro'],['Estoque Parado','/dashboard/relatorios/estoque-parado'],['Ranking de Produtos','/dashboard/relatorios/ranking-produtos'],['Curva ABC','/dashboard/relatorios/curva-abc'],['Margem por Produto','/dashboard/relatorios/margem-produto'],['Produtos × Forma Pagamento','/dashboard/relatorios/produtos-forma-pagamento'],['Vendedores / Operadores','/dashboard/relatorios/vendedores'],['Comissão por Vendedor','/dashboard/relatorios/comissao-vendedor'],['Vendas por Hora / Dia','/dashboard/relatorios/vendas-horario'],['Ticket Médio','/dashboard/relatorios/ticket-medio'],['Formas de Pagamento','/dashboard/relatorios/formas-pagamento'],['DRE Gerencial','/dashboard/relatorios/dre-gerencial'],['CMV','/dashboard/relatorios/cmv'],['Lucro Bruto','/dashboard/relatorios/lucro-bruto'],['Demonstrativo Fluxo de Caixa','/dashboard/relatorios/fluxo-caixa'],['Contas a Receber','/dashboard/relatorios/contas-receber'],['Contas a Pagar','/dashboard/relatorios/contas-pagar'],['Balanço Patrimonial','/dashboard/relatorios/balanco-patrimonial'],['Vendas por CFOP','/dashboard/relatorios/vendas-cfop'],['Produtos por Tributação','/dashboard/relatorios/produtos-tributacao']]]
];