'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { branchLicenseList, branchLicenseSave } from './branch-license-actions';

type Row=Record<string,unknown>;
const text=(v:unknown)=>v==null?'':String(v);
const num=(v:unknown)=>Number(v||0);
const digits=(v:string)=>v.replace(/\D/g,'');

const messages:Record<string,string>={
 branch_module_not_licensed:'O módulo Lojas / Filiais não está liberado nesta licença. Habilite-o no ThorControl.',
 branch_license_limit_reached:'O limite de lojas/filiais contratado foi atingido. Amplie a licença no ThorControl.',
 branch_license_inactive:'A licença não está ativa para criar uma nova filial.',
 branch_name_required:'Informe o nome da filial.',invalid_cnpj:'CNPJ inválido.',invalid_state:'UF inválida.',
 branch_cnpj_already_registered:'Este CNPJ já está cadastrado em outra unidade.',headquarters_managed_in_matrix:'Os dados da Matriz são alterados em Administrativo → Matriz.',
};

export function BranchesWorkspace({initialBranches,license}:{initialBranches:Row[];license:Row}){
 const router=useRouter();const [rows,setRows]=useState<Row[]>(initialBranches);const [editing,setEditing]=useState<Row|null>(null);const [open,setOpen]=useState(false);const [message,setMessage]=useState('');const [lookup,setLookup]=useState('');const [pending,startTransition]=useTransition();
 useEffect(()=>{let alive=true;void branchLicenseList().then(r=>{if(alive&&r.ok)setRows(r.data)});return()=>{alive=false}},[]);
 const branchLimit=Math.max(num(license.branch_limit),1);const used=rows.length;const remaining=Math.max(branchLimit-used,0);const enabled=Boolean((license.modules as Record<string,boolean>|undefined)?.branches);const headquarters=rows.find(b=>Boolean(b.is_headquarters));
 const extraUsed=Math.max(used-1,0);const extraLicensed=Math.max(branchLimit-1,0);
 const sorted=useMemo(()=>[...rows].sort((a,b)=>Number(Boolean(b.is_headquarters))-Number(Boolean(a.is_headquarters))||text(a.name).localeCompare(text(b.name),'pt-BR')),[rows]);
 const empty:Row={name:'',cnpj:'',state_registration:'',municipal_registration:'',crt:'',email:'',phone:'',contact:'',responsible:'',postal_code:'',street:'',number:'',complement:'',district:'',city:'',state:'',ibge_city_code:''};
 const current=editing??empty;
 function beginNew(){setEditing(null);setOpen(true);setMessage('');}
 function beginEdit(row:Row){if(row.is_headquarters){setMessage('A Matriz é editada em Administrativo → Matriz.');return}setEditing(row);setOpen(true);setMessage('');}
 async function lookupCnpj(form:HTMLFormElement){const fd=new FormData(form);const cnpj=digits(text(fd.get('cnpj')));if(cnpj.length!==14){setMessage('Digite os 14 dígitos do CNPJ.');return}setLookup('cnpj');try{const r=await fetch(`/api/lookup/cnpj?cnpj=${cnpj}`,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error();const d=j.data||{};const set=(name:string,value:unknown)=>{const el=form.elements.namedItem(name) as HTMLInputElement|null;if(el&&!el.value)el.value=text(value)};set('name',d.trade_name||d.name);set('state_registration',d.state_registration);set('email',d.email);set('phone',d.phone);set('postal_code',d.postal_code);set('street',d.street);set('number',d.number);set('complement',d.complement);set('district',d.district);set('city',d.city);set('state',d.state);set('ibge_city_code',d.ibge_city_code);setMessage('Dados da filial carregados pelo CNPJ. Revise antes de salvar.');}catch{setMessage('Não foi possível consultar o CNPJ agora. O cadastro manual continua disponível.');}finally{setLookup('')}}
 async function lookupCep(form:HTMLFormElement){const fd=new FormData(form);const cep=digits(text(fd.get('postal_code')));if(cep.length!==8)return;setLookup('cep');try{const r=await fetch(`/api/lookup/cep?cep=${cep}`,{cache:'no-store'});const j=await r.json();if(r.ok&&j.ok){const d=j.data||{};const set=(name:string,value:unknown)=>{const el=form.elements.namedItem(name) as HTMLInputElement|null;if(el&&!el.value)el.value=text(value)};set('street',d.street);set('complement',d.complement);set('district',d.district);set('city',d.city);set('state',d.state);set('ibge_city_code',d.ibge_city_code);}}finally{setLookup('')}}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const payload:Row=Object.fromEntries(fd.entries());if(editing?.id)payload.id=editing.id;payload.cnpj=digits(text(payload.cnpj));payload.postal_code=digits(text(payload.postal_code));payload.state=text(payload.state).toUpperCase();startTransition(async()=>{const r=await branchLicenseSave(payload);if(!r.ok){setMessage(messages[text(r.error)]||`Não foi possível salvar a filial: ${text(r.error)}`);return}setOpen(false);setEditing(null);setMessage('Filial salva e vinculada à licença.');const latest=await branchLicenseList();if(latest.ok)setRows(latest.data);router.refresh();});}
 return <div className="licensed-branches-shell">
  <section className="erp-module-card branch-license-hero"><div><small>LICENÇA MULTILOJA</small><h2>Matriz + Lojas / Filiais</h2><p>A Matriz está incluída na licença-base. Cada unidade adicional consome uma vaga de filial liberada pelo ThorControl.</p></div><button className="erp-primary" onClick={beginNew} disabled={!enabled||remaining<=0}>+ Nova filial</button></section>
  <section className="branch-license-kpis"><article><span>Total licenciado</span><strong>{branchLimit}</strong><small>loja(s), incluindo Matriz</small></article><article><span>Em uso</span><strong>{used}</strong><small>1 Matriz + {extraUsed} filial(is)</small></article><article><span>Filiais adicionais</span><strong>{extraUsed} / {extraLicensed}</strong><small>usadas / contratadas</small></article><article><span>Disponíveis</span><strong>{remaining}</strong><small>vaga(s) para nova filial</small></article></section>
  {!enabled&&<div className="branch-license-warning"><strong>Módulo Lojas / Filiais não contratado.</strong><span>Habilite o módulo e aumente o limite no ThorControl para cadastrar unidades além da Matriz.</span></div>}
  {enabled&&remaining<=0&&<div className="branch-license-warning"><strong>Limite da licença atingido.</strong><span>Para abrir outra loja, amplie “Total de lojas/unidades” no ThorControl.</span></div>}
  {message&&<div className="erp-message">{message}</div>}
  <section className="erp-module-card"><div className="erp-price-title"><div><h2>Unidades cadastradas</h2><p>Cada filial mantém CNPJ, inscrições, CRT, endereço e configuração operacional próprios. PDVs, estoque, fiscal e relatórios continuam vinculados ao <code>branch_id</code>.</p></div></div><div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Unidade</th><th>CNPJ / IE</th><th>Cidade / UF</th><th>Tipo</th><th>Ações</th></tr></thead><tbody>{sorted.map(b=><tr key={text(b.id)}><td><strong>{b.is_headquarters?'Matriz':text(b.name)}</strong>{b.is_headquarters&&text(b.name)!=='Matriz'?<small>{text(b.name)}</small>:null}</td><td>{text(b.cnpj)||'—'}<small>IE {text(b.state_registration)||'—'} · CRT {text(b.crt)||'—'}</small></td><td>{[text(b.city),text(b.state)].filter(Boolean).join(' / ')||'—'}</td><td><span className="erp-pill">{b.is_headquarters?'Matriz':'Filial'}</span></td><td><div className="branch-row-actions">{b.is_headquarters?<Link className="erp-row-action" href="/dashboard/administrativo/empresas">Editar Matriz</Link>:<button className="erp-row-action" onClick={()=>beginEdit(b)}>Editar</button>}<Link className="erp-row-action" href={`/dashboard/configuracoes?branch=${text(b.id)}`}>Configurar</Link></div></td></tr>)}</tbody></table></div></section>
  {open&&<div className="branch-license-modal-bg"><form className="erp-module-card branch-license-modal" onSubmit={submit} key={text(editing?.id)||'new'}><header><div><small>{editing?'EDITAR FILIAL':'NOVA FILIAL'}</small><h2>{editing?text(editing.name):'Cadastrar nova unidade'}</h2><p>{headquarters?`Empresa principal: ${text(headquarters.name)||'Matriz'}`:'A nova unidade será vinculada à empresa da sessão.'}</p></div><button type="button" onClick={()=>{setOpen(false);setEditing(null)}}>×</button></header><div className="branch-license-form"><label>Nome da filial *<input name="name" required defaultValue={text(current.name)}/></label><label>CNPJ da filial<div className="branch-inline-input"><input name="cnpj" inputMode="numeric" defaultValue={text(current.cnpj)}/><button type="button" onClick={e=>void lookupCnpj(e.currentTarget.form!)} disabled={lookup==='cnpj'}>{lookup==='cnpj'?'Consultando...':'Consultar'}</button></div></label><label>Inscrição Estadual<input name="state_registration" defaultValue={text(current.state_registration)}/></label><label>Inscrição Municipal<input name="municipal_registration" defaultValue={text(current.municipal_registration)}/></label><label>CRT<select name="crt" defaultValue={text(current.crt)}><option value="">Selecione...</option><option value="1">1 - Simples Nacional</option><option value="2">2 - Simples excesso sublimite</option><option value="3">3 - Regime Normal</option><option value="4">4 - MEI</option></select></label><label>E-mail<input name="email" type="email" defaultValue={text(current.email)}/></label><label>Telefone<input name="phone" defaultValue={text(current.phone)}/></label><label>Responsável<input name="responsible" defaultValue={text(current.responsible)}/></label><label>Contato<input name="contact" defaultValue={text(current.contact)}/></label><label>CEP<input name="postal_code" inputMode="numeric" defaultValue={text(current.postal_code)} onBlur={e=>void lookupCep(e.currentTarget.form!)}/></label><label>Rua / Logradouro<input name="street" defaultValue={text(current.street)}/></label><label>Número<input name="number" defaultValue={text(current.number)}/></label><label>Complemento<input name="complement" defaultValue={text(current.complement)}/></label><label>Bairro<input name="district" defaultValue={text(current.district)}/></label><label>Cidade<input name="city" defaultValue={text(current.city)}/></label><label>UF<input name="state" maxLength={2} defaultValue={text(current.state)}/></label><label>Código IBGE<input name="ibge_city_code" defaultValue={text(current.ibge_city_code)}/></label></div><footer><button type="button" onClick={()=>{setOpen(false);setEditing(null)}}>Cancelar</button><button className="erp-primary" disabled={pending}>{pending?'Salvando...':'Salvar filial'}</button></footer></form></div>}
 </div>;
}
