'use client';

import { useEffect, useState } from 'react';
import { erpCashClose, erpCashList, erpCashOpen, erpUserCashClose, erpUserCashGet } from './actions';

type Row=Record<string,unknown>;
const money=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR'):'—';
const methodName=(m:unknown)=>({cash:'Dinheiro',pix:'PIX',credit_card:'Crédito',debit_card:'Débito',voucher:'Voucher',store_credit:'Crédito da loja',store_credit_voucher:'Vale Crédito',other:'Outros'}[String(m)]??String(m));

export function CashWorkspace({posRegisters}:{posRegisters:Row[]}){
 const [sessions,setSessions]=useState<Row[]>([]);const [myCash,setMyCash]=useState<Row|null>(null);const [myOperator,setMyOperator]=useState('');const [myCounted,setMyCounted]=useState('');const [myNotes,setMyNotes]=useState('');const [pos,setPos]=useState(String(posRegisters[0]?.id??''));const [opening,setOpening]=useState(0);const [counted,setCounted]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);
 async function load(){const [all,mine]=await Promise.all([erpCashList(),erpUserCashGet()]);if(all.ok)setSessions(all.data);else setMessage(String(all.error??'Falha ao carregar caixa'));if(mine.ok){setMyCash(mine.has_open_cash&&mine.cash&&typeof mine.cash==='object'?mine.cash as Row:null);setMyOperator(String((mine.cash as Row|undefined)?.operator??mine.operator??''));}else if(String(mine.error)==='pdv_operator_not_linked')setMessage('Este usuário do ThorGestão ainda não está vinculado a um operador do ThorPDV com o mesmo e-mail.');}
 useEffect(()=>{void load()},[]);
 async function open(){if(!pos)return;setLoading(true);const r=await erpCashOpen(pos,opening);setLoading(false);if(r.ok){setMessage('Caixa aberto para o seu usuário. O ThorGestão e o ThorPDV passam a enxergar a mesma sessão.');setOpening(0);await load()}else setMessage(String(r.error==='cash_user_already_open'?'Você já possui um caixa aberto. Feche a sessão atual antes de abrir outra.':r.error??'Falha ao abrir caixa'))}
 async function close(id:string){const raw=counted[id];if(raw===undefined||raw===''){setMessage('Informe o valor contado para fechar o caixa.');return}setLoading(true);const r=await erpCashClose(id,Number(raw),'Fechamento gerencial pelo ThorGestão');setLoading(false);if(r.ok){setMessage(`Caixa fechado. Esperado: ${money(r.expected)} · Contado: ${money(r.closing)} · Diferença: ${money(r.difference)}.`);await load()}else setMessage(String(r.error??'Falha ao fechar caixa'))}
 async function closeMine(){if(!myCash)return;if(myCounted===''){setMessage('Informe o valor contado no seu caixa antes de fechar.');return}setLoading(true);const r=await erpUserCashClose(Number(myCounted),myNotes);setLoading(false);if(r.ok){setMessage(`Seu caixa foi fechado no ThorGestão. Esperado: ${money(r.expected)} · Contado: ${money(r.closing)} · Diferença: ${money(r.difference)}.`);setMyCounted('');setMyNotes('');await load()}else setMessage(String(r.error??'Falha ao fechar seu caixa'))}
 const openCount=sessions.filter(s=>s.status==='open').length;const sales=sessions.reduce((a,s)=>a+Number(s.sales_total??0),0);const received=sessions.reduce((a,s)=>a+Number(s.received_total??0),0);const payments=Array.isArray(myCash?.payments)?myCash.payments as Row[]:[];
 return <div className="erp-cash-workspace">
  <section className={`erp-my-cash ${myCash?'open':'closed'}`}><div className="erp-my-cash-head"><div><span>MEU CAIXA</span><h2>{myCash?`${myOperator||'Operador'} · Caixa aberto`:`${myOperator||'Usuário'} · Nenhum caixa aberto`}</h2><p>{myCash?`Sessão compartilhada com o ThorPDV · ${String(myCash.pos??'PDV')} · ${String(myCash.branch??'')}`:'Quando este operador abrir o caixa no ThorPDV, a mesma sessão aparecerá aqui automaticamente.'}</p></div><strong>{myCash?'ABERTO':'FECHADO'}</strong></div>{myCash&&<><div className="erp-my-cash-kpis"><article><span>Abertura</span><b>{money(myCash.opening_amount)}</b><small>{dt(myCash.opened_at)}</small></article><article><span>Vendas</span><b>{money(myCash.sales_total)}</b><small>sessão do operador</small></article><article><span>Recebido</span><b>{money(myCash.received_total)}</b><small>todos os meios</small></article><article><span>Esperado em dinheiro</span><b>{money(myCash.expected_cash)}</b><small>fundo + dinheiro ± movimentos</small></article></div>{payments.length>0&&<div className="erp-my-cash-payments">{payments.map((p,i)=><span key={`${String(p.method)}-${i}`}><b>{methodName(p.method)}</b>{money(p.amount)}</span>)}</div>}<div className="erp-my-cash-close"><label>Valor contado<input type="number" min="0" step="0.01" value={myCounted} onChange={e=>setMyCounted(e.target.value)} placeholder="0,00"/></label><label>Observação<input value={myNotes} onChange={e=>setMyNotes(e.target.value)} placeholder="Opcional"/></label><button disabled={loading} onClick={closeMine}>{loading?'Fechando...':'Fechar meu caixa'}</button></div>{myCash.is_current_business_day===false&&<p className="erp-cash-warning">Atenção: este caixa pertence a uma data comercial anterior. O fechamento encerrará essa sessão antiga.</p>}</>}
  </section>
  <section className="erp-module-kpis"><article><span>PDVs cadastrados</span><strong>{posRegisters.filter(p=>p.active!==false).length}</strong><small>terminais ativos</small></article><article><span>Caixas abertos</span><strong>{openCount}</strong><small>sessões em operação</small></article><article><span>Vendas nas sessões</span><strong>{money(sales)}</strong><small>faturamento vinculado</small></article><article><span>Recebido</span><strong>{money(received)}</strong><small>pagamentos das sessões</small></article></section>
  <section className="erp-module-card"><div className="erp-cash-open"><div><h2>Abertura de caixa</h2><p>Cada operador possui sua própria sessão. Se o caixa já foi aberto no ThorPDV, não abra outro: ele aparece em Meu Caixa.</p></div><label>PDV<select value={pos} onChange={e=>setPos(e.target.value)}><option value="">Selecione...</option>{posRegisters.filter(p=>p.active!==false).map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)} · {String(p.branch??'')}</option>)}</select></label><label>Fundo inicial<input type="number" min="0" step="0.01" value={opening} onChange={e=>setOpening(Number(e.target.value))}/></label><button className="erp-primary" disabled={!pos||loading||Boolean(myCash)} onClick={open}>Abrir meu caixa</button></div>{message&&<p className="erp-message">{message}</p>}<div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Operador</th><th>PDV</th><th>Filial</th><th>Abertura</th><th>Fundo</th><th>Vendas</th><th>Recebido</th><th>Dinheiro</th><th>Esperado</th><th>Status</th><th>Fechamento gerencial</th></tr></thead><tbody>{sessions.length===0?<tr><td className="erp-empty" colSpan={11}>Nenhuma sessão de caixa registrada.</td></tr>:sessions.map((s,i)=><tr key={String(s.id??i)}><td><strong>{String(s.operator??'—')}</strong></td><td>{String(s.pos??'')}</td><td>{String(s.branch??'')}</td><td>{dt(s.opened_at)}</td><td>{money(s.opening_amount)}</td><td>{money(s.sales_total)}</td><td>{money(s.received_total)}</td><td>{money(s.cash_received)}</td><td><strong>{money(s.expected_cash)}</strong></td><td><span className={`erp-pill ${s.status==='open'?'':'danger'}`}>{String(s.status)}</span></td><td>{s.status==='open'?<div className="erp-cash-close"><input type="number" step="0.01" placeholder="Valor contado" value={counted[String(s.id)]??''} onChange={e=>setCounted(c=>({...c,[String(s.id)]:e.target.value}))}/><button className="erp-row-action" disabled={loading} onClick={()=>close(String(s.id))}>Fechar</button></div>:<span>{money(s.closing_amount)}<small>{s.closed_at?` · ${dt(s.closed_at)}`:''}</small></span>}</td></tr>)}</tbody></table></div></section>
 </div>;
}
