'use client';

import { FormEvent, useMemo, useState, useTransition } from 'react';
import { bankBillingsList, bankIntegrationsData, saveBankIntegration, testItauBolecode } from './bank-integrations-actions';

type Row=Record<string,unknown>;
const text=(v:unknown)=>v==null?'':String(v);
const money=(v:unknown)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:unknown)=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const err:Record<string,string>={invalid_session:'Sessão inválida.',bank_account_not_found:'Conta bancária não encontrada.',itau_agency_must_have_4_digits:'A agência Itaú deve ter 4 dígitos.',itau_account_must_have_7_digits:'A conta Itaú deve ter 7 dígitos.',itau_account_digit_required:'Informe o DAC/dígito da conta.',itau_credentials_not_configured:'As credenciais Itaú ainda não foram configuradas no ThorControl.',itau_provider_not_ready:'O ambiente Itaú não está habilitado no ThorControl.',payer_document_invalid:'CPF/CNPJ do pagador inválido.',payer_name_required:'Informe o nome do pagador.',payer_postal_code_invalid:'CEP do pagador deve ter 8 dígitos.',amount_required:'Informe um valor maior que zero.',due_date_required:'Informe o vencimento.',itau_token_failed:'O Itaú recusou a autenticação.',itau_token_missing_in_response:'O token retornado pelo Itaú não foi reconhecido.',itau_bolecode_exception:'Falha interna durante a chamada do BoleCode.'};

export function ItauBolecodeWorkspace({accountsInitial,integrationsInitial,billingsInitial}:{accountsInitial:Record<string,unknown>;integrationsInitial:Record<string,unknown>;billingsInitial:Record<string,unknown>}){
 const accounts=useMemo(()=>((accountsInitial.accounts as Row[])??[]).filter(a=>a.account_type==='bank'&&!a.is_system),[accountsInitial]);
 const [integrations,setIntegrations]=useState<Row[]>(Array.isArray(integrationsInitial.integrations)?integrationsInitial.integrations as Row[]:[]);
 const [billings,setBillings]=useState<Row[]>(Array.isArray(billingsInitial.billings)?billingsInitial.billings as Row[]:[]);
 const [selectedId,setSelectedId]=useState(text(accounts[0]?.id));const [message,setMessage]=useState('');const [result,setResult]=useState<Row|null>(null);const [pending,startTransition]=useTransition();
 const selected=accounts.find(a=>text(a.id)===selectedId);const integration=integrations.find(i=>text(i.bank_account_id)===selectedId&&text(i.provider)==='itau'&&text(i.product)==='bolecode_pix');
 function run(fn:()=>Promise<void>){startTransition(()=>{void fn()})}
 async function refresh(){const [i,b]=await Promise.all([bankIntegrationsData(),bankBillingsList(100)]);if(i.ok)setIntegrations(Array.isArray(i.integrations)?i.integrations as Row[]:[]);if(b.ok)setBillings(Array.isArray(b.billings)?b.billings as Row[]:[])}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedId)return;const fd=new FormData(e.currentTarget);const r=await saveBankIntegration(selectedId,{...Object.fromEntries(fd.entries()),active:fd.get('active')==='on',allow_divergent:fd.get('allow_divergent')==='on'});if(!r.ok){setMessage(err[text(r.error)]||text(r.error||'Falha ao salvar integração.'));return}setMessage(`Integração Itaú salva. ID do beneficiário: ${text(r.beneficiary_id)}.`);await refresh()}
 async function test(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!integration)return;const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const effective=submitter?.value==='effective';if(effective&&text(integration.environment)==='production'&&!window.confirm('Esta operação emitirá uma cobrança REAL no Itaú. Deseja continuar?'))return;const fd=new FormData(e.currentTarget);const r=await testItauBolecode(text(integration.id),Object.fromEntries(fd.entries()),effective);setResult(r as Row);if(r.ok)setMessage(effective?'BoleCode enviado ao Itaú com sucesso.':'Simulação enviada ao Itaú com sucesso.');else setMessage(err[text(r.error)]||text(r.error||r.detail||'Falha na API Itaú.'));await refresh()}
 const settings=(integration?.settings&&typeof integration.settings==='object'?integration.settings:{}) as Row;
 return <div className="itau-bank-workspace">
  <section className="itau-hero"><div><small>INTEGRAÇÃO BANCÁRIA</small><h2>Itaú BoleCode Pix</h2><p>Configure a conta beneficiária e gere boleto registrado com QR Code Pix diretamente pelo Thor.</p></div><div className="itau-state"><span className={integration?.active?'on':'off'}/><div><strong>{integration?.active?'Integração ativa':'Aguardando configuração'}</strong><small>{integration?`${text(integration.environment)==='production'?'Produção':'Sandbox'} · ${integration.provider_ready?'Credencial pronta':'Credencial pendente no ThorControl'}`:'Selecione e configure uma conta Itaú'}</small></div></div></section>
  {message&&<div className="itau-message">{message}</div>}
  <section className="itau-account-picker"><label>Conta bancária<select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setResult(null)}}><option value="">Selecione...</option>{accounts.map(a=><option key={text(a.id)} value={text(a.id)}>{text(a.name)} {a.bank_code?`· Banco ${text(a.bank_code)}`:''}</option>)}</select></label><div><span>Conta escolhida</span><strong>{text(selected?.name)||'Nenhuma'}</strong><small>{selected?`Ag. ${text(selected.agency)||'—'} · Conta ${text(selected.account_number)||'—'}`:'Cadastre uma conta bancária primeiro.'}</small></div></section>
  {selected?<div className="itau-layout">
   <form key={`${selectedId}-${text(integration?.updated_at)}`} className="itau-card itau-config" onSubmit={e=>run(()=>save(e))}><div className="itau-card-head"><div><small>CONFIGURAÇÃO DA CONTA</small><h3>Beneficiário Itaú</h3></div><span className="itau-pill">Banco 341</span></div><div className="itau-form-grid">
    <label>Ambiente<select name="environment" defaultValue={text(integration?.environment)||'sandbox'}><option value="sandbox">Sandbox / Homologação</option><option value="production">Produção</option></select></label>
    <label>Agência<input name="agency" inputMode="numeric" maxLength={4} defaultValue={text(settings.agency)||text(selected.agency)} placeholder="1500"/></label>
    <label>Conta corrente<input name="account_number" inputMode="numeric" maxLength={7} defaultValue={text(settings.account_number)||text(selected.account_number)} placeholder="0012345"/></label>
    <label>DAC / Dígito<input name="account_digit" inputMode="numeric" maxLength={1} defaultValue={text(settings.account_digit)} placeholder="0"/></label>
    <label>Carteira<select name="wallet" defaultValue={text(settings.wallet)||'109'}><option value="109">109 — Cobrança registrada</option></select></label>
    <label>Espécie<select name="species" defaultValue={text(settings.species)||'01'}><option value="01">01 — Duplicata Mercantil</option><option value="05">05 — Recibo</option><option value="06">06 — Contrato</option><option value="08">08 — Duplicata de Serviços</option><option value="17">17 — Fatura de Serviço</option><option value="99">99 — Diversos</option></select></label>
    <label>Juros padrão<select name="default_interest_type" defaultValue={text(settings.default_interest_type)||'05'}><option value="05">Sem juros</option><option value="90">Percentual mensal</option><option value="91">Percentual diário</option><option value="92">Percentual anual</option><option value="93">Valor diário</option></select></label>
    <label>Multa padrão<select name="default_fine_type" defaultValue={text(settings.default_fine_type)||'03'}><option value="03">Sem multa</option><option value="01">Valor fixo</option><option value="02">Percentual</option></select></label>
    <label className="itau-check wide"><input type="checkbox" name="allow_divergent" defaultChecked={Boolean(settings.allow_divergent)}/><span>Aceitar pagamento com valor divergente</span></label><label className="itau-check wide"><input type="checkbox" name="active" defaultChecked={integration?Boolean(integration.active):true}/><span>Ativar BoleCode Pix nesta conta</span></label>
   </div><div className="itau-beneficiary"><span>ID do beneficiário</span><strong>{text(settings.beneficiary_id)||'Será calculado como agência + conta + DAC'}</strong></div><button className="itau-primary" disabled={pending}>Salvar integração Itaú</button></form>
   <form className="itau-card itau-test" onSubmit={e=>run(()=>test(e))}><div className="itau-card-head"><div><small>HOMOLOGAÇÃO</small><h3>Simular BoleCode</h3></div><span className={`itau-pill ${integration?.provider_ready?'ready':''}`}>{integration?.provider_ready?'Credencial pronta':'ThorControl pendente'}</span></div><p className="itau-help">Use dados de teste. A opção Simular valida o payload sem efetivar a cobrança; Emitir teste efetiva somente quando a integração estiver no Sandbox.</p><div className="itau-form-grid">
    <label className="wide">Nome / Razão social<input required name="name" placeholder="Cliente de Teste"/></label><label>CPF/CNPJ<input required name="document" inputMode="numeric" placeholder="Somente números"/></label><label>Valor<input required name="amount" type="number" min="0.01" step="0.01" placeholder="100.00"/></label><label>Vencimento<input required name="due_date" type="date"/></label><label>CEP<input required name="postal_code" inputMode="numeric" maxLength={8}/></label><label className="wide">Logradouro<input required name="street" placeholder="Rua Exemplo"/></label><label>Número<input name="number" placeholder="100"/></label><label>Complemento<input name="complement"/></label><label>Bairro<input required name="district"/></label><label>Cidade<input required name="city"/></label><label>UF<input required name="state" maxLength={2} placeholder="PI"/></label>
   </div><div className="itau-test-actions"><button value="simulate" disabled={pending||!integration||!integration.provider_ready}>Simular no Itaú</button><button className="itau-primary" value="effective" disabled={pending||!integration||!integration.provider_ready||text(integration.environment)==='production'}>{text(integration?.environment)==='production'?'Produção bloqueada nesta fase':'Emitir teste Sandbox'}</button></div></form>
  </div>:null}
  {result?<section className="itau-card itau-result"><div className="itau-card-head"><div><small>RETORNO DA API</small><h3>{result.ok?'Operação aceita pelo Itaú':'Falha na operação'}</h3></div><span className={`itau-http ${result.ok?'ok':'error'}`}>HTTP {text(result.http_status)||'—'}</span></div><div className="itau-result-grid"><div><span>Status</span><strong>{text(result.status)||text(result.error)||'—'}</strong></div><div><span>Nosso Número</span><strong>{text(result.our_number)||'—'}</strong></div><div><span>Correlation ID</span><strong>{text(result.correlation_id)||'—'}</strong></div><div><span>TXID Pix</span><strong>{text(result.pix_txid)||'—'}</strong></div></div>{result.digitable_line?<div className="itau-code"><span>Linha digitável</span><code>{text(result.digitable_line)}</code></div>:null}{result.pix_emv?<div className="itau-code"><span>Pix Copia e Cola</span><code>{text(result.pix_emv)}</code></div>:null}{result.pix_qr_base64?<img className="itau-qr" src={`data:image/png;base64,${text(result.pix_qr_base64)}`} alt="QR Code Pix retornado pelo Itaú"/>:null}{!result.ok?<pre>{JSON.stringify(result.response??result,null,2)}</pre>:null}</section>:null}
  <section className="itau-card itau-history"><div className="itau-card-head"><div><small>COBRANÇAS BANCÁRIAS</small><h3>Últimos testes e emissões</h3></div><span>{billings.length} registro(s)</span></div><div className="itau-table-wrap"><table><thead><tr><th>Data</th><th>Conta</th><th>Ambiente</th><th>Nosso Número</th><th>Vencimento</th><th>Valor</th><th>Status</th><th>HTTP</th></tr></thead><tbody>{billings.length===0?<tr><td colSpan={8}>Nenhuma cobrança testada ainda.</td></tr>:billings.map(b=><tr key={text(b.id)}><td>{new Date(text(b.created_at)).toLocaleString('pt-BR')}</td><td>{text(b.account)}</td><td>{text(b.environment)==='production'?'Produção':'Sandbox'}</td><td>{text(b.our_number)||'—'}</td><td>{date(b.due_date)}</td><td>{money(b.amount)}</td><td><span className={`itau-billing-status ${text(b.status)}`}>{text(b.status)}</span></td><td>{text(b.http_status)||'—'}</td></tr>)}</tbody></table></div></section>
 </div>;
}
