'use client';

import { FormEvent, useMemo, useState } from 'react';
import { erpCreateSale, erpLoad, erpLoadPage, erpSave } from './actions';
import { AdvancedShell } from './advanced-shell';

type Row = Record<string, unknown>;
type LookupMap = Record<string, Row[]>;
type Field = { key: string; label: string; type?: 'text'|'number'|'date'|'datetime-local'|'textarea'|'checkbox'|'select'; required?: boolean; lookup?: string; optionLabel?: string; options?: [string,string][]; placeholder?: string };
type Column = { key: string; label: string; format?: 'currency'|'date'|'datetime'|'boolean'|'status' };
type ModuleConfig = { title: string; subtitle: string; addLabel?: string; fields: Field[]; columns: Column[]; readOnly?: boolean; kind?: 'report'|'regular' };

const PAGE_SIZE=10;
const yesNo: [string,string][] = [['true','Ativo'],['false','Inativo']];
const statusFinance: [string,string][] = [['open','Em aberto'],['paid','Pago'],['partial','Parcial'],['overdue','Vencido'],['cancelled','Cancelado']];

const configs: Record<string, ModuleConfig> = {
  clientes: { title:'Cadastro de Clientes', subtitle:'Clientes integrados a vendas, financeiro e documentos fiscais.', addLabel:'Novo Cliente', fields:[
    {key:'type',label:'Tipo',type:'select',options:[['PF','Pessoa Física'],['PJ','Pessoa Jurídica']]},{key:'name',label:'Nome / Razão Social',required:true},{key:'document',label:'CPF / CNPJ'},{key:'email',label:'E-mail'},{key:'phone',label:'Telefone'},{key:'city',label:'Cidade'},{key:'state',label:'UF',placeholder:'PI'},{key:'active',label:'Status',type:'select',options:yesNo}],
    columns:[{key:'name',label:'Nome / Razão Social'},{key:'document',label:'CPF / CNPJ'},{key:'type',label:'Tipo'},{key:'city',label:'Cidade'},{key:'phone',label:'Telefone'},{key:'active',label:'Status',format:'boolean'}] },
  fornecedores: { title:'Cadastro de Fornecedores', subtitle:'Fornecedores vinculados a contas a pagar e movimentações de estoque.', addLabel:'Novo Fornecedor', fields:[{key:'name',label:'Razão Social',required:true},{key:'document',label:'CNPJ'},{key:'state_registration',label:'Inscrição Estadual'},{key:'email',label:'E-mail'},{key:'phone',label:'Telefone'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Razão Social'},{key:'document',label:'CNPJ'},{key:'state_registration',label:'IE'},{key:'email',label:'E-mail'},{key:'phone',label:'Telefone'},{key:'active',label:'Status',format:'boolean'}] },
  'perfis-pdv': { title:'Perfis de Usuário PDV', subtitle:'Permissões para operadores do ponto de venda.', addLabel:'Novo Perfil PDV', fields:[{key:'name',label:'Nome do Perfil',required:true},{key:'permissions_text',label:'Permissões',type:'textarea',placeholder:'vender,cancelar,desconto,abrir_caixa'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Perfil'},{key:'permissions',label:'Permissões'},{key:'active',label:'Status',format:'boolean'}] },
  'perfis-adm': { title:'Perfis de Usuário ADM', subtitle:'Perfis e permissões do ambiente administrativo.', addLabel:'Novo Perfil ADM', fields:[{key:'name',label:'Nome do Perfil',required:true},{key:'permissions_text',label:'Permissões',type:'textarea',placeholder:'produtos,estoque,financeiro,relatorios'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Perfil'},{key:'permissions',label:'Permissões'},{key:'active',label:'Status',format:'boolean'}] },
  'usuarios-pdv': { title:'Usuários PDV', subtitle:'Operadores vinculados a perfil de acesso e filial.', addLabel:'Novo Usuário PDV', fields:[{key:'name',label:'Nome',required:true},{key:'email',label:'E-mail'},{key:'profile_id',label:'Perfil',type:'select',lookup:'profiles_pdv',optionLabel:'name'},{key:'branch_id',label:'Filial',type:'select',lookup:'branches',optionLabel:'name'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Nome'},{key:'email',label:'E-mail'},{key:'profile',label:'Perfil'},{key:'branch',label:'Filial'},{key:'last_access',label:'Último acesso',format:'datetime'},{key:'active',label:'Status',format:'boolean'}] },
  'usuarios-adm': { title:'Usuários Administrativos', subtitle:'Usuários vinculados a perfil e filial.', addLabel:'Novo Usuário ADM', fields:[{key:'name',label:'Nome',required:true},{key:'email',label:'E-mail'},{key:'profile_id',label:'Perfil',type:'select',lookup:'profiles_adm',optionLabel:'name'},{key:'branch_id',label:'Filial',type:'select',lookup:'branches',optionLabel:'name'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Nome'},{key:'email',label:'E-mail'},{key:'profile',label:'Perfil'},{key:'branch',label:'Filial'},{key:'last_access',label:'Último acesso',format:'datetime'},{key:'active',label:'Status',format:'boolean'}] },
  produtos: { title:'Cadastro de Produtos', subtitle:'Produtos integrados a preço, estoque, vendas e fiscal.', addLabel:'Novo Produto', fields:[{key:'sku',label:'Código / SKU'},{key:'barcode',label:'Código de Barras'},{key:'name',label:'Descrição do Produto',required:true},{key:'group_id',label:'Grupo',type:'select',lookup:'groups',optionLabel:'name'},{key:'class_id',label:'Classe',type:'select',lookup:'classes',optionLabel:'name'},{key:'unit',label:'Unidade',placeholder:'UN'},{key:'ncm',label:'NCM'},{key:'cest',label:'CEST'},{key:'cfop_default',label:'CFOP Padrão'},{key:'cost_price',label:'Preço de Custo',type:'number'},{key:'sale_price',label:'Preço de Venda',type:'number',required:true},{key:'minimum_stock',label:'Estoque Mínimo',type:'number'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'sku',label:'Código'},{key:'barcode',label:'EAN'},{key:'name',label:'Produto'},{key:'group_name',label:'Grupo'},{key:'class_name',label:'Classe'},{key:'sale_price',label:'Preço Venda',format:'currency'},{key:'stock',label:'Estoque'},{key:'active',label:'Status',format:'boolean'}] },
  grupos: { title:'Grupos de Produtos', subtitle:'Organização dos produtos por grupos comerciais.', addLabel:'Novo Grupo', fields:[{key:'name',label:'Nome do Grupo',required:true},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Grupo'},{key:'active',label:'Status',format:'boolean'},{key:'created_at',label:'Criado em',format:'date'}] },
  classes: { title:'Classes de Produtos', subtitle:'Classificação complementar integrada aos grupos.', addLabel:'Nova Classe', fields:[{key:'name',label:'Nome da Classe',required:true},{key:'group_id',label:'Grupo',type:'select',lookup:'groups',optionLabel:'name'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Classe'},{key:'group_name',label:'Grupo'},{key:'active',label:'Status',format:'boolean'}] },
  modificadores: { title:'Modificadores', subtitle:'Adicionais e modificadores de item para o PDV.', addLabel:'Novo Modificador', fields:[{key:'name',label:'Nome',required:true},{key:'price_delta',label:'Acréscimo de Preço',type:'number'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Modificador'},{key:'price_delta',label:'Acréscimo',format:'currency'},{key:'active',label:'Status',format:'boolean'}] },
  'tabelas-precos': { title:'Gestão de Tabelas de Preços', subtitle:'Tabelas, vigências e preços comerciais.', addLabel:'Nova Tabela', fields:[{key:'name',label:'Nome da Tabela',required:true},{key:'table_type',label:'Tipo',type:'select',options:[['standard','Padrão'],['wholesale','Atacado'],['promotion','Promoção'],['adjustment','Ajuste']]},{key:'valid_from',label:'Início',type:'date'},{key:'valid_to',label:'Fim',type:'date'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Tabela'},{key:'table_type',label:'Tipo'},{key:'valid_from',label:'Início',format:'date'},{key:'valid_to',label:'Fim',format:'date'},{key:'item_count',label:'Itens'},{key:'active',label:'Status',format:'boolean'}] },
  'tabelas-precos/copiar': { title:'Copiar Tabela de Preços', subtitle:'Consulte as tabelas existentes; a cópia usa a mesma base de itens para uma nova vigência.', fields:[], columns:[{key:'name',label:'Tabela'},{key:'table_type',label:'Tipo'},{key:'item_count',label:'Itens'},{key:'active',label:'Status',format:'boolean'}], readOnly:true },
  'tabelas-precos/ajustes': { title:'Ajustes Programados', subtitle:'Reajustes percentuais ou fixos vinculados às tabelas.', addLabel:'Novo Ajuste', fields:[{key:'name',label:'Descrição',required:true},{key:'price_table_id',label:'Tabela',type:'select',lookup:'price_tables',optionLabel:'name'},{key:'adjustment_type',label:'Tipo',type:'select',options:[['percent','Percentual'],['fixed','Valor fixo']]},{key:'adjustment_value',label:'Valor do Ajuste',type:'number'},{key:'execute_at',label:'Executar em',type:'datetime-local'},{key:'status',label:'Status',type:'select',options:[['draft','Rascunho'],['scheduled','Agendado'],['executed','Executado'],['cancelled','Cancelado']]}], columns:[{key:'name',label:'Ajuste'},{key:'price_table',label:'Tabela'},{key:'adjustment_type',label:'Tipo'},{key:'adjustment_value',label:'Valor'},{key:'execute_at',label:'Execução',format:'datetime'},{key:'status',label:'Status',format:'status'}] },
  promocoes: { title:'Promoções', subtitle:'Regras promocionais com período de validade.', addLabel:'Nova Promoção', fields:[{key:'name',label:'Nome',required:true},{key:'valid_from',label:'Início',type:'datetime-local'},{key:'valid_to',label:'Fim',type:'datetime-local'},{key:'rules_text',label:'Regra / Observação',type:'textarea'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'Promoção'},{key:'valid_from',label:'Início',format:'datetime'},{key:'valid_to',label:'Fim',format:'datetime'},{key:'active',label:'Status',format:'boolean'}] },
  estoque: { title:'Gestão de Estoque', subtitle:'Entradas, saídas, ajustes e saldos por produto e filial.', addLabel:'Nova Movimentação', fields:[{key:'product_id',label:'Produto',type:'select',lookup:'products',optionLabel:'name',required:true},{key:'movement_type',label:'Tipo',type:'select',options:[['in','Entrada'],['out','Saída'],['adjustment','Ajuste'],['transfer','Transferência'],['loss','Perda']]},{key:'quantity',label:'Quantidade',type:'number',required:true},{key:'unit_cost',label:'Custo Unitário',type:'number'},{key:'notes',label:'Observação',type:'textarea'}], columns:[{key:'created_at',label:'Data',format:'datetime'},{key:'product',label:'Produto'},{key:'sku',label:'Código'},{key:'movement_type',label:'Tipo',format:'status'},{key:'quantity',label:'Quantidade'},{key:'branch',label:'Filial'},{key:'notes',label:'Observação'}] },
  'estoque/inventario': { title:'Inventários', subtitle:'Contagens físicas e diferenças de estoque.', addLabel:'Novo Inventário', fields:[{key:'status',label:'Status',type:'select',options:[['open','Aberto'],['counting','Em contagem'],['closed','Fechado'],['cancelled','Cancelado']]},{key:'notes',label:'Observação',type:'textarea'}], columns:[{key:'code',label:'Código'},{key:'branch',label:'Filial'},{key:'status',label:'Status',format:'status'},{key:'item_count',label:'Itens'},{key:'opened_at',label:'Abertura',format:'datetime'},{key:'closed_at',label:'Fechamento',format:'datetime'}] },
  'estoque/ajustes': { title:'Ajustes de Estoque', subtitle:'Movimentações de correção de saldo.', addLabel:'Novo Ajuste', fields:[{key:'product_id',label:'Produto',type:'select',lookup:'products',optionLabel:'name',required:true},{key:'movement_type',label:'Tipo',type:'select',options:[['adjustment','Ajuste']]},{key:'quantity',label:'Quantidade (+/-)',type:'number',required:true},{key:'notes',label:'Motivo',type:'textarea'}], columns:[{key:'created_at',label:'Data',format:'datetime'},{key:'product',label:'Produto'},{key:'quantity',label:'Quantidade'},{key:'branch',label:'Filial'},{key:'notes',label:'Motivo'}] },
  'estoque/transferencias': { title:'Transferências de Estoque', subtitle:'Histórico de transferências entre filiais.', addLabel:'Nova Transferência', fields:[{key:'product_id',label:'Produto',type:'select',lookup:'products',optionLabel:'name',required:true},{key:'movement_type',label:'Tipo',type:'select',options:[['transfer','Transferência']]},{key:'quantity',label:'Quantidade',type:'number',required:true},{key:'notes',label:'Destino / Observação',type:'textarea'}], columns:[{key:'created_at',label:'Data',format:'datetime'},{key:'product',label:'Produto'},{key:'quantity',label:'Quantidade'},{key:'branch',label:'Origem'},{key:'notes',label:'Destino / Observação'}] },
  'financeiro/receber': { title:'Contas a Receber', subtitle:'Recebimentos, vencimentos e inadimplência.', addLabel:'Novo Lançamento', fields:[{key:'entry_type',label:'Tipo',type:'select',options:[['receivable','A Receber']]},{key:'description',label:'Descrição',required:true},{key:'customer_id',label:'Cliente',type:'select',lookup:'customers',optionLabel:'name'},{key:'amount',label:'Valor',type:'number',required:true},{key:'paid_amount',label:'Valor Recebido',type:'number'},{key:'due_date',label:'Vencimento',type:'date'},{key:'status',label:'Status',type:'select',options:statusFinance}], columns:[{key:'due_date',label:'Vencimento',format:'date'},{key:'customer',label:'Cliente'},{key:'description',label:'Descrição'},{key:'amount',label:'Valor',format:'currency'},{key:'paid_amount',label:'Recebido',format:'currency'},{key:'status',label:'Status',format:'status'}] },
  'financeiro/pagar': { title:'Contas a Pagar', subtitle:'Despesas e compromissos com fornecedores.', addLabel:'Novo Lançamento', fields:[{key:'entry_type',label:'Tipo',type:'select',options:[['payable','A Pagar']]},{key:'description',label:'Descrição',required:true},{key:'supplier_id',label:'Fornecedor',type:'select',lookup:'suppliers',optionLabel:'name'},{key:'amount',label:'Valor',type:'number',required:true},{key:'paid_amount',label:'Valor Pago',type:'number'},{key:'due_date',label:'Vencimento',type:'date'},{key:'status',label:'Status',type:'select',options:statusFinance}], columns:[{key:'due_date',label:'Vencimento',format:'date'},{key:'supplier',label:'Fornecedor'},{key:'description',label:'Descrição'},{key:'amount',label:'Valor',format:'currency'},{key:'paid_amount',label:'Pago',format:'currency'},{key:'status',label:'Status',format:'status'}] },
  'financeiro/fluxo-caixa': { title:'Fluxo de Caixa', subtitle:'Entradas, saídas, realizado e previsto.', fields:[], columns:[{key:'report_day',label:'Data',format:'date'},{key:'entry_type',label:'Tipo',format:'status'},{key:'total',label:'Total',format:'currency'},{key:'paid',label:'Realizado',format:'currency'},{key:'entries',label:'Lançamentos'}], readOnly:true, kind:'report' },
  'financeiro/conciliacao': { title:'Conciliação Financeira', subtitle:'Revise lançamentos pagos, parciais e em aberto.', fields:[], columns:[{key:'created_at',label:'Lançamento',format:'datetime'},{key:'description',label:'Descrição'},{key:'amount',label:'Valor',format:'currency'},{key:'paid_amount',label:'Liquidado',format:'currency'},{key:'status',label:'Status',format:'status'}], readOnly:true },
  'administrativo/empresas': { title:'Empresas e Filiais', subtitle:'Dados cadastrais e fiscais da organização.', addLabel:'Nova Empresa', fields:[{key:'legal_name',label:'Razão Social',required:true},{key:'trade_name',label:'Nome Fantasia'},{key:'cnpj',label:'CNPJ'},{key:'state_registration',label:'Inscrição Estadual'},{key:'tax_regime',label:'Regime Tributário'},{key:'email',label:'E-mail'},{key:'phone',label:'Telefone'},{key:'status',label:'Status',type:'select',options:[['active','Ativa'],['inactive','Inativa']]}], columns:[{key:'legal_name',label:'Razão Social'},{key:'trade_name',label:'Fantasia'},{key:'cnpj',label:'CNPJ'},{key:'tax_regime',label:'Regime'},{key:'status',label:'Status',format:'status'}] },
  'administrativo/pdvs': { title:'Caixas e PDVs', subtitle:'Terminais vinculados às filiais.', addLabel:'Novo PDV', fields:[{key:'name',label:'Nome do PDV',required:true},{key:'code',label:'Código'},{key:'branch_id',label:'Filial',type:'select',lookup:'branches',optionLabel:'name'},{key:'active',label:'Status',type:'select',options:yesNo}], columns:[{key:'name',label:'PDV'},{key:'code',label:'Código'},{key:'branch',label:'Filial'},{key:'active',label:'Status',format:'boolean'}] },
  fiscal: { title:'Documentos Fiscais', subtitle:'NF-e/NFC-e emitidas, autorizadas, rejeitadas e canceladas.', fields:[], columns:[{key:'document_type',label:'Tipo'},{key:'number',label:'Número'},{key:'series',label:'Série'},{key:'status',label:'Status',format:'status'},{key:'access_key',label:'Chave de Acesso'},{key:'provider',label:'Provedor'},{key:'created_at',label:'Data',format:'datetime'}], readOnly:true },
  integracoes: { title:'Integrações', subtitle:'Conectores externos sem armazenamento de segredos no frontend.', addLabel:'Nova Integração', fields:[{key:'category',label:'Categoria',required:true},{key:'provider',label:'Provedor',required:true},{key:'enabled',label:'Status',type:'select',options:yesNo}], columns:[{key:'category',label:'Categoria'},{key:'provider',label:'Provedor'},{key:'enabled',label:'Ativa',format:'boolean'},{key:'updated_at',label:'Atualizada em',format:'datetime'}] },
  configuracoes: { title:'Configurações Gerais', subtitle:'Dados empresariais usados pelos módulos do ThorPDV.', fields:[], columns:[{key:'legal_name',label:'Empresa'},{key:'trade_name',label:'Fantasia'},{key:'tax_regime',label:'Regime Tributário'},{key:'status',label:'Status',format:'status'}], readOnly:true },
  'relatorios/financeiro': { title:'Relatório Financeiro', subtitle:'Consolidado de contas a receber e a pagar.', fields:[], columns:[{key:'report_day',label:'Data',format:'date'},{key:'entry_type',label:'Tipo',format:'status'},{key:'total',label:'Total',format:'currency'},{key:'paid',label:'Realizado',format:'currency'},{key:'entries',label:'Lançamentos'}], readOnly:true, kind:'report' },
  'relatorios/vendas': { title:'Relatórios de Vendas PDV', subtitle:'Desempenho por produto e grupo.', fields:[], columns:[{key:'sku',label:'Código'},{key:'product',label:'Produto'},{key:'group_name',label:'Grupo'},{key:'quantity',label:'Quantidade'},{key:'avg_unit_price',label:'Valor Unitário Médio',format:'currency'},{key:'revenue',label:'Faturamento',format:'currency'}], readOnly:true, kind:'report' },
  'relatorios/estoque': { title:'Relatório de Estoque', subtitle:'Saldo, mínimo, custo e valor do estoque.', fields:[], columns:[{key:'sku',label:'Código'},{key:'name',label:'Produto'},{key:'stock',label:'Saldo'},{key:'minimum_stock',label:'Mínimo'},{key:'cost_price',label:'Custo',format:'currency'},{key:'stock_value',label:'Valor do Estoque',format:'currency'}], readOnly:true, kind:'report' },
  'relatorios/listagens': { title:'Listagens Gerais', subtitle:'Listagem exportável de produtos cadastrados.', fields:[], columns:[{key:'sku',label:'Código'},{key:'barcode',label:'EAN'},{key:'name',label:'Produto'},{key:'group_name',label:'Grupo'},{key:'sale_price',label:'Preço',format:'currency'},{key:'stock',label:'Estoque'}], readOnly:true, kind:'report' },
  atendimento: { title:'Central de Atendimento', subtitle:'Chamados e solicitações vinculados aos clientes.', addLabel:'Novo Chamado', fields:[{key:'customer_id',label:'Cliente',type:'select',lookup:'customers',optionLabel:'name'},{key:'subject',label:'Assunto',required:true},{key:'description',label:'Descrição',type:'textarea'},{key:'priority',label:'Prioridade',type:'select',options:[['low','Baixa'],['medium','Média'],['high','Alta'],['urgent','Urgente']]},{key:'status',label:'Status',type:'select',options:[['open','Aberto'],['in_progress','Em atendimento'],['waiting_customer','Aguardando cliente'],['resolved','Resolvido'],['closed','Fechado']]}], columns:[{key:'protocol',label:'Protocolo'},{key:'customer',label:'Cliente'},{key:'subject',label:'Assunto'},{key:'priority',label:'Prioridade',format:'status'},{key:'opened_at',label:'Abertura',format:'datetime'},{key:'status',label:'Status',format:'status'}] },
};

function configFor(slug: string): ModuleConfig {
  if (slug === 'clientes/novo') return configs.clientes;
  if (slug === 'produtos/novo') return configs.produtos;
  if (slug === 'financeiro/receber/novo') return configs['financeiro/receber'];
  if (slug === 'financeiro/pagar/novo') return configs['financeiro/pagar'];
  if (slug === 'estoque/nova') return configs.estoque;
  if (slug === 'atendimento/mensagens' || slug === 'atendimento/sla') return configs.atendimento;
  return configs[slug] ?? { title:'Módulo ThorPDV', subtitle:'Módulo integrado.', fields:[], columns:[], readOnly:true };
}

function formatValue(value: unknown, format?: Column['format']) {
  if (value === null || value === undefined || value === '') return '—';
  if (format === 'currency') return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));
  if (format === 'date') { const d=new Date(String(value)+'T00:00:00'); return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('pt-BR'); }
  if (format === 'datetime') { const d=new Date(String(value)); return Number.isNaN(d.getTime())?String(value):d.toLocaleString('pt-BR'); }
  if (format === 'boolean') return Boolean(value) ? 'Ativo' : 'Inativo';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

function filterRows(data:Row[],slug:string){
  if(slug==='financeiro/receber'||slug==='financeiro/receber/novo')return data.filter(r=>r.entry_type==='receivable');
  if(slug==='financeiro/pagar'||slug==='financeiro/pagar/novo')return data.filter(r=>r.entry_type==='payable');
  if(slug==='estoque/ajustes')return data.filter(r=>r.movement_type==='adjustment');
  if(slug==='estoque/transferencias')return data.filter(r=>r.movement_type==='transfer');
  return data;
}

function SaleScreen({ lookups }: { lookups: LookupMap }) {
  const products=lookups.products??[]; const customers=lookups.customers??[];
  const [customer,setCustomer]=useState(''); const [productId,setProductId]=useState(''); const [qty,setQty]=useState(1); const [method,setMethod]=useState('pix');
  const [cart,setCart]=useState<{product_id:string;name:string;quantity:number;unit_price:number;discount:number}[]>([]); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  const total=cart.reduce((s,i)=>s+i.quantity*i.unit_price-i.discount,0);
  const add=()=>{ const p=products.find(x=>x.id===productId); if(!p)return; setCart(c=>[...c,{product_id:String(p.id),name:String(p.name),quantity:Number(qty)||1,unit_price:Number(p.sale_price)||0,discount:0}]); setProductId(''); setQty(1); };
  const finish=async()=>{ if(!cart.length)return; setSaving(true); const result=await erpCreateSale({customer_id:customer||null,channel:'PDV',items:cart.map(({name,...item})=>item),payments:[{method,amount:total}]}); setSaving(false); if(result.ok){setMessage(`Venda nº ${String(result.number)} finalizada. Total ${formatValue(result.total,'currency')}. Estoque e pagamento atualizados.`);setCart([]);}else setMessage(`Erro: ${String(result.error??'não foi possível concluir')}`); };
  return <div className="erp-sale-grid"><section className="erp-module-card"><h2>Nova Venda</h2><div className="erp-form-grid"><label>Cliente<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Consumidor não identificado</option>{customers.map(c=><option value={String(c.id)} key={String(c.id)}>{String(c.name)}</option>)}</select></label><label>Produto<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Selecione...</option>{products.filter(p=>p.active!==false).map(p=><option value={String(p.id)} key={String(p.id)}>{String(p.name)} — {formatValue(p.sale_price,'currency')}</option>)}</select></label><label>Quantidade<input type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><button className="erp-primary" type="button" onClick={add}>Adicionar item</button></div></section><section className="erp-module-card"><h2>Carrinho</h2>{cart.length===0?<p className="erp-empty">Nenhum item adicionado.</p>:<table className="erp-data-table"><thead><tr><th>Produto</th><th>Qtd.</th><th>Unitário</th><th>Total</th><th></th></tr></thead><tbody>{cart.map((i,index)=><tr key={`${i.product_id}-${index}`}><td>{i.name}</td><td>{i.quantity}</td><td>{formatValue(i.unit_price,'currency')}</td><td>{formatValue(i.quantity*i.unit_price-i.discount,'currency')}</td><td><button className="erp-row-action" onClick={()=>setCart(c=>c.filter((_,x)=>x!==index))}>×</button></td></tr>)}</tbody></table>}<div className="erp-sale-total"><label>Pagamento<select value={method} onChange={e=>setMethod(e.target.value)}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit_card">Cartão de crédito</option><option value="debit_card">Cartão de débito</option></select></label><strong>Total: {formatValue(total,'currency')}</strong><button disabled={!cart.length||saving} className="erp-primary" onClick={finish}>{saving?'Finalizando...':'Finalizar venda'}</button></div>{message&&<p className="erp-message">{message}</p>}</section></div>;
}

type ModuleClientProps={slug:string;resource:string;initialData:Row[];lookups:LookupMap;initialTotal?:number;serverPaged?:boolean};

export function ModuleClient({ slug, resource, initialData, lookups, initialTotal=initialData.length, serverPaged=true }: ModuleClientProps) {
  const config=configFor(slug); const [rows,setRows]=useState<Row[]>(initialData); const [total,setTotal]=useState(initialTotal); const [offset,setOffset]=useState(0); const [search,setSearch]=useState(''); const [modal,setModal]=useState(slug.endsWith('/novo')); const [editing,setEditing]=useState<Row|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  const filtered=useMemo(()=>filterRows(rows,slug),[rows,slug]);
  const effectiveTotal=serverPaged?total:filtered.length;
  const visibleRows=serverPaged?filtered:filtered.slice(offset,offset+PAGE_SIZE);
  const pageCount=Math.max(1,Math.ceil(effectiveTotal/PAGE_SIZE));
  const page=Math.floor(offset/PAGE_SIZE)+1;
  const from=effectiveTotal===0?0:offset+1;
  const to=Math.min(offset+visibleRows.length,effectiveTotal);
  const totalValue=useMemo(()=>visibleRows.reduce((s,r)=>s+Number(r.total??r.amount??r.revenue??r.stock_value??0),0),[visibleRows]);
  const refresh=async(q=search,nextOffset=offset)=>{
    if(serverPaged){const res=await erpLoadPage(resource,q,PAGE_SIZE,nextOffset);if(res.ok){setRows(res.data);setTotal(res.total);setOffset(res.offset);}else setMessage(String(res.error??'Erro ao carregar'));return;}
    const res=await erpLoad(resource,q);if(res.ok){setRows(res.data);setTotal(filterRows(res.data,slug).length);setOffset(Math.min(nextOffset,Math.max(0,(Math.ceil(filterRows(res.data,slug).length/PAGE_SIZE)-1)*PAGE_SIZE)));}else setMessage(String(res.error??'Erro ao carregar'));
  };
  const openNew=()=>{setEditing(null);setModal(true);setMessage('');};
  const openEdit=(row:Row)=>{setEditing(row);setModal(true);setMessage('');};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const fd=new FormData(e.currentTarget);const payload:Record<string,unknown>={}; for(const field of config.fields){const raw=fd.get(field.key); if(field.type==='number')payload[field.key]=raw===''?0:Number(raw); else if(field.type==='checkbox')payload[field.key]=raw==='on'; else payload[field.key]=raw?.toString()??'';} if(editing?.id)payload.id=editing.id; if('permissions_text' in payload){const text=String(payload.permissions_text||'');payload.permissions=Object.fromEntries(text.split(',').map(x=>x.trim()).filter(Boolean).map(x=>[x,true]));delete payload.permissions_text;} if('rules_text' in payload){payload.rules={description:String(payload.rules_text||'')};delete payload.rules_text;} const result=await erpSave(resource,payload);setSaving(false);if(result.ok){setModal(false);setEditing(null);setMessage('Registro salvo com sucesso.');await refresh(search,offset);}else setMessage(`Erro: ${String(result.error??'não foi possível salvar')}`);};
  const doSearch=async(e:FormEvent)=>{e.preventDefault();setOffset(0);await refresh(search,0);};
  const changePage=async(nextOffset:number)=>{const safe=Math.max(0,nextOffset);setMessage('');if(serverPaged)await refresh(search,safe);else setOffset(safe);};
  const exportCsv=async()=>{const full=await erpLoad(resource,search);const source=full.ok?filterRows(full.data,slug):filtered;const cols=config.columns;const lines=[cols.map(c=>`"${c.label}"`).join(';'),...source.map(r=>cols.map(c=>`"${formatValue(r[c.key],c.format).replaceAll('"','""')}"`).join(';'))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`thorpdv-${slug.replaceAll('/','-')}.csv`;a.click();URL.revokeObjectURL(url);};

  const title=slug==='vendas/nova'?'Nova Venda PDV':config.title;
  const subtitle=slug==='vendas/nova'?'Venda integrada a estoque, pagamentos e financeiro.':config.subtitle;
  return <AdvancedShell title={title} subtitle={subtitle} activePath={`/dashboard/${slug}`}>
    {slug==='vendas/nova'?<SaleScreen lookups={lookups}/>:<>
      <div className="erp-module-kpis"><article><span>Registros</span><strong>{effectiveTotal}</strong><small>no módulo atual</small></article><article><span>Ativos / válidos</span><strong>{visibleRows.filter(r=>r.active!==false&&r.status!=='cancelled').length}</strong><small>na página atual</small></article><article><span>Valor exibido</span><strong>{formatValue(totalValue,'currency')}</strong><small>na página atual</small></article><article><span>Integração</span><strong>Online</strong><small>Supabase conectado</small></article></div>
      <section className="erp-module-card"><div className="erp-module-toolbar"><form onSubmit={doSearch} className="erp-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar neste módulo..."/><button type="submit">Buscar</button></form><div className="erp-toolbar-actions">{config.kind==='report'&&<button className="erp-ghost" onClick={()=>window.print()}>Imprimir / PDF</button>}<button className="erp-ghost" onClick={()=>void exportCsv()}>Exportar CSV</button>{!config.readOnly&&config.addLabel&&<button className="erp-primary" onClick={openNew}>+ {config.addLabel}</button>}</div></div>
        {message&&<p className="erp-message">{message}</p>}
        <div className="erp-table-scroll"><table className="erp-data-table"><thead><tr>{config.columns.map(c=><th key={c.key}>{c.label}</th>)}{!config.readOnly&&<th>Ações</th>}</tr></thead><tbody>{visibleRows.length===0?<tr><td colSpan={config.columns.length+1} className="erp-empty">Nenhum registro encontrado. Use o botão de cadastro para começar.</td></tr>:visibleRows.map((row,index)=><tr key={String(row.id??`${offset}-${index}`)}>{config.columns.map(c=><td key={c.key}>{(c.format==='boolean'||c.format==='status')?<span className={`erp-pill ${String(row[c.key])==='false'||row[c.key]===false||['cancelled','overdue','inactive','closed'].includes(String(row[c.key]))?'danger':''}`}>{formatValue(row[c.key],c.format)}</span>:formatValue(row[c.key],c.format)}</td>)}{!config.readOnly&&<td><button className="erp-row-action" onClick={()=>openEdit(row)}>Editar</button></td>}</tr>)}</tbody></table></div>
        <footer className="erp-table-footer"><span>{effectiveTotal} registro(s) • exibindo {from}–{to}</span><div className="erp-pagination"><button type="button" className="erp-ghost" disabled={offset===0} onClick={()=>void changePage(offset-PAGE_SIZE)}>← Anterior</button><span>Página {page} de {pageCount}</span><button type="button" className="erp-ghost" disabled={offset+PAGE_SIZE>=effectiveTotal} onClick={()=>void changePage(offset+PAGE_SIZE)}>Próxima →</button></div><span>10 registros por página</span></footer>
      </section>
    </>}
    {modal&&<div className="erp-modal-backdrop" onMouseDown={()=>setModal(false)}><div className="erp-modal" onMouseDown={e=>e.stopPropagation()}><div className="erp-modal-head"><div><h2>{editing?'Editar registro':config.addLabel??'Novo registro'}</h2><p>{config.subtitle}</p></div><button onClick={()=>setModal(false)}>×</button></div><form onSubmit={submit}><div className="erp-form-grid">{config.fields.map(field=>{const value=editing?.[field.key]??(field.key==='active'?'true':'');const options=field.options??(field.lookup?(lookups[field.lookup]??[]).map(r=>[String(r.id),String(r[field.optionLabel??'name'])] as [string,string]):undefined);return <label key={field.key} className={field.type==='textarea'?'wide':''}>{field.label}{field.type==='textarea'?<textarea name={field.key} defaultValue={field.key==='permissions_text'&&editing?.permissions?Object.keys(editing.permissions as Record<string,unknown>).join(', '):String(value??'')} placeholder={field.placeholder}/>:field.type==='select'?<select name={field.key} defaultValue={String(value??'')} required={field.required}><option value="">Selecione...</option>{options?.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>:<input name={field.key} type={field.type??'text'} step={field.type==='number'?'0.01':undefined} defaultValue={String(value??'')} placeholder={field.placeholder} required={field.required}/>}</label>})}</div><div className="erp-modal-actions"><button type="button" className="erp-ghost" onClick={()=>setModal(false)}>Cancelar</button><button className="erp-primary" disabled={saving}>{saving?'Salvando...':'Salvar'}</button></div></form></div></div>}
  </AdvancedShell>;
}
