'use client';

import { FormEvent, useEffect, useState } from 'react';
import { erpLoad, erpPriceTableCopy, erpPriceTableDetail, erpPriceTableSetItem, erpSave } from './actions';
import { ListPagination,useListPagination } from './list-pagination';

type Row = Record<string, unknown>;
const money=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));

export function PriceTableWorkspace({ initialTables, products, copyMode=false }:{initialTables:Row[];products:Row[];copyMode?:boolean}){
  const [tables,setTables]=useState(initialTables);const [selected,setSelected]=useState(String(initialTables[0]?.id??''));const [detail,setDetail]=useState<{table?:Row;items?:Row[]}>({});const [message,setMessage]=useState('');
  const [name,setName]=useState('');const [tableType,setTableType]=useState('standard');const [validFrom,setValidFrom]=useState('');const [validTo,setValidTo]=useState('');const [active,setActive]=useState(true);
  const [productId,setProductId]=useState('');const [price,setPrice]=useState(0);const [copyName,setCopyName]=useState('');
  const tablePager=useListPagination(tables);const itemPager=useListPagination(detail.items??[]);

  async function refresh(){const r=await erpLoad('price_tables');if(r.ok){setTables(r.data);if(!selected&&r.data[0])setSelected(String(r.data[0].id));}}
  async function load(id=selected){if(!id){setDetail({});return;}const r=await erpPriceTableDetail(id);if(r.ok){const t=r.table as Row;setDetail({table:t,items:(r.items as Row[])??[]});itemPager.setPage(0);setName(String(t.name??''));setTableType(String(t.table_type??'standard'));setValidFrom(String(t.valid_from??''));setValidTo(String(t.valid_to??''));setActive(t.active!==false);}else setMessage(String(r.error??'Falha ao carregar'));}
  useEffect(()=>{void load(selected);},[selected]);

  async function saveTable(e:FormEvent){e.preventDefault();const payload:Record<string,unknown>={name,table_type:tableType,valid_from:validFrom,valid_to:validTo,active};if(detail.table?.id)payload.id=detail.table.id;const r=await erpSave('price_tables',payload);if(r.ok){setMessage('Tabela salva.');await refresh();if(!detail.table?.id&&r.id)setSelected(String(r.id));}else setMessage(String(r.error??'Falha ao salvar tabela'));}
  function newTable(){setSelected('');setDetail({});setName('');setTableType('standard');setValidFrom('');setValidTo('');setActive(true);setMessage('Nova tabela: preencha os dados e salve.');}
  async function saveItem(e:FormEvent){e.preventDefault();if(!selected)return;const r=await erpPriceTableSetItem(selected,productId,price);if(r.ok){setMessage('Preço específico salvo.');setProductId('');setPrice(0);await load();}else setMessage(String(r.error??'Falha ao salvar item'));}
  async function copy(){if(!selected)return;const r=await erpPriceTableCopy(selected,copyName);if(r.ok){setMessage('Cópia criada inativa para revisão.');setCopyName('');await refresh();if(r.id)setSelected(String(r.id));}else setMessage(String(r.error??'Falha ao copiar'));}

  return <div className="erp-price-workspace"><section className="erp-module-card erp-price-sidebar"><div className="erp-price-title"><div><h2>Tabelas</h2><p>{tables.length} cadastrada(s)</p></div>{!copyMode&&<button className="erp-primary" onClick={newTable}>+ Nova</button>}</div><div className="erp-price-list">{tablePager.pageRows.map(t=><button key={String(t.id)} className={selected===String(t.id)?'active':''} onClick={()=>setSelected(String(t.id))}><strong>{String(t.name)}</strong><span>{String(t.table_type)} · {String(t.item_count??0)} itens</span></button>)}</div><ListPagination page={tablePager.page} pageCount={tablePager.pageCount} total={tablePager.total} from={tablePager.from} to={tablePager.to} onPage={tablePager.setPage} label="tabela(s)"/></section>
    <div className="erp-price-content">{copyMode?<section className="erp-module-card erp-advanced-panel"><h2>Copiar tabela completa</h2><p>A cópia replica todos os preços e começa inativa para revisão.</p><label>Origem<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione...</option>{tables.map(t=><option value={String(t.id)} key={String(t.id)}>{String(t.name)}</option>)}</select></label><label>Nome da cópia<input value={copyName} onChange={e=>setCopyName(e.target.value)} placeholder="Nova tabela"/></label><button className="erp-primary" onClick={copy} disabled={!selected}>Copiar tabela + itens</button>{message&&<p className="erp-message">{message}</p>}</section>:<>
      <section className="erp-module-card erp-advanced-panel"><h2>{detail.table?'Configuração da tabela':'Nova tabela'}</h2><form className="erp-form-grid" onSubmit={saveTable}><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Tipo<select value={tableType} onChange={e=>setTableType(e.target.value)}><option value="standard">Padrão</option><option value="wholesale">Atacado</option><option value="promotion">Promoção</option><option value="adjustment">Ajuste</option></select></label><label>Vigência inicial<input type="date" value={validFrom} onChange={e=>setValidFrom(e.target.value)}/></label><label>Vigência final<input type="date" value={validTo} onChange={e=>setValidTo(e.target.value)}/></label><label>Status<select value={active?'true':'false'} onChange={e=>setActive(e.target.value==='true')}><option value="true">Ativa</option><option value="false">Inativa</option></select></label><button className="erp-primary">Salvar tabela</button></form>{message&&<p className="erp-message">{message}</p>}</section>
      {selected&&<section className="erp-module-card"><div className="erp-price-item-head"><div><h2>Preços por produto</h2><p>Quando um preço específico existir, ele substitui o preço base nessa tabela.</p></div><form onSubmit={saveItem}><select required value={productId} onChange={e=>{setProductId(e.target.value);const p=products.find(x=>String(x.id)===e.target.value);setPrice(Number(p?.sale_price??0));}}><option value="">Produto...</option>{products.map(p=><option value={String(p.id)} key={String(p.id)}>{String(p.name)}</option>)}</select><input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/><button className="erp-primary">Aplicar</button></form></div><div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Código</th><th>Produto</th><th>Base</th><th>Nesta tabela</th><th>Diferença</th></tr></thead><tbody>{(detail.items??[]).length===0?<tr><td className="erp-empty" colSpan={5}>Nenhum preço específico ainda.</td></tr>:itemPager.pageRows.map((i,n)=><tr key={String(i.product_id??`${itemPager.page}-${n}`)}><td>{String(i.sku??'—')}</td><td>{String(i.product)}</td><td>{money(i.base_price)}</td><td><strong>{money(i.price)}</strong></td><td>{money(Number(i.price??0)-Number(i.base_price??0))}</td></tr>)}</tbody></table></div><ListPagination page={itemPager.page} pageCount={itemPager.pageCount} total={itemPager.total} from={itemPager.from} to={itemPager.to} onPage={itemPager.setPage} label="item(ns)"/></section>}</>}
    </div>
  </div>;
}
