'use client';

import { FormEvent, useState } from 'react';
import { erpLoad, erpSave } from './actions';
import { executePriceAdjustment } from './price-adjustment-actions';
import { ListPagination,useListPagination } from './list-pagination';

type Row=Record<string,unknown>;
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR'):'—';

export function PriceAdjustmentWorkspace({initial,priceTables}:{initial:Row[];priceTables:Row[]}){
 const [rows,setRows]=useState(initial);const [message,setMessage]=useState('');const pager=useListPagination(rows);
 async function refresh(){const r=await erpLoad('price_adjustments');if(r.ok){setRows(r.data);pager.setPage(0)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const r=await erpSave('price_adjustments',{name:String(fd.get('name')??''),price_table_id:String(fd.get('price_table_id')??''),adjustment_type:String(fd.get('adjustment_type')??'percent'),adjustment_value:Number(fd.get('adjustment_value')??0),execute_at:String(fd.get('execute_at')??''),status:'scheduled'});if(r.ok){setMessage('Ajuste agendado. Quando a data vencer, o catálogo aplica automaticamente antes da próxima venda.');e.currentTarget.reset();await refresh()}else setMessage(String(r.error??'Falha ao agendar'))}
 async function execute(id:string){if(!confirm('Executar este ajuste agora sobre todos os itens da tabela?'))return;const r=await executePriceAdjustment(id);if(r.ok){setMessage('Ajuste executado e preços da tabela atualizados.');await refresh()}else setMessage(String(r.error??'Falha ao executar'))}
 return <div className="erp-promotion-grid"><section className="erp-module-card erp-advanced-panel"><h2>Novo ajuste programado</h2><p>Use valor positivo para aumento e negativo para redução.</p><form className="erp-form-grid" onSubmit={submit}><label>Descrição<input required name="name"/></label><label>Tabela<select required name="price_table_id"><option value="">Selecione...</option>{priceTables.map(t=><option value={String(t.id)} key={String(t.id)}>{String(t.name)}</option>)}</select></label><label>Tipo<select name="adjustment_type"><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select></label><label>Valor<input required name="adjustment_value" type="number" step="0.01"/></label><label>Executar em<input required name="execute_at" type="datetime-local"/></label><button className="erp-primary">Agendar ajuste</button></form>{message&&<p className="erp-message">{message}</p>}</section><section className="erp-module-card"><div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Ajuste</th><th>Tabela</th><th>Tipo</th><th>Valor</th><th>Execução</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={7} className="erp-empty">Nenhum ajuste programado.</td></tr>:pager.pageRows.map((r,i)=><tr key={String(r.id??`${pager.page}-${i}`)}><td>{String(r.name)}</td><td>{String(r.price_table??'—')}</td><td>{String(r.adjustment_type)}</td><td>{String(r.adjustment_value)}</td><td>{dt(r.execute_at)}</td><td><span className="erp-pill">{String(r.status)}</span></td><td>{['scheduled','draft'].includes(String(r.status))?<button className="erp-row-action" onClick={()=>execute(String(r.id))}>Executar agora</button>:'—'}</td></tr>)}</tbody></table></div><ListPagination page={pager.page} pageCount={pager.pageCount} total={pager.total} from={pager.from} to={pager.to} onPage={pager.setPage} label="ajuste(s)"/></section></div>;
}
