'use client';
import { FormEvent,useState } from 'react';
import { productAttributeValueDisable,productAttributeValueSave } from './product-reference-actions';
import type { ReferenceKind } from './product-reference-workspace';
type Row=Record<string,unknown>;const text=(v:unknown)=>v==null?'':String(v);
export function ProductReferenceModal({kind,row,suggestedCode,onClose,onSave}:{kind:ReferenceKind;row:Row|null;suggestedCode:number;onClose:()=>void;onSave:(p:Row)=>Promise<boolean>}){const [name,setName]=useState(text(row?.name));const [code,setCode]=useState(text(row?.code)||String(suggestedCode));const [decimals,setDecimals]=useState(text(row?.decimal_places)||'3');const [type,setType]=useState(text(row?.attribute_type)||'text');const [active,setActive]=useState(row?.active!==false);const [values,setValues]=useState<Row[]>(Array.isArray(row?.values)?row!.values as Row[]:[]);const [newValue,setNewValue]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const p:Row={id:text(row?.id)||undefined,name,active};if(kind==='categories')p.code=code;if(kind==='units'){p.code=code;p.decimal_places=Number(decimals)}if(kind==='attributes')p.attribute_type=type;await onSave(p)}finally{setBusy(false)}}
 async function addValue(){if(!row?.id||!newValue.trim())return;setBusy(true);try{const r=await productAttributeValueSave(text(row.id),newValue.trim(),values.length+1);if(r.ok){setValues(c=>[...c,{id:text(r.id),value:newValue.trim()}]);setNewValue('')}}finally{setBusy(false)}}
 async function removeValue(v:Row){if(!text(v.id))return;setBusy(true);try{const r=await productAttributeValueDisable(text(v.id));if(r.ok)setValues(c=>c.filter(x=>text(x.id)!==text(v.id)))}finally{setBusy(false)}}
 return <div className="ref-backdrop"><section className="ref-modal"><header><div><span>CADASTRO</span><h2>{row?'Editar':'Novo'} {kind==='brands'?'marca':kind==='categories'?'categoria':kind==='units'?'unidade':'atributo'}</h2></div><button type="button" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="ref-form">{kind==='categories'&&<label>Referência<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/></label>}{kind==='units'&&<label>Código<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required/></label>}<label>Descrição<input value={name} onChange={e=>setName(e.target.value)} autoFocus required/></label>{kind==='units'&&<label>Casas decimais<select value={decimals} onChange={e=>setDecimals(e.target.value)}>{[0,1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label>}{kind==='attributes'&&<label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="text">Texto</option><option value="color">Cor</option><option value="size">Tamanho</option></select></label>}<label>Status<button type="button" className={`ref-status ${active?'active':''}`} onClick={()=>setActive(x=>!x)}>{active?'Ativo':'Inativo'}</button></label></div>{kind==='attributes'&&<fieldset><legend>Valores</legend><div className="ref-values">{values.map(v=><span key={text(v.id)}>{text(v.value)}<button type="button" onClick={()=>removeValue(v)}>×</button></span>)}</div>{row?.id?<div className="ref-add-value"><input value={newValue} onChange={e=>setNewValue(e.target.value)} placeholder="Novo valor"/><button type="button" onClick={addValue}>Adicionar</button></div>:<small>Salve e reabra o atributo para adicionar os valores.</small>}</fieldset>}<footer><button type="button" className="ref-cancel" onClick={onClose}>Cancelar</button><button className="ref-primary" disabled={busy}>{busy?'Salvando...':'Salvar'}</button></footer></form></section></div>}
