'use client';
import { useState,useTransition } from 'react';
import { productBrandSave,productCategorySave,productReferenceList,productUnitSave,productAttributeSave } from './product-reference-actions';
import { ProductReferenceModal } from './product-reference-modal';
type Row=Record<string,unknown>;export type ReferenceKind='brands'|'categories'|'units'|'attributes';
const text=(v:unknown)=>v==null?'':String(v);const num=(v:unknown)=>Number(v||0)||0;
const info={brands:['Marcas','Nova'],categories:['Categorias','Nova categoria'],units:['Unidades de Medida','Nova unidade'],attributes:['Atributos','Novo']} as const;
const columns:Record<ReferenceKind,string[]>={brands:['Descrição','Produtos','Ativa'],categories:['Referência','Descrição','Produtos','Ativa'],units:['Código','Descrição','Casas decimais','Produtos','Ativa'],attributes:['Descrição','Tipo','Valores','Ativo']};
function friendly(v:unknown){const s=text(v);if(s.includes('unique')||s.includes('duplicate'))return 'Já existe um cadastro com essa informação.';return s||'Não foi possível concluir a operação.'}
export function ProductReferenceWorkspace({kind,initial}:{kind:ReferenceKind;initial:Row[]}){const [data,setData]=useState(initial);const [search,setSearch]=useState('');const [editing,setEditing]=useState<Row|null|undefined>(undefined);const [message,setMessage]=useState('');const [pending,startTransition]=useTransition();
 async function refresh(){const r=await productReferenceList(kind,search);if(r.ok)setData(r.data);else setMessage(friendly(r.error))}
 async function save(payload:Row){let r:Record<string,unknown>;if(kind==='brands')r=await productBrandSave(payload);else if(kind==='categories')r=await productCategorySave(payload);else if(kind==='units')r=await productUnitSave(payload);else r=await productAttributeSave(payload);if(!r.ok){setMessage(friendly(r.error));return false}await refresh();setMessage('Cadastro salvo com sucesso.');return true}
 function toggle(row:Row){startTransition(async()=>{await save({...row,active:row.active===false})})}
 return <section className="ref-card"><div className="ref-toolbar"><form onSubmit={e=>{e.preventDefault();startTransition(refresh)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar"/><button title="Pesquisar">↻</button></form><div><button className="ref-primary" type="button" onClick={()=>setEditing(null)}>+ {info[kind][1]}</button><button className="ref-filter" type="button" onClick={()=>startTransition(refresh)}>⌕ Filtrar</button></div></div>{message&&<div className="ref-message">{message}</div>}<div className="ref-table-wrap"><table><thead><tr><th>Ações</th>{columns[kind].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.length?data.map(row=><RefRow key={text(row.id)} kind={kind} row={row} edit={()=>setEditing(row)} toggle={()=>toggle(row)}/>):<tr><td className="ref-empty" colSpan={columns[kind].length+1}>Nenhum cadastro encontrado.</td></tr>}</tbody></table></div><footer><span>{data.length} {info[kind][0].toLowerCase()}</span><span>{pending?'Atualizando...':'Thor Gestão'}</span></footer>{editing!==undefined&&<ProductReferenceModal kind={kind} row={editing} suggestedCode={Math.max(0,...data.map(x=>num(x.code)))+1} onClose={()=>setEditing(undefined)} onSave={async p=>{const ok=await save(p);if(ok)setEditing(undefined);return ok}}/>}</section>}
function RefRow({kind,row,edit,toggle}:{kind:ReferenceKind;row:Row;edit:()=>void;toggle:()=>void}){const active=row.active!==false;return <tr><td><button className="ref-edit" onClick={edit}>✎</button></td>{kind==='brands'&&<><td><strong>{text(row.name)}</strong></td><td><Count n={row.product_count}/></td></>}{kind==='categories'&&<><td>{text(row.code)}</td><td><div className="ref-name"><span className="ref-photo">▧</span><strong>{text(row.name)}</strong></div></td><td><Count n={row.product_count}/></td></>}{kind==='units'&&<><td><strong>{text(row.code)}</strong></td><td>{text(row.name)}</td><td>{num(row.decimal_places)}</td><td><Count n={row.product_count}/></td></>}{kind==='attributes'&&<><td><button className="ref-expand" onClick={edit}>›</button><strong>{text(row.name)}</strong></td><td>{text(row.attribute_type)==='color'?'Cor':text(row.attribute_type)==='size'?'Tamanho':'Texto'}</td><td><Count n={row.value_count}/></td></>}<td><button className={`ref-switch ${active?'':'off'}`} onClick={toggle}><i/></button></td></tr>}
function Count({n}:{n:unknown}){return <span className="ref-count">{num(n)}</span>}
