'use client';

import { useMemo, useState } from 'react';
import { salesOrderCancel, salesOrderDetail, salesOrderList, salesOrderSave, paymentTermSave } from './sales-order-actions';

type Row=Record<string,unknown>;
type Cart={product_id:string;product_code:string;sku:string;name:string;unit:string;quantity:number;unit_price:number;discount:number};
const money=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
const n=(v:unknown)=>{const x=Number(v??0);return Number.isFinite(x)?x:0};
const s=(v:unknown)=>String(v??'');
const paymentNames:Record<string,string>={cash:'Dinheiro',pix:'PIX',debit_card:'Cartão de débito',credit_card:'Cartão de crédito',voucher:'Voucher',store_credit:'Crédito da loja',other:'Outro'};

export function SalesOrderWorkspace({initialOrders,customers,sellers,catalog,initialTerms}:{initialOrders:Row[];customers:Row[];sellers:Row[];catalog:Row[];initialTerms:Row[]}){
  const [orders,setOrders]=useState(initialOrders);const [terms,setTerms]=useState(initialTerms);const [editing,setEditing]=useState<string>('');const [customer,setCustomer]=useState('');const [seller,setSeller]=useState('');const [product,setProduct]=useState('');const [qty,setQty]=useState(1);const [itemDiscount,setItemDiscount]=useState(0);const [cart,setCart]=useState<Cart[]>([]);const [discount,setDiscount]=useState(0);const [surcharge,setSurcharge]=useState(0);const [condition,setCondition]=useState<'immediate'|'term'>('immediate');const [paymentMethod,setPaymentMethod]=useState('pix');const [termId,setTermId]=useState('');const [termMethod,setTermMethod]=useState<'boleto'|'crediario'>('crediario');const [installments,setInstallments]=useState(1);const [firstDue,setFirstDue]=useState(30);const [interval,setInterval]=useState(30);const [interest,setInterest]=useState(0);const [notes,setNotes]=useState('');const [message,setMessage]=useState('');const [search,setSearch]=useState('');const [saving,setSaving]=useState(false);
  const [planName,setPlanName]=useState('');const [planMethod,setPlanMethod]=useState<'boleto'|'crediario'>('crediario');const [planInstallments,setPlanInstallments]=useState(1);const [planFirst,setPlanFirst]=useState(30);const [planInterval,setPlanInterval]=useState(30);const [planInterest,setPlanInterest]=useState(0);
  const subtotal=useMemo(()=>cart.reduce((a,i)=>a+i.quantity*i.unit_price-i.discount,0),[cart]);const total=Math.max(subtotal-discount+surcharge,0);const interestAmount=condition==='term'?total*interest/100:0;const financedTotal=total+interestAmount;
  const selectedTerm=terms.find(t=>s(t.id)===termId);

  function newOrder(){setEditing('');setCustomer('');setSeller('');setProduct('');setQty(1);setItemDiscount(0);setCart([]);setDiscount(0);setSurcharge(0);setCondition('immediate');setPaymentMethod('pix');setTermId('');setTermMethod('crediario');setInstallments(1);setFirstDue(30);setInterval(30);setInterest(0);setNotes('');setMessage('');}
  function addItem(){const p=catalog.find(x=>s(x.id)===product);if(!p)return;if(qty<=0){setMessage('Quantidade deve ser maior que zero.');return;}const price=n(p.effective_price??p.sale_price);if(itemDiscount>qty*price){setMessage('Desconto do item maior que o valor do item.');return;}setCart(c=>[...c,{product_id:s(p.id),product_code:s(p.product_code),sku:s(p.sku),name:s(p.name),unit:s(p.unit||'UN'),quantity:qty,unit_price:price,discount:itemDiscount}]);setProduct('');setQty(1);setItemDiscount(0);setMessage('');}
  function applyTerm(id:string){setTermId(id);const t=terms.find(x=>s(x.id)===id);if(!t)return;setTermMethod(s(t.method)==='boleto'?'boleto':'crediario');setInstallments(n(t.installments)||1);setFirstDue(n(t.first_due_days));setInterval(n(t.interval_days)||30);setInterest(n(t.interest_percent));}
  async function refresh(q=search){const r=await salesOrderList(q);if(r.ok)setOrders(r.data);else setMessage(String(r.error??'Falha ao carregar pedidos.'));}
  async function save(){if(!customer){setMessage('O cliente é obrigatório no pedido de venda.');return;}if(!cart.length){setMessage('Adicione pelo menos um produto.');return;}if(discount>subtotal){setMessage('Desconto geral maior que o subtotal.');return;}setSaving(true);const r=await salesOrderSave({id:editing||null,customer_id:customer,seller_user_id:seller||null,payment_condition:condition,payment_method:condition==='immediate'?paymentMethod:null,payment_term_id:condition==='term'?termId||null:null,term_method:condition==='term'?termMethod:null,installments:condition==='term'?installments:null,first_due_days:condition==='term'?firstDue:null,interval_days:condition==='term'?interval:null,interest_percent:condition==='term'?interest:null,discount,surcharge,notes:notes||null,items:cart.map(i=>({product_id:i.product_id,quantity:i.quantity,discount:i.discount}))});setSaving(false);if(r.ok){setMessage(`Pedido nº ${String(r.number)} salvo por ${money(r.total)}. Ele já pode ser sincronizado e buscado no ThorPDV.`);newOrder();await refresh('');}else setMessage(`Não foi possível salvar: ${String(r.error??'erro')}`);}
  async function loadOrder(id:string){const r=await salesOrderDetail(id);if(!r.ok||!r.order){setMessage(String(r.error??'Pedido não encontrado.'));return;}const o=r.order;setEditing(s(o.id));setCustomer(s(o.customer_id));setSeller(s(o.seller_user_id));setCondition(s(o.payment_condition)==='term'?'term':'immediate');setPaymentMethod(s(o.payment_method)||'pix');setTermId(s(o.payment_term_id));setTermMethod(s(o.term_method)==='boleto'?'boleto':'crediario');setInstallments(n(o.installments)||1);setFirstDue(n(o.first_due_days));setInterval(n(o.interval_days)||30);setInterest(n(o.interest_percent));setDiscount(n(o.discount));setSurcharge(n(o.surcharge));setNotes(s(o.notes));setCart((Array.isArray(o.items)?o.items:[]).map(x=>{const i=x as Row;return{product_id:s(i.product_id),product_code:s(i.product_code),sku:s(i.sku),name:s(i.name),unit:s(i.unit||'UN'),quantity:n(i.quantity),unit_price:n(i.unit_price),discount:n(i.discount)}}));setMessage(`Editando pedido nº ${String(o.number)}.`);window.scrollTo({top:0,behavior:'smooth'});}
  async function cancel(id:string){const r=await salesOrderCancel(id);if(r.ok){setMessage('Pedido cancelado.');if(editing===id)newOrder();await refresh();}else setMessage(String(r.error??'Não foi possível cancelar.'));}
  async function savePlan(){if(!planName.trim()){setMessage('Informe o nome do plano.');return;}const r=await paymentTermSave({name:planName.trim(),method:planMethod,installments:planInstallments,first_due_days:planFirst,interval_days:planInterval,interest_percent:planInterest,active:true});if(r.ok){const fresh={id:r.id,name:planName.trim(),method:planMethod,installments:planInstallments,first_due_days:planFirst,interval_days:planInterval,interest_percent:planInterest,active:true};setTerms(t=>[...t,fresh]);setPlanName('');setMessage('Plano de venda a prazo salvo.');}else setMessage(String(r.error??'Falha ao salvar plano.'));}

  return <div className="erp-so-shell"><section className="erp-module-card erp-so-form"><div className="erp-so-head"><div><small>{editing?'EDIÇÃO':'NOVO PEDIDO'}</small><h2>{editing?'Editar pedido de venda':'Pedido de venda'}</h2><p>O pedido registra a negociação sem movimentar estoque ou financeiro. A baixa ocorre somente quando for convertido em venda.</p></div><button className="erp-ghost" onClick={newOrder}>Limpar / Novo</button></div>
    <div className="erp-so-grid"><label>Cliente obrigatório<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Selecione o cliente...</option>{customers.filter(x=>x.active!==false).map(x=><option key={s(x.id)} value={s(x.id)}>{s(x.name)}{x.document?` — ${s(x.document)}`:''}</option>)}</select></label><label>Vendedor (opcional)<select value={seller} onChange={e=>setSeller(e.target.value)}><option value="">Sem vendedor identificado</option>{sellers.map(x=><option key={s(x.id)} value={s(x.id)}>{s(x.name)}</option>)}</select></label></div>
    <div className="erp-so-add"><label>Produto<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Selecione...</option>{catalog.map(p=><option key={s(p.id)} value={s(p.id)}>Cód. {s(p.product_code||'—')} · {s(p.name)} · {money(p.effective_price??p.sale_price)} · {s(p.unit||'UN')}</option>)}</select></label><label>Qtd.<input type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(n(e.target.value))}/></label><label>Desc. item<input type="number" min="0" step="0.01" value={itemDiscount} onChange={e=>setItemDiscount(n(e.target.value))}/></label><button className="erp-primary" onClick={addItem} disabled={!product}>Adicionar</button></div>
    <div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Cód.</th><th>Referência</th><th>Produto</th><th>Qtd./UN</th><th>Unitário</th><th>Desconto</th><th>Total</th><th></th></tr></thead><tbody>{cart.length?cart.map((i,idx)=><tr key={`${i.product_id}-${idx}`}><td>{i.product_code||'—'}</td><td>{i.sku||'—'}</td><td>{i.name}</td><td>{i.quantity} {i.unit}</td><td>{money(i.unit_price)}</td><td>{money(i.discount)}</td><td><strong>{money(i.quantity*i.unit_price-i.discount)}</strong></td><td><button className="erp-row-action" onClick={()=>setCart(c=>c.filter((_,x)=>x!==idx))}>Remover</button></td></tr>):<tr><td colSpan={8} className="erp-empty">Adicione os produtos desejados pelo cliente.</td></tr>}</tbody></table></div>
    <div className="erp-so-negotiation"><div className="erp-so-values"><label>Desconto geral<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(n(e.target.value))}/></label><label>Acréscimo<input type="number" min="0" step="0.01" value={surcharge} onChange={e=>setSurcharge(n(e.target.value))}/></label><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="total"><span>Total</span><strong>{money(total)}</strong></div></div><div className="erp-so-payment"><div className="erp-so-condition"><button className={condition==='immediate'?'active':''} onClick={()=>setCondition('immediate')}>À vista</button><button className={condition==='term'?'active':''} onClick={()=>setCondition('term')}>Venda a Prazo</button></div>{condition==='immediate'?<label>Forma negociada<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}>{Object.entries(paymentNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>:<><label>Plano de prazo<select value={termId} onChange={e=>applyTerm(e.target.value)}><option value="">Configuração manual</option>{terms.filter(t=>t.active!==false).map(t=><option key={s(t.id)} value={s(t.id)}>{s(t.name)}</option>)}</select></label><div className="erp-so-term"><label>Tipo<select value={termMethod} onChange={e=>setTermMethod(e.target.value as 'boleto'|'crediario')}><option value="crediario">Crediário</option><option value="boleto">Boleto</option></select></label><label>Parcelas<input type="number" min="1" max="60" value={installments} onChange={e=>setInstallments(Math.max(n(e.target.value),1))}/></label><label>1º venc. (dias)<input type="number" min="0" value={firstDue} onChange={e=>setFirstDue(Math.max(n(e.target.value),0))}/></label><label>Intervalo<input type="number" min="1" value={interval} onChange={e=>setInterval(Math.max(n(e.target.value),1))}/></label><label>Taxa %<input type="number" min="0" step="0.01" value={interest} onChange={e=>setInterest(Math.max(n(e.target.value),0))}/></label></div><div className="erp-so-finance-preview">Principal <b>{money(total)}</b> + taxa <b>{money(interestAmount)}</b> = <strong>{money(financedTotal)}</strong> em {installments}x de aprox. {money(financedTotal/Math.max(installments,1))}</div></>}</div></div>
    <label className="erp-so-notes">Observações<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações comerciais, entrega, negociação..."></textarea></label><div className="erp-so-actions"><button className="erp-primary" onClick={save} disabled={saving||!customer||!cart.length}>{saving?'Salvando...':editing?'Atualizar pedido':'Salvar pedido de venda'}</button></div>{message&&<p className="erp-message">{message}</p>}</section>

    <section className="erp-module-card erp-so-list"><div className="erp-so-head"><div><small>PEDIDOS</small><h2>Pedidos de venda</h2></div><div className="erp-so-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Número ou cliente"/><button className="erp-ghost" onClick={()=>refresh()}>Buscar</button></div></div><div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Nº</th><th>Cliente</th><th>Vendedor</th><th>Negociação</th><th>Itens</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={s(o.id)}><td><strong>#{s(o.number)}</strong></td><td>{s(o.customer_name)}</td><td>{s(o.seller_name)||'—'}</td><td>{s(o.payment_condition)==='term'?`${s(o.term_method)==='boleto'?'Boleto':'Crediário'} · ${s(o.installments||1)}x`:paymentNames[s(o.payment_method)]||'À vista'}</td><td>{s(o.item_count)}</td><td>{money(o.total)}</td><td><span className={`erp-so-status ${s(o.status)}`}>{s(o.status)==='open'?'Aberto':s(o.status)==='converted'?'Convertido':'Cancelado'}</span></td><td><div className="erp-so-row-actions"><button onClick={()=>loadOrder(s(o.id))} disabled={s(o.status)!=='open'}>Editar</button><button onClick={()=>cancel(s(o.id))} disabled={s(o.status)!=='open'}>Cancelar</button></div></td></tr>):<tr><td colSpan={8} className="erp-empty">Nenhum pedido de venda encontrado.</td></tr>}</tbody></table></div></section>

    <section className="erp-module-card erp-so-terms"><div className="erp-so-head"><div><small>VENDA A PRAZO</small><h2>Planos de Boleto / Crediário</h2><p>Configure quantidade de parcelas, primeiro vencimento, intervalo e taxa. Esses planos são sincronizados com o ThorPDV.</p></div></div><div className="erp-so-plan-form"><label>Nome<input value={planName} onChange={e=>setPlanName(e.target.value)} placeholder="Ex.: Crediário 3x 30/60/90"/></label><label>Tipo<select value={planMethod} onChange={e=>setPlanMethod(e.target.value as 'boleto'|'crediario')}><option value="crediario">Crediário</option><option value="boleto">Boleto</option></select></label><label>Parcelas<input type="number" min="1" max="60" value={planInstallments} onChange={e=>setPlanInstallments(Math.max(n(e.target.value),1))}/></label><label>1º venc. dias<input type="number" min="0" value={planFirst} onChange={e=>setPlanFirst(Math.max(n(e.target.value),0))}/></label><label>Intervalo dias<input type="number" min="1" value={planInterval} onChange={e=>setPlanInterval(Math.max(n(e.target.value),1))}/></label><label>Taxa %<input type="number" min="0" step="0.01" value={planInterest} onChange={e=>setPlanInterest(Math.max(n(e.target.value),0))}/></label><button className="erp-primary" onClick={savePlan}>Adicionar plano</button></div><div className="erp-so-plan-list">{terms.map(t=><div key={s(t.id)}><b>{s(t.name)}</b><span>{s(t.method)==='boleto'?'Boleto':'Crediário'} · {s(t.installments)}x · 1º em {s(t.first_due_days)} dias · intervalo {s(t.interval_days)} dias · taxa {Number(t.interest_percent||0).toLocaleString('pt-BR')}%</span></div>)}</div></section>
  </div>;
}
