'use client';

import { useEffect, useMemo, useState } from 'react';
import { erpCreateSale, erpSaleCatalog } from './actions';

type Row=Record<string,unknown>;
type CartItem={product_id:string;name:string;sku:string;unit:string;quantity:number;price:number;discount:number;stock:number};
const money=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
const num=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};

export function SaleWorkspaceV070({customers,priceTables,terms}:{customers:Row[];priceTables:Row[];terms:Row[]}){
  const [tableId,setTableId]=useState('');const [catalog,setCatalog]=useState<Row[]>([]);const [resolvedTable,setResolvedTable]=useState('');const [customer,setCustomer]=useState('');const [product,setProduct]=useState('');const [qty,setQty]=useState(1);const [itemDiscount,setItemDiscount]=useState(0);const [cart,setCart]=useState<CartItem[]>([]);const [saleDiscount,setSaleDiscount]=useState(0);const [condition,setCondition]=useState<'immediate'|'term'>('immediate');const [method,setMethod]=useState('pix');const [entryMethod,setEntryMethod]=useState('pix');const [entryAmount,setEntryAmount]=useState(0);const [termId,setTermId]=useState('');const [termMethod,setTermMethod]=useState<'boleto'|'crediario'>('crediario');const [installments,setInstallments]=useState(1);const [firstDue,setFirstDue]=useState(30);const [interval,setInterval]=useState(30);const [interest,setInterest]=useState(0);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
  async function loadCatalog(id=tableId){const r=await erpSaleCatalog(id||undefined);if(r.ok){setCatalog(r.data);setResolvedTable(String(r.price_table_id??''));}else setMessage(String(r.error??'Falha ao carregar catálogo'));}
  useEffect(()=>{void loadCatalog(tableId);},[tableId]);
  const subtotal=useMemo(()=>cart.reduce((s,i)=>s+(i.quantity*i.price-i.discount),0),[cart]);const total=Math.max(subtotal-saleDiscount,0);const remaining=Math.max(total-entryAmount,0);const interestAmount=condition==='term'?remaining*interest/100:0;const financed=remaining+interestAmount;
  function applyTerm(id:string){setTermId(id);const t=terms.find(x=>String(x.id)===id);if(!t)return;setTermMethod(String(t.method)==='boleto'?'boleto':'crediario');setInstallments(Math.max(num(t.installments),1));setFirstDue(Math.max(num(t.first_due_days),0));setInterval(Math.max(num(t.interval_days),1));setInterest(Math.max(num(t.interest_percent),0));}
  function add(){const p=catalog.find(x=>String(x.id)===product);if(!p)return;const available=num(p.stock);if(qty<=0){setMessage('Quantidade inválida.');return;}if(qty>available){setMessage(`Estoque insuficiente. Disponível: ${available}.`);return;}const price=num(p.effective_price);if(itemDiscount>qty*price){setMessage('Desconto do item maior que o valor do item.');return;}setCart(c=>[...c,{product_id:String(p.id),name:String(p.name),sku:String(p.sku??''),unit:String(p.unit??'UN'),quantity:qty,price,discount:itemDiscount,stock:available}]);setProduct('');setQty(1);setItemDiscount(0);setMessage('');}
  async function finish(){if(!cart.length)return;if(saleDiscount>subtotal){setMessage('Desconto da venda maior que o subtotal.');return;}if(condition==='term'&&!customer){setMessage('Venda a prazo exige cliente identificado.');return;}if(condition==='term'&&remaining<=0.009){setMessage('Não há saldo para financiar. Reduza a entrada ou use venda à vista.');return;}setSaving(true);const payments=condition==='immediate'?[{method,amount:total}]:(entryAmount>0?[{method:entryMethod,amount:entryAmount}]:[]);const term=condition==='term'?{payment_term_id:termId||null,method:termMethod,installments,first_due_days:firstDue,interval_days:interval,interest_percent:interest}:null;const r=await erpCreateSale({customer_id:customer||null,price_table_id:tableId||resolvedTable||null,channel:'pdv',discount:saleDiscount,items:cart.map(i=>({product_id:i.product_id,quantity:i.quantity,discount:i.discount})),payments,term});setSaving(false);if(r.ok){const termInfo=r.term as Row|undefined;setMessage(condition==='term'?`Venda nº ${String(r.number)} concluída. ${String(termInfo?.installments??installments)} parcela(s) de ${termMethod==='boleto'?'Boleto':'Crediário'} foram enviadas para Contas a Receber.`:`Venda nº ${String(r.number)} concluída e quitada por ${money(r.total)}. Nenhum título foi criado em Contas a Receber.`);setCart([]);setSaleDiscount(0);setEntryAmount(0);await loadCatalog();}else setMessage(`Não foi possível finalizar: ${String(r.error??'erro')}`);}
  const paymentOptions=<><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit_card">Cartão de crédito</option><option value="debit_card">Cartão de débito</option><option value="voucher">Voucher</option><option value="store_credit">Crédito da loja</option><option value="other">Outro</option></>;
  return <div className="erp-sale-workspace"><section className="erp-module-card erp-sale-catalog"><div className="erp-sale-settings"><label>Tabela de preços<select value={tableId} onChange={e=>{setTableId(e.target.value);setCart([]);}}><option value="">Tabela padrão vigente</option>{priceTables.filter(t=>t.active!==false).map(t=><option key={String(t.id)} value={String(t.id)}>{String(t.name)}</option>)}</select></label><label>Cliente {condition==='term'&&<b>— obrigatório para prazo</b>}<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Consumidor não identificado</option>{customers.filter(c=>c.active!==false).map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.name)}</option>)}</select></label></div><div className="erp-sale-add"><label>Produto<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Selecione um produto...</option>{catalog.filter(p=>num(p.stock)>0).map(p=><option key={String(p.id)} value={String(p.id)}>Cód. {String(p.product_code??'—')} · {String(p.name)} · {money(p.effective_price)} · estoque {String(p.stock)} {String(p.unit??'UN')}</option>)}</select></label><label>Qtd.<input type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(num(e.target.value))}/></label><label>Desc. item<input type="number" min="0" step="0.01" value={itemDiscount} onChange={e=>setItemDiscount(num(e.target.value))}/></label><button className="erp-primary" type="button" onClick={add} disabled={!product}>Adicionar</button></div></section>
    <section className="erp-module-card"><div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Referência</th><th>Produto</th><th>Qtd./Un.</th><th>Preço servidor</th><th>Desconto</th><th>Total</th><th></th></tr></thead><tbody>{cart.length===0?<tr><td className="erp-empty" colSpan={7}>Adicione produtos para iniciar a venda.</td></tr>:cart.map((i,n)=><tr key={`${i.product_id}-${n}`}><td>{i.sku||'—'}</td><td>{i.name}</td><td>{i.quantity} {i.unit}</td><td>{money(i.price)}</td><td>{money(i.discount)}</td><td><strong>{money(i.quantity*i.price-i.discount)}</strong></td><td><button className="erp-row-action" onClick={()=>setCart(c=>c.filter((_,x)=>x!==n))}>Remover</button></td></tr>)}</tbody></table></div>
      <div className="erp-sale-checkout"><div className="erp-sale-values"><label>Desconto geral<input type="number" min="0" step="0.01" value={saleDiscount} onChange={e=>setSaleDiscount(num(e.target.value))}/></label><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="total"><span>Total</span><strong>{money(total)}</strong></div></div><div className="erp-sale-payment"><div className="erp-so-condition"><button className={condition==='immediate'?'active':''} onClick={()=>{setCondition('immediate');setEntryAmount(0)}}>À vista</button><button className={condition==='term'?'active':''} onClick={()=>setCondition('term')}>Venda a Prazo</button></div>{condition==='immediate'?<label>Forma de pagamento<select value={method} onChange={e=>setMethod(e.target.value)}>{paymentOptions}</select></label>:<><label>Plano<select value={termId} onChange={e=>applyTerm(e.target.value)}><option value="">Configuração manual</option>{terms.filter(t=>t.active!==false).map(t=><option key={String(t.id)} value={String(t.id)}>{String(t.name)}</option>)}</select></label><div className="erp-so-term"><label>Tipo<select value={termMethod} onChange={e=>setTermMethod(e.target.value as 'boleto'|'crediario')}><option value="crediario">Crediário</option><option value="boleto">Boleto</option></select></label><label>Parcelas<input type="number" min="1" max="60" value={installments} onChange={e=>setInstallments(Math.max(num(e.target.value),1))}/></label><label>1º venc. dias<input type="number" min="0" value={firstDue} onChange={e=>setFirstDue(Math.max(num(e.target.value),0))}/></label><label>Intervalo<input type="number" min="1" value={interval} onChange={e=>setInterval(Math.max(num(e.target.value),1))}/></label><label>Taxa %<input type="number" min="0" step="0.01" value={interest} onChange={e=>setInterest(Math.max(num(e.target.value),0))}/></label></div><div className="erp-so-grid"><label>Entrada agora<input type="number" min="0" max={total} step="0.01" value={entryAmount} onChange={e=>setEntryAmount(Math.min(Math.max(num(e.target.value),0),total))}/></label><label>Forma da entrada<select value={entryMethod} onChange={e=>setEntryMethod(e.target.value)}>{paymentOptions}</select></label></div><div className="erp-so-finance-preview">Saldo {money(remaining)} + taxa {money(interestAmount)} = <strong>{money(financed)}</strong> em {installments}x de aprox. {money(financed/Math.max(installments,1))}. Somente esse saldo irá para Contas a Receber.</div></>}<button className="erp-primary erp-finish-sale" disabled={!cart.length||saving||(condition==='term'&&!customer)} onClick={finish}>{saving?'Finalizando...':'Finalizar venda'}</button></div></div>{message&&<p className="erp-message">{message}</p>}
    </section>
  </div>;
}
