'use client';

import { FormEvent, useMemo, useState } from 'react';
import { erpSave } from './actions';
import { ListPagination,useListPagination } from './list-pagination';

type Row=Record<string,unknown>;
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR'):'—';
const cash=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
const num=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};

export function StockWorkspace({products,history,locations=[],balances=[],mode='all'}:{products:Row[];history:Row[];locations?:Row[];balances?:Row[];mode?:'all'|'adjustment'}){
 const defaultLocation=String(locations.find(l=>l.is_default&&l.active!==false)?.id??locations.find(l=>l.active!==false)?.id??'');
 const [locationId,setLocationId]=useState(defaultLocation);const [product,setProduct]=useState('');const [type,setType]=useState(mode==='adjustment'?'adjustment':'in');const [qty,setQty]=useState(1);const [cost,setCost]=useState(0);const [notes,setNotes]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 const rows=mode==='adjustment'?history.filter(r=>r.movement_type==='adjustment'):history;
 const pager=useListPagination(rows);
 const localBalances=useMemo(()=>new Map(balances.filter(b=>!locationId||String(b.stock_location_id)===locationId).map(b=>[String(b.product_id),num(b.available)])),[balances,locationId]);
 const activeLocations=locations.filter(l=>l.active!==false);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);const r=await erpSave('stock',{product_id:product,stock_location_id:locationId||null,movement_type:mode==='adjustment'?'adjustment':type,quantity:qty,unit_cost:cost||null,notes});setSaving(false);if(r.ok){setMessage('Movimentação registrada e saldo do local atualizado.');window.location.reload();}else setMessage(`Não foi possível registrar: ${String(r.error??'erro')}`);}
 return <section className="erp-module-card"><div className="erp-advanced-head"><h2>{mode==='adjustment'?'Ajuste de estoque':'Movimentações de estoque'}</h2><p>Entradas, saídas, perdas e ajustes atualizam o saldo da filial e também o Local de Estoque selecionado.</p></div><form className="erp-form-grid erp-advanced-form" onSubmit={submit}>{activeLocations.length>0&&<label>Local de Estoque<select required value={locationId} onChange={e=>{setLocationId(e.target.value);setProduct('');}}>{activeLocations.map(l=><option key={String(l.id)} value={String(l.id)}>{String(l.name)} — {String(l.branch_name??'')}</option>)}</select></label>}<label>Produto<select required value={product} onChange={e=>setProduct(e.target.value)}><option value="">Selecione...</option>{products.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)} — saldo local {activeLocations.length?String(localBalances.get(String(p.id))??0):String(p.stock??0)}</option>)}</select></label>{mode!=='adjustment'&&<label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="in">Entrada</option><option value="out">Saída</option><option value="loss">Perda</option><option value="adjustment">Ajuste</option></select></label>}<label>Quantidade {mode==='adjustment'?'(+ ou -)':''}<input required type="number" step="0.001" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Custo unitário<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label className="wide">Motivo / documento<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="NF de entrada, perda, acerto..."/></label><button className="erp-primary" disabled={saving}>{saving?'Salvando...':'Registrar movimentação'}</button></form>{message&&<p className="erp-message">{message}</p>}<div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Data</th><th>Produto</th><th>Código</th><th>Tipo</th><th>Quantidade</th><th>Custo</th><th>Local Estoque</th><th>Filial</th><th>Observação</th></tr></thead><tbody>{rows.length===0?<tr><td className="erp-empty" colSpan={9}>Nenhuma movimentação registrada.</td></tr>:pager.pageRows.map((r,i)=><tr key={String(r.id??`${pager.page}-${i}`)}><td>{dt(r.created_at)}</td><td>{String(r.product??'')}</td><td>{String(r.product_code??r.sku??'—')}</td><td><span className="erp-pill">{String(r.movement_type)}</span></td><td>{String(r.quantity??0)}</td><td>{r.unit_cost?cash(r.unit_cost):'—'}</td><td>{String(r.stock_location??'Matriz')}</td><td>{String(r.branch??'')}</td><td>{String(r.notes??'—')}</td></tr>)}</tbody></table></div><ListPagination page={pager.page} pageCount={pager.pageCount} total={pager.total} from={pager.from} to={pager.to} onPage={pager.setPage} label="movimentação(ões)"/></section>;
}
