export type StudioFormat='money'|'number'|'percent'|'date'|'datetime'|'text';
export type StudioField={key:string;label:string;format?:StudioFormat};
export type StudioSource={id:string;title:string;group:string;period:boolean;dimensions:StudioField[];metrics:StudioField[]};

export const studioSources:StudioSource[]=[
 {id:'product_ranking',title:'Ranking de Produtos',group:'Comercial',period:true,dimensions:[{key:'product',label:'Produto'},{key:'sku',label:'Código'}],metrics:[{key:'quantity',label:'Quantidade',format:'number'},{key:'sales_count',label:'Vendas',format:'number'},{key:'avg_unit_price',label:'Preço médio',format:'money'},{key:'revenue',label:'Faturamento',format:'money'}]},
 {id:'product_payment',title:'Produtos × Forma de Pagamento',group:'Comercial',period:true,dimensions:[{key:'product',label:'Produto'},{key:'payment_method',label:'Forma de pagamento'},{key:'sku',label:'Código'}],metrics:[{key:'sales_count',label:'Vendas',format:'number'},{key:'allocated_quantity',label:'Quantidade rateada',format:'number'},{key:'allocated_amount',label:'Valor rateado',format:'money'}]},
 {id:'sellers',title:'Vendedores / Operadores',group:'Comercial',period:true,dimensions:[{key:'seller',label:'Vendedor / Operador'},{key:'branch',label:'Filial'}],metrics:[{key:'sales_count',label:'Vendas',format:'number'},{key:'item_quantity',label:'Itens',format:'number'},{key:'revenue',label:'Faturamento',format:'money'},{key:'avg_ticket',label:'Ticket médio',format:'money'},{key:'discounts',label:'Descontos',format:'money'},{key:'surcharges',label:'Acréscimos',format:'money'}]},
 {id:'payment_methods',title:'Formas de Pagamento',group:'Caixa',period:true,dimensions:[{key:'payment_method',label:'Forma de pagamento'},{key:'status',label:'Status'}],metrics:[{key:'transactions',label:'Transações',format:'number'},{key:'sales_count',label:'Vendas',format:'number'},{key:'amount',label:'Valor aplicado',format:'money'},{key:'tendered_amount',label:'Valor entregue',format:'money'},{key:'change_amount',label:'Troco',format:'money'}]},
 {id:'cash_closures',title:'Fechamentos de Caixa',group:'Caixa',period:true,dimensions:[{key:'branch',label:'Filial'},{key:'pos',label:'PDV'},{key:'operator',label:'Operador'}],metrics:[{key:'sales_count',label:'Vendas',format:'number'},{key:'sales_total',label:'Vendas R$',format:'money'},{key:'cash_payments',label:'Dinheiro',format:'money'},{key:'supply',label:'Suprimento',format:'money'},{key:'withdrawal',label:'Sangria',format:'money'},{key:'difference',label:'Diferença',format:'money'}]},
 {id:'cash_flow',title:'Fluxo de Caixa',group:'Financeiro',period:true,dimensions:[{key:'report_day',label:'Data',format:'date'}],metrics:[{key:'inflow_realized',label:'Entradas realizadas',format:'money'},{key:'outflow_realized',label:'Saídas realizadas',format:'money'},{key:'realized_balance',label:'Saldo realizado',format:'money'},{key:'inflow_forecast',label:'Entradas previstas',format:'money'},{key:'outflow_forecast',label:'Saídas previstas',format:'money'},{key:'forecast_balance',label:'Saldo previsto',format:'money'}]},
 {id:'receivables',title:'Contas a Receber',group:'Financeiro',period:true,dimensions:[{key:'customer',label:'Cliente'},{key:'branch',label:'Filial'},{key:'status',label:'Status'},{key:'due_date',label:'Vencimento',format:'date'}],metrics:[{key:'amount',label:'Valor',format:'money'},{key:'paid_amount',label:'Recebido',format:'money'},{key:'open_amount',label:'Em aberto',format:'money'}]},
 {id:'payables',title:'Contas a Pagar',group:'Financeiro',period:true,dimensions:[{key:'supplier',label:'Fornecedor'},{key:'branch',label:'Filial'},{key:'status',label:'Status'},{key:'due_date',label:'Vencimento',format:'date'}],metrics:[{key:'amount',label:'Valor',format:'money'},{key:'paid_amount',label:'Pago',format:'money'},{key:'open_amount',label:'Em aberto',format:'money'}]},
 {id:'gross_profit',title:'Lucro Bruto por Período',group:'Rentabilidade',period:true,dimensions:[{key:'report_day',label:'Data',format:'date'}],metrics:[{key:'net_revenue',label:'Receita líquida',format:'money'},{key:'cmv',label:'CMV',format:'money'},{key:'gross_profit',label:'Lucro bruto',format:'money'},{key:'margin_percent',label:'Margem bruta',format:'percent'}]},
 {id:'cmv',title:'CMV',group:'Rentabilidade',period:true,dimensions:[{key:'report_day',label:'Data',format:'date'}],metrics:[{key:'quantity',label:'Quantidade líquida',format:'number'},{key:'revenue',label:'Receita',format:'money'},{key:'cmv',label:'CMV',format:'money'},{key:'gross_profit',label:'Lucro bruto',format:'money'},{key:'cmv_percent',label:'CMV / Receita',format:'percent'}]},
 {id:'product_margin',title:'Margem por Produto',group:'Rentabilidade',period:true,dimensions:[{key:'product',label:'Produto'},{key:'sku',label:'Código'}],metrics:[{key:'quantity',label:'Quantidade líquida',format:'number'},{key:'revenue',label:'Receita líquida',format:'money'},{key:'cmv',label:'CMV',format:'money'},{key:'gross_profit',label:'Lucro bruto',format:'money'},{key:'margin_percent',label:'Margem',format:'percent'}]},
 {id:'abc_curve',title:'Curva ABC',group:'Rentabilidade',period:true,dimensions:[{key:'abc_class',label:'Classe ABC'},{key:'product',label:'Produto'},{key:'sku',label:'Código'}],metrics:[{key:'quantity',label:'Quantidade',format:'number'},{key:'revenue',label:'Faturamento',format:'money'},{key:'revenue_share',label:'Participação',format:'percent'},{key:'cumulative_share',label:'Acumulado',format:'percent'}]},
 {id:'sales_timing',title:'Vendas por Hora / Dia',group:'Comercial',period:true,dimensions:[{key:'weekday',label:'Dia da semana'},{key:'hour_of_day',label:'Hora',format:'number'}],metrics:[{key:'sales_count',label:'Vendas',format:'number'},{key:'revenue',label:'Faturamento',format:'money'},{key:'avg_ticket',label:'Ticket médio',format:'money'}]},
 {id:'average_ticket',title:'Ticket Médio',group:'Comercial',period:true,dimensions:[{key:'report_day',label:'Data',format:'date'},{key:'branch',label:'Filial'}],metrics:[{key:'sales_count',label:'Vendas',format:'number'},{key:'item_quantity',label:'Itens',format:'number'},{key:'revenue',label:'Faturamento',format:'money'},{key:'avg_ticket',label:'Ticket médio',format:'money'}]},
 {id:'seller_commission',title:'Comissão por Vendedor',group:'Comercial',period:true,dimensions:[{key:'seller',label:'Vendedor'},{key:'branch',label:'Filial'}],metrics:[{key:'gross_revenue',label:'Receita bruta',format:'money'},{key:'net_revenue',label:'Receita líquida',format:'money'},{key:'commission_percent',label:'Percentual',format:'percent'},{key:'commission_amount',label:'Comissão',format:'money'}]},
 {id:'sales_cfop',title:'Vendas por CFOP',group:'Fiscal',period:true,dimensions:[{key:'cfop',label:'CFOP'}],metrics:[{key:'sales_count',label:'Vendas',format:'number'},{key:'quantity',label:'Quantidade',format:'number'},{key:'revenue',label:'Faturamento',format:'money'}]},
 {id:'stock_position',title:'Posição de Estoque',group:'Estoque',period:false,dimensions:[{key:'branch',label:'Filial'},{key:'product',label:'Produto'},{key:'stock_status',label:'Situação'},{key:'sku',label:'Código'}],metrics:[{key:'physical_stock',label:'Estoque físico',format:'number'},{key:'reserved_stock',label:'Reservado',format:'number'},{key:'available_stock',label:'Disponível',format:'number'},{key:'minimum_stock',label:'Mínimo',format:'number'},{key:'stock_value',label:'Valor em estoque',format:'money'}]},
 {id:'stock_movements',title:'Movimentações de Estoque',group:'Estoque',period:true,dimensions:[{key:'branch',label:'Filial'},{key:'product',label:'Produto'},{key:'movement_type',label:'Movimento'},{key:'sku',label:'Código'}],metrics:[{key:'quantity',label:'Quantidade',format:'number'},{key:'unit_cost',label:'Custo unitário',format:'money'}]},
 {id:'stagnant_stock',title:'Estoque Parado',group:'Estoque',period:true,dimensions:[{key:'branch',label:'Filial'},{key:'product',label:'Produto'},{key:'sku',label:'Código'}],metrics:[{key:'stock_quantity',label:'Quantidade',format:'number'},{key:'stock_value',label:'Valor parado',format:'money'},{key:'days_without_sale',label:'Dias sem venda',format:'number'}]},
 {id:'no_movement_products',title:'Produtos sem Giro',group:'Estoque',period:true,dimensions:[{key:'branch',label:'Filial'},{key:'product',label:'Produto'},{key:'sku',label:'Código'}],metrics:[{key:'stock_quantity',label:'Quantidade',format:'number'},{key:'stock_value',label:'Valor em estoque',format:'money'},{key:'days_without_sale',label:'Dias sem venda',format:'number'}]},
];

export const studioSourceMap=Object.fromEntries(studioSources.map(s=>[s.id,s])) as Record<string,StudioSource>;
export const studioAllowedReports=studioSources.map(s=>s.id);
