'use client';

export type Format='money'|'number'|'percent';
export type ChartType='kpi'|'bar'|'column'|'line'|'area'|'donut'|'pie'|'table'|'gauge'|'radial'|'funnel'|'treemap'|'heatmap'|'waterfall'|'combo'|'scatter'|'radar'|'spark';
export type Point={label:string;value:number;detail?:string;format?:Format};

const money=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
const number=(v:unknown)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(Number(v??0));
const percent=(v:unknown)=>`${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(Number(v??0))}%`;
const fmt=(v:number,format:Format='money')=>format==='money'?money(v):format==='percent'?percent(v):number(v);
const palette=['#22c55e','#f59e0b','#ec4899','#8b5cf6','#06b6d4','#ef4444','#64748b','#14b8a6','#f97316','#3b82f6','#a855f7'];
const colorAt=(base:string,index:number)=>index===0?base:palette[(index-1)%palette.length];
const rgba=(hex:string,alpha:number)=>{const clean=hex.replace('#','');const full=clean.length===3?clean.split('').map(x=>x+x).join(''):clean;const num=parseInt(full,16);if(!Number.isFinite(num))return `rgba(109,40,217,${alpha})`;return `rgba(${(num>>16)&255},${(num>>8)&255},${num&255},${alpha})`};
const display=(p:Point)=>p.detail??fmt(p.value,p.format);

function Empty(){return <div className="bi-empty">Sem dados para este período.</div>}
function Kpi({points,color}:{points:Point[];color:string}){if(!points.length)return <Empty/>;const total=points.reduce((s,p)=>s+p.value,0);return <div className="bi-kpi"><div className="bi-kpi-accent" style={{background:color}}/><strong>{fmt(total,points[0]?.format)}</strong><p>{points.length>1?`${points.length} pontos consolidados`:points[0]?.detail??points[0]?.label}</p></div>}
function Bar({points,color}:{points:Point[];color:string}){const list=points.slice(0,14),max=Math.max(1,...list.map(p=>Math.abs(p.value)));if(!list.length)return <Empty/>;return <div className="bi-bars">{list.map((p,i)=><div className="bi-bar" key={`${p.label}-${i}`}><div><span>{p.label}</span><b>{display(p)}</b></div><div className="bi-track"><i style={{width:`${Math.max(2,Math.abs(p.value)/max*100)}%`,background:colorAt(color,i)}}/></div></div>)}</div>}
function Columns({points,color}:{points:Point[];color:string}){const list=points.slice(-18),max=Math.max(1,...list.map(p=>Math.abs(p.value)));if(!list.length)return <Empty/>;return <div className="bi-columns">{list.map((p,i)=><div key={`${p.label}-${i}`} className="bi-col" title={`${p.label} · ${display(p)}`}><div><i style={{height:`${Math.max(3,Math.abs(p.value)/max*100)}%`,background:colorAt(color,i)}}/></div><span>{p.label}</span></div>)}</div>}
function Line({points,color,area=false,spark=false}:{points:Point[];color:string;area?:boolean;spark?:boolean}){if(!points.length)return <Empty/>;const values=points.map(p=>p.value),min=Math.min(0,...values),max=Math.max(1,...values),range=Math.max(1,max-min),w=700,h=spark?90:245,pad=spark?8:22;const coords=values.map((v,i)=>[points.length===1?w/2:pad+i*(w-pad*2)/(points.length-1),h-pad-(v-min)/range*(h-pad*2)] as const),poly=coords.map(([x,y])=>`${x},${y}`).join(' '),gid=`bi-${color.replace('#','')}-${points.length}-${spark?'s':'n'}`;const fill=coords.length?`M ${coords[0][0]} ${h-pad} L ${coords.map(([x,y])=>`${x} ${y}`).join(' L ')} L ${coords[coords.length-1][0]} ${h-pad} Z`:'';return <div className={`bi-line ${spark?'spark':''}`}><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><defs><linearGradient id={gid} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".3"/><stop offset="1" stopColor={color} stopOpacity=".02"/></linearGradient></defs>{!spark&&[.25,.5,.75,1].map(k=><line key={k} x1={pad} x2={w-pad} y1={h-pad-(h-pad*2)*k} y2={h-pad-(h-pad*2)*k} className="bi-grid-line"/>)}{area?<path d={fill} fill={`url(#${gid})`}/>:null}<polyline points={poly} fill="none" stroke={color} strokeWidth={spark?5:4} strokeLinecap="round" strokeLinejoin="round"/></svg>{!spark?<div className="bi-axis"><span>{points[0]?.label}</span><span>{points[Math.floor(points.length/2)]?.label}</span><span>{points[points.length-1]?.label}</span></div>:null}</div>}
function Circle({points,color,pie=false}:{points:Point[];color:string;pie?:boolean}){const list=points.filter(p=>p.value>0).slice(0,10),total=list.reduce((s,p)=>s+p.value,0);if(!total)return <Empty/>;const stops=list.map((p,i)=>{const start=list.slice(0,i).reduce((s,x)=>s+x.value,0)/total*100,end=start+p.value/total*100;return `${colorAt(color,i)} ${start}% ${end}%`}).join(',');return <div className="bi-circle-layout"><div className={`bi-donut ${pie?'pie':''}`} style={{background:`conic-gradient(${stops})`}}>{!pie?<div><b>{fmt(total,list[0]?.format)}</b><span>Total</span></div>:null}</div><div className="bi-legend">{list.map((p,i)=><div key={`${p.label}-${i}`}><i style={{background:colorAt(color,i)}}/><span>{p.label}</span><b>{display(p)}</b></div>)}</div></div>}
function Table({points}:{points:Point[]}){if(!points.length)return <Empty/>;return <div className="bi-table">{points.slice(0,16).map((p,i)=><div key={`${p.label}-${i}`}><span>{p.label}</span><b>{display(p)}</b></div>)}</div>}
function Gauge({points,color,radial=false}:{points:Point[];color:string;radial?:boolean}){if(!points.length)return <Empty/>;const value=points.reduce((s,p)=>s+p.value,0),max=Math.max(1,...points.map(p=>Math.abs(p.value)))*Math.max(1,points.length),pctv=Math.min(100,Math.abs(value)/max*100);return <div className={radial?'bi-radial':'bi-gauge'}><div style={{background:`conic-gradient(${color} 0 ${pctv}%,var(--bi-track) ${pctv}% 100%)`}}><span><b>{fmt(value,points[0]?.format)}</b><small>{radial?'Consolidado':'Indicador'}</small></span></div></div>}
function Funnel({points,color}:{points:Point[];color:string}){const list=[...points].sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,9),max=Math.max(1,...list.map(p=>Math.abs(p.value)));if(!list.length)return <Empty/>;return <div className="bi-funnel">{list.map((p,i)=><div key={p.label} style={{width:`${35+Math.abs(p.value)/max*65}%`,background:rgba(color,.1+i*.035),borderColor:rgba(color,.25)}}><span>{p.label}</span><b>{display(p)}</b></div>)}</div>}
function Treemap({points,color}:{points:Point[];color:string}){const list=points.slice(0,14),sum=list.reduce((s,p)=>s+Math.abs(p.value),0);if(!sum)return <Empty/>;return <div className="bi-treemap">{list.map((p,i)=><div key={p.label} style={{flexGrow:Math.max(.3,Math.abs(p.value)/sum*10),background:rgba(colorAt(color,i),.12),borderColor:rgba(colorAt(color,i),.28)}}><span>{p.label}</span><b>{display(p)}</b></div>)}</div>}
function Heatmap({points,color}:{points:Point[];color:string}){const list=points.slice(0,28),max=Math.max(1,...list.map(p=>Math.abs(p.value)));if(!list.length)return <Empty/>;return <div className="bi-heatmap">{list.map(p=><div key={p.label} style={{background:rgba(color,.08+.7*Math.abs(p.value)/max)}}><span>{p.label}</span><b>{display(p)}</b></div>)}</div>}
function Waterfall({points,color}:{points:Point[];color:string}){const list=points.slice(0,12);if(!list.length)return <Empty/>;const vals=list.map((p,i)=>{const before=list.slice(0,i).reduce((s,x)=>s+x.value,0),after=before+p.value;return {...p,before,after}}),min=Math.min(0,...vals.flatMap(v=>[v.before,v.after])),max=Math.max(1,...vals.flatMap(v=>[v.before,v.after])),range=Math.max(1,max-min);return <div className="bi-waterfall">{vals.map(v=>{const bottom=(Math.min(v.before,v.after)-min)/range*100,height=Math.max(2,Math.abs(v.value)/range*100);return <div key={v.label}><div><i style={{bottom:`${bottom}%`,height:`${height}%`,background:v.value>=0?color:'#dc2626'}}/></div><span>{v.label}</span></div>})}</div>}
function Scatter({points,color}:{points:Point[];color:string}){const list=points.slice(0,20);if(!list.length)return <Empty/>;const max=Math.max(1,...list.map(p=>Math.abs(p.value)));return <div className="bi-scatter"><svg viewBox="0 0 660 235">{list.map((p,i)=><g key={`${p.label}-${i}`}><circle cx={32+(i+1)/(list.length+1)*590} cy={205-Math.abs(p.value)/max*170} r="7" fill={colorAt(color,i)} opacity=".82"/><title>{`${p.label}: ${display(p)}`}</title></g>)}</svg></div>}
function Radar({points,color}:{points:Point[];color:string}){const list=points.slice(0,8);if(list.length<3)return <Bar points={points} color={color}/>;const max=Math.max(1,...list.map(p=>Math.abs(p.value))),cx=160,cy=145,r=100,poly=list.map((p,i)=>{const a=-Math.PI/2+i*2*Math.PI/list.length,rr=Math.abs(p.value)/max*r;return `${cx+Math.cos(a)*rr},${cy+Math.sin(a)*rr}`}).join(' ');return <div className="bi-radar"><svg viewBox="0 0 320 290">{[.25,.5,.75,1].map(k=><polygon key={k} points={list.map((_,i)=>{const a=-Math.PI/2+i*2*Math.PI/list.length;return `${cx+Math.cos(a)*r*k},${cy+Math.sin(a)*r*k}`}).join(' ')} fill="none" stroke="var(--bi-grid)"/>)}<polygon points={poly} fill={rgba(color,.15)} stroke={color} strokeWidth="2.5"/>{list.map((p,i)=>{const a=-Math.PI/2+i*2*Math.PI/list.length;return <text key={p.label} x={cx+Math.cos(a)*(r+22)} y={cy+Math.sin(a)*(r+22)} textAnchor="middle" fontSize="9" fill="var(--bi-muted)">{p.label.slice(0,14)}</text>})}</svg></div>}

export function Visual({chart,points,color}:{chart:ChartType;points:Point[];color:string}){
 if(chart==='bar')return <Bar points={points} color={color}/>;
 if(chart==='column')return <Columns points={points} color={color}/>;
 if(chart==='line')return <Line points={points} color={color}/>;
 if(chart==='area')return <Line points={points} color={color} area/>;
 if(chart==='spark')return <Line points={points} color={color} spark/>;
 if(chart==='donut')return <Circle points={points} color={color}/>;
 if(chart==='pie')return <Circle points={points} color={color} pie/>;
 if(chart==='table')return <Table points={points}/>;
 if(chart==='gauge')return <Gauge points={points} color={color}/>;
 if(chart==='radial')return <Gauge points={points} color={color} radial/>;
 if(chart==='funnel')return <Funnel points={points} color={color}/>;
 if(chart==='treemap')return <Treemap points={points} color={color}/>;
 if(chart==='heatmap')return <Heatmap points={points} color={color}/>;
 if(chart==='waterfall')return <Waterfall points={points} color={color}/>;
 if(chart==='scatter')return <Scatter points={points} color={color}/>;
 if(chart==='radar')return <Radar points={points} color={color}/>;
 if(chart==='combo')return <div className="bi-combo"><Columns points={points} color={color}/><Line points={points} color="#475569" spark/></div>;
 return <Kpi points={points} color={color}/>;
}
