-- ThorPDV Fiscal v0.7.5
-- Multiple NF-e/NFC-e series, controlled last number, POS-to-NFC-e series mapping,
-- DANFE preferences, encrypted CSC and tenant CFOP catalog.

create table if not exists public.fiscal_series (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  document_type text not null check (document_type in ('nfe','nfce')),
  series integer not null check (series between 1 and 999),
  label text,
  last_number bigint not null default 0 check (last_number between 0 and 999999999),
  is_default boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id,branch_id,document_type,series)
);
create unique index if not exists fiscal_series_one_default_idx on public.fiscal_series(tenant_id,branch_id,document_type) where is_default and active;
create index if not exists fiscal_series_branch_idx on public.fiscal_series(tenant_id,branch_id,document_type,active);
alter table public.fiscal_series enable row level security;
drop policy if exists tenant_access_fiscal_series on public.fiscal_series;
create policy tenant_access_fiscal_series on public.fiscal_series for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));

create table if not exists public.fiscal_pos_series (
  id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,branch_id uuid not null references public.branches(id) on delete cascade,
  pos_register_id uuid not null references public.pos_registers(id) on delete cascade,fiscal_series_id uuid not null references public.fiscal_series(id) on delete cascade,
  cash_number text not null,in_use boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create unique index if not exists fiscal_pos_series_active_pos_idx on public.fiscal_pos_series(tenant_id,pos_register_id) where in_use;
create unique index if not exists fiscal_pos_series_active_series_idx on public.fiscal_pos_series(tenant_id,fiscal_series_id) where in_use;
create unique index if not exists fiscal_pos_series_active_cash_idx on public.fiscal_pos_series(tenant_id,branch_id,cash_number) where in_use;
alter table public.fiscal_pos_series enable row level security;
drop policy if exists tenant_access_fiscal_pos_series on public.fiscal_pos_series;
create policy tenant_access_fiscal_pos_series on public.fiscal_pos_series for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));

create table if not exists public.fiscal_danfe_settings (
  id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,branch_id uuid not null references public.branches(id) on delete cascade,
  unit_decimal_places smallint not null default 2 check (unit_decimal_places between 2 and 6),
  product_name_lines smallint not null default 2 check (product_name_lines between 1 and 5),
  item_order text not null default 'launch' check (item_order in ('alphabetical','launch','internal_code')),
  product_name_format text not null default '{nome}',active boolean not null default true,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,branch_id)
);
alter table public.fiscal_danfe_settings enable row level security;
drop policy if exists tenant_access_fiscal_danfe_settings on public.fiscal_danfe_settings;
create policy tenant_access_fiscal_danfe_settings on public.fiscal_danfe_settings for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));

create table if not exists public.fiscal_cfops (
  id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,
  code text not null check(code~'^[0-9]{4}$'),name text not null,active boolean not null default true,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code)
);
alter table public.fiscal_cfops enable row level security;
drop policy if exists tenant_access_fiscal_cfops on public.fiscal_cfops;
create policy tenant_access_fiscal_cfops on public.fiscal_cfops for all using (public.is_tenant_member(tenant_id)) with check (public.is_tenant_member(tenant_id));

create table if not exists private.fiscal_csc_credentials (
 tenant_id uuid not null references public.tenants(id) on delete cascade,company_id uuid not null references public.companies(id) on delete cascade,
 branch_id uuid not null references public.branches(id) on delete cascade,csc_id text,csc_token_cipher bytea,updated_at timestamptz not null default now(),primary key(tenant_id,branch_id)
);

create or replace function private.ensure_default_cfops(p_tenant uuid) returns void language plpgsql security definer set search_path='public','private','extensions' as $function$
begin
 insert into public.fiscal_cfops(tenant_id,code,name,active) values
 (p_tenant,'1102','Compra para comercialização',true),(p_tenant,'1152','Transferência para comercialização',true),
 (p_tenant,'1202','Devolução de venda de mercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 1.503, 1.504, 1.505 e 1.506.',true),
 (p_tenant,'1403','Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária',true),
 (p_tenant,'1411','Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária',true),
 (p_tenant,'1917','Entrada de mercadoria recebida em consignação mercantil ou industrial',true),(p_tenant,'1926','Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação',true),
 (p_tenant,'1949','Outra entrada de mercadoria ou prestação de serviço não especificada',true),(p_tenant,'2102','Compra para comercialização',true),(p_tenant,'2152','Transferência para comercialização',true),
 (p_tenant,'2201','Devolução de venda de produção do estabelecimento',true),(p_tenant,'2403','Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária',true),
 (p_tenant,'2411','Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária',true),(p_tenant,'3102','Compra para comercialização',true),
 (p_tenant,'5101','Venda de produção do estabelecimento',true),(p_tenant,'5102','Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 5.501, 5.502, 5.504 e 5.505 / 6.501, 6.502, 6.504 e 6.505',true),
 (p_tenant,'5117','Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura',true),(p_tenant,'5152','Transferência de mercadoria adquirida ou recebida de terceiros',true),
 (p_tenant,'5202','Devolução de compra para comercialização, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas no código 5.503 ou 6.503.',true),
 (p_tenant,'5401','Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto',true),
 (p_tenant,'5403','Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituto',true),
 (p_tenant,'5405','Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituído',true),
 (p_tenant,'5655','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização',true),(p_tenant,'5910','Remessa em bonificação, doação ou brinde',true),
 (p_tenant,'5917','Remessa de mercadoria em consignação mercantil ou industrial',true),(p_tenant,'5922','Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura',true),
 (p_tenant,'5926','Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação',true),(p_tenant,'5927','Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração',true),
 (p_tenant,'5929','Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF',true),(p_tenant,'5949','Outra saída de mercadoria ou prestação de serviço não especificado',true),
 (p_tenant,'6102','Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 5.501, 5.502, 5.504 e 5.505 / 6.501, 6.502, 6.504 e 6.505',true),
 (p_tenant,'6107','Venda de produção do estabelecimento, destinada a não contribuinte',true),(p_tenant,'6108','Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte',true),
 (p_tenant,'6152','Transferência de mercadoria adquirida ou recebida de terceiros',true),(p_tenant,'6202','Devolução de compra para comercialização, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas no código 5.503 ou 6.503.',true),
 (p_tenant,'6403','Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto',true),
 (p_tenant,'6404','Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente',true),(p_tenant,'6655','Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização',true),
 (p_tenant,'6929','Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF',true),(p_tenant,'6949','Outra saída de mercadoria ou prestação de serviço não especificado',true),
 (p_tenant,'7102','Venda de mercadoria adquirida ou recebida de terceiros',true)
 on conflict(tenant_id,code) do nothing;
end $function$;

create or replace function private.ensure_fiscal_defaults(p_tenant uuid,p_company uuid,p_branch uuid) returns void language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v_fs public.fiscal_settings%rowtype;v_nfe integer:=1;v_nfce integer:=1;v_last bigint;
begin
 select * into v_fs from public.fiscal_settings where tenant_id=p_tenant;
 if coalesce(v_fs.nfe_series,'')~'^[0-9]+$' then v_nfe:=greatest(1,least(999,v_fs.nfe_series::integer));end if;
 if coalesce(v_fs.nfce_series,'')~'^[0-9]+$' then v_nfce:=greatest(1,least(999,v_fs.nfce_series::integer));end if;
 select coalesce(max(number::bigint),0) into v_last from public.fiscal_documents where tenant_id=p_tenant and branch_id=p_branch and document_type='nfe' and series=v_nfe::text and number~'^[0-9]+$';
 insert into public.fiscal_series(tenant_id,company_id,branch_id,document_type,series,label,last_number,is_default,active) values(p_tenant,p_company,p_branch,'nfe',v_nfe,'NF-e Série '||v_nfe,v_last,not exists(select 1 from public.fiscal_series where tenant_id=p_tenant and branch_id=p_branch and document_type='nfe' and is_default and active),true) on conflict(tenant_id,branch_id,document_type,series) do update set last_number=greatest(public.fiscal_series.last_number,excluded.last_number),updated_at=now();
 select coalesce(max(number::bigint),0) into v_last from public.fiscal_documents where tenant_id=p_tenant and branch_id=p_branch and document_type='nfce' and series=v_nfce::text and number~'^[0-9]+$';
 insert into public.fiscal_series(tenant_id,company_id,branch_id,document_type,series,label,last_number,is_default,active) values(p_tenant,p_company,p_branch,'nfce',v_nfce,'NFC-e Série '||v_nfce,v_last,not exists(select 1 from public.fiscal_series where tenant_id=p_tenant and branch_id=p_branch and document_type='nfce' and is_default and active),true) on conflict(tenant_id,branch_id,document_type,series) do update set last_number=greatest(public.fiscal_series.last_number,excluded.last_number),updated_at=now();
 insert into public.fiscal_danfe_settings(tenant_id,company_id,branch_id) values(p_tenant,p_company,p_branch) on conflict(tenant_id,branch_id) do nothing;
 perform private.ensure_default_cfops(p_tenant);
end $function$;

do $block$ declare r record; begin for r in select tenant_id,company_id,id branch_id from public.branches loop perform private.ensure_fiscal_defaults(r.tenant_id,r.company_id,r.branch_id); end loop; end $block$;

create or replace function public.erp_fiscal_settings_get(p_token text) returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v record;s public.fiscal_settings%rowtype;c record;cs private.fiscal_csc_credentials%rowtype;d public.fiscal_danfe_settings%rowtype;v_series jsonb;v_pos jsonb;v_cfops jsonb;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;
 perform private.ensure_fiscal_defaults(v.tenant_id,v.company_id,v.branch_id);select * into s from public.fiscal_settings where tenant_id=v.tenant_id;select * into c from private.fiscal_certificates where tenant_id=v.tenant_id and company_id=v.company_id;select * into cs from private.fiscal_csc_credentials where tenant_id=v.tenant_id and branch_id=v.branch_id;select * into d from public.fiscal_danfe_settings where tenant_id=v.tenant_id and branch_id=v.branch_id;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.document_type,x.series),'[]'::jsonb) into v_series from (select fs.id,fs.document_type,fs.series::text series,fs.label,fs.last_number,(fs.last_number+1) next_number,fs.is_default,fs.active,fs.branch_id,b.name branch,exists(select 1 from public.fiscal_pos_series fps where fps.fiscal_series_id=fs.id and fps.in_use) in_use_by_cash from public.fiscal_series fs join public.branches b on b.id=fs.branch_id where fs.tenant_id=v.tenant_id and fs.branch_id=v.branch_id)x;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.name),'[]'::jsonb) into v_pos from (select p.id,p.name,p.code,p.active,p.branch_id,b.name branch,m.id mapping_id,m.cash_number,m.in_use,m.fiscal_series_id,ser.series::text fiscal_series,ser.label fiscal_series_label from public.pos_registers p join public.branches b on b.id=p.branch_id left join lateral(select fps.* from public.fiscal_pos_series fps where fps.tenant_id=v.tenant_id and fps.pos_register_id=p.id and fps.in_use order by fps.updated_at desc limit 1)m on true left join public.fiscal_series ser on ser.id=m.fiscal_series_id where p.tenant_id=v.tenant_id and p.branch_id=v.branch_id)x;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.code),'[]'::jsonb) into v_cfops from(select id,code,name,active,case when left(code,1) in('1','2','3') then 'entry' else 'exit' end direction from public.fiscal_cfops where tenant_id=v.tenant_id)x;
 return jsonb_build_object('ok',true,'settings',jsonb_build_object('provider','svrs_direct','transport','SVRS direta','environment',coalesce(s.environment,'homologation'),'nfe_series',coalesce((select fs.series::text from public.fiscal_series fs where fs.tenant_id=v.tenant_id and fs.branch_id=v.branch_id and fs.document_type='nfe' and fs.active and fs.is_default limit 1),coalesce(s.nfe_series,'1')),'nfce_series',coalesce((select fs.series::text from public.fiscal_series fs where fs.tenant_id=v.tenant_id and fs.branch_id=v.branch_id and fs.document_type='nfce' and fs.active and fs.is_default limit 1),coalesce(s.nfce_series,'1')),'csc_id',coalesce(cs.csc_id,s.csc_id),'csc_token_configured',cs.csc_token_cipher is not null,'branch_id',v.branch_id,'company_id',v.company_id,'series',v_series,'pos_registers',v_pos,'cfops',v_cfops,'danfe',jsonb_build_object('unit_decimal_places',coalesce(d.unit_decimal_places,2),'product_name_lines',coalesce(d.product_name_lines,2),'item_order',coalesce(d.item_order,'launch'),'product_name_format',coalesce(d.product_name_format,'{nome}'),'active',coalesce(d.active,true)),'configured',c.company_id is not null,'certificate',case when c.company_id is null then null else jsonb_build_object('filename',c.filename,'subject_cn',c.subject_cn,'subject_cnpj',c.subject_cnpj,'serial_number',c.serial_number,'valid_from',c.valid_from,'valid_to',c.valid_to,'fingerprint_sha256',c.fingerprint_sha256,'file_sha256',c.file_sha256,'uploaded_at',c.uploaded_at,'expired',(c.valid_to is not null and c.valid_to<now()))end));
end $function$;

create or replace function public.erp_fiscal_settings_save(p_token text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v record;v_env text:=coalesce(nullif(p_payload->>'environment',''),'homologation');v_csc_id text:=nullif(trim(p_payload->>'csc_id'),'');v_token text:=nullif(p_payload->>'csc_token','');v_key text;v_dec smallint:=coalesce(nullif(p_payload->>'unit_decimal_places','')::smallint,2);v_lines smallint:=coalesce(nullif(p_payload->>'product_name_lines','')::smallint,2);v_order text:=coalesce(nullif(p_payload->>'item_order',''),'launch');v_format text:=coalesce(nullif(p_payload->>'product_name_format',''),'{nome}');
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;perform private.ensure_fiscal_defaults(v.tenant_id,v.company_id,v.branch_id);
 if v_env not in('homologation','production') then return jsonb_build_object('ok',false,'error','invalid_environment');end if;if v_csc_id is not null and v_csc_id!~'^[0-9]{1,6}$' then return jsonb_build_object('ok',false,'error','invalid_csc_id');end if;if v_dec not between 2 and 6 then return jsonb_build_object('ok',false,'error','invalid_danfe_decimal_places');end if;if v_lines not between 1 and 5 then return jsonb_build_object('ok',false,'error','invalid_danfe_product_lines');end if;if v_order not in('alphabetical','launch','internal_code') then return jsonb_build_object('ok',false,'error','invalid_danfe_item_order');end if;if length(v_format)>200 then return jsonb_build_object('ok',false,'error','invalid_product_name_format');end if;
 insert into public.fiscal_settings(tenant_id,provider,environment,nfe_series,nfce_series,csc_id) values(v.tenant_id,'svrs_direct',v_env,coalesce((select series::text from public.fiscal_series where tenant_id=v.tenant_id and branch_id=v.branch_id and document_type='nfe' and active and is_default limit 1),'1'),coalesce((select series::text from public.fiscal_series where tenant_id=v.tenant_id and branch_id=v.branch_id and document_type='nfce' and active and is_default limit 1),'1'),v_csc_id) on conflict(tenant_id) do update set provider='svrs_direct',environment=excluded.environment,nfe_series=excluded.nfe_series,nfce_series=excluded.nfce_series,csc_id=excluded.csc_id,updated_at=now();
 insert into public.fiscal_danfe_settings(tenant_id,company_id,branch_id,unit_decimal_places,product_name_lines,item_order,product_name_format,active) values(v.tenant_id,v.company_id,v.branch_id,v_dec,v_lines,v_order,v_format,coalesce(nullif(p_payload->>'danfe_active','')::boolean,true)) on conflict(tenant_id,branch_id) do update set unit_decimal_places=excluded.unit_decimal_places,product_name_lines=excluded.product_name_lines,item_order=excluded.item_order,product_name_format=excluded.product_name_format,active=excluded.active,updated_at=now();
 if p_payload?'csc_id' or p_payload?'csc_token' or coalesce((p_payload->>'clear_csc_token')::boolean,false) then select secret into v_key from private.fiscal_crypto_keys where id=1;if v_key is null then return jsonb_build_object('ok',false,'error','fiscal_crypto_key_missing');end if;insert into private.fiscal_csc_credentials(tenant_id,company_id,branch_id,csc_id,csc_token_cipher) values(v.tenant_id,v.company_id,v.branch_id,v_csc_id,case when v_token is not null then extensions.pgp_sym_encrypt(v_token,v_key) else null end) on conflict(tenant_id,branch_id) do update set company_id=excluded.company_id,csc_id=excluded.csc_id,csc_token_cipher=case when coalesce((p_payload->>'clear_csc_token')::boolean,false) then null when v_token is not null then excluded.csc_token_cipher else private.fiscal_csc_credentials.csc_token_cipher end,updated_at=now();end if;
 return jsonb_build_object('ok',true,'provider','svrs_direct','csc_token_configured',(select csc_token_cipher is not null from private.fiscal_csc_credentials where tenant_id=v.tenant_id and branch_id=v.branch_id));exception when invalid_text_representation then return jsonb_build_object('ok',false,'error','invalid_fiscal_setting_value');
end $function$;

create or replace function public.erp_fiscal_series_save(p_token text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v record;v_id uuid:=nullif(p_payload->>'id','')::uuid;old public.fiscal_series%rowtype;v_type text:=lower(trim(p_payload->>'document_type'));v_series integer:=nullif(p_payload->>'series','')::integer;v_last bigint:=coalesce(nullif(p_payload->>'last_number','')::bigint,0);v_default boolean:=coalesce((p_payload->>'is_default')::boolean,false);v_active boolean:=coalesce((p_payload->>'active')::boolean,true);v_label text:=nullif(trim(p_payload->>'label'),'');v_max bigint:=0;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;perform private.ensure_fiscal_defaults(v.tenant_id,v.company_id,v.branch_id);if v_type not in('nfe','nfce') then return jsonb_build_object('ok',false,'error','invalid_document_type');end if;if v_series is null or v_series not between 1 and 999 then return jsonb_build_object('ok',false,'error','invalid_fiscal_series');end if;if v_last<0 or v_last>999999999 then return jsonb_build_object('ok',false,'error','invalid_last_fiscal_number');end if;
 if v_id is not null then select * into old from public.fiscal_series where id=v_id and tenant_id=v.tenant_id and branch_id=v.branch_id for update;if old.id is null then return jsonb_build_object('ok',false,'error','fiscal_series_not_found');end if;if(old.document_type<>v_type or old.series<>v_series) and exists(select 1 from public.fiscal_documents where tenant_id=v.tenant_id and branch_id=v.branch_id and document_type=old.document_type and series=old.series::text) then return jsonb_build_object('ok',false,'error','series_identity_locked_by_documents');end if;end if;
 select coalesce(max(number::bigint),0) into v_max from public.fiscal_documents where tenant_id=v.tenant_id and branch_id=v.branch_id and document_type=v_type and series=v_series::text and number~'^[0-9]+$';if v_last<v_max then return jsonb_build_object('ok',false,'error','last_number_below_existing_document','minimum',v_max);end if;if not v_active and v_id is not null and exists(select 1 from public.fiscal_pos_series where fiscal_series_id=v_id and in_use) then return jsonb_build_object('ok',false,'error','series_in_use_by_cash_register');end if;if not v_active and(v_default or coalesce(old.is_default,false)) then return jsonb_build_object('ok',false,'error','default_series_cannot_be_disabled');end if;if not v_default and not exists(select 1 from public.fiscal_series where tenant_id=v.tenant_id and branch_id=v.branch_id and document_type=v_type and active and is_default and(v_id is null or id<>v_id)) then v_default:=true;end if;if v_default then update public.fiscal_series set is_default=false,updated_at=now() where tenant_id=v.tenant_id and branch_id=v.branch_id and document_type=v_type and(v_id is null or id<>v_id);end if;
 if v_id is null then insert into public.fiscal_series(tenant_id,company_id,branch_id,document_type,series,label,last_number,is_default,active) values(v.tenant_id,v.company_id,v.branch_id,v_type,v_series,coalesce(v_label,upper(v_type)||' Série '||v_series),v_last,v_default,v_active) returning id into v_id;else update public.fiscal_series set document_type=v_type,series=v_series,label=coalesce(v_label,upper(v_type)||' Série '||v_series),last_number=v_last,is_default=v_default,active=v_active,updated_at=now() where id=v_id;end if;if v_default then update public.fiscal_settings set nfe_series=case when v_type='nfe' then v_series::text else nfe_series end,nfce_series=case when v_type='nfce' then v_series::text else nfce_series end,updated_at=now() where tenant_id=v.tenant_id;end if;return jsonb_build_object('ok',true,'id',v_id,'last_number',v_last,'next_number',v_last+1,'is_default',v_default);exception when unique_violation then return jsonb_build_object('ok',false,'error','fiscal_series_already_exists');when invalid_text_representation then return jsonb_build_object('ok',false,'error','invalid_fiscal_series_value');
end $function$;

create or replace function public.erp_fiscal_pos_series_save(p_token text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v record;v_pos uuid:=nullif(p_payload->>'pos_register_id','')::uuid;v_series uuid:=nullif(p_payload->>'fiscal_series_id','')::uuid;v_cash text:=nullif(trim(p_payload->>'cash_number'),'');v_use boolean:=coalesce((p_payload->>'in_use')::boolean,true);v_map uuid;pr public.pos_registers%rowtype;fs public.fiscal_series%rowtype;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;select * into pr from public.pos_registers where id=v_pos and tenant_id=v.tenant_id and branch_id=v.branch_id;if pr.id is null then return jsonb_build_object('ok',false,'error','cash_register_not_found');end if;select id into v_map from public.fiscal_pos_series where tenant_id=v.tenant_id and pos_register_id=v_pos and in_use order by updated_at desc limit 1;if not v_use then update public.fiscal_pos_series set in_use=false,updated_at=now() where tenant_id=v.tenant_id and pos_register_id=v_pos and in_use;return jsonb_build_object('ok',true,'in_use',false);end if;if v_series is null then return jsonb_build_object('ok',false,'error','fiscal_series_required');end if;select * into fs from public.fiscal_series where id=v_series and tenant_id=v.tenant_id and branch_id=v.branch_id and document_type='nfce' and active;if fs.id is null then return jsonb_build_object('ok',false,'error','nfce_series_not_found');end if;v_cash:=coalesce(v_cash,nullif(pr.code,''),pr.name);if exists(select 1 from public.fiscal_pos_series where tenant_id=v.tenant_id and branch_id=v.branch_id and in_use and cash_number=v_cash and pos_register_id<>v_pos) then return jsonb_build_object('ok',false,'error','cash_number_already_in_use');end if;if exists(select 1 from public.fiscal_pos_series where tenant_id=v.tenant_id and in_use and fiscal_series_id=v_series and pos_register_id<>v_pos) then return jsonb_build_object('ok',false,'error','fiscal_series_already_in_use');end if;if v_map is null then insert into public.fiscal_pos_series(tenant_id,company_id,branch_id,pos_register_id,fiscal_series_id,cash_number,in_use) values(v.tenant_id,v.company_id,v.branch_id,v_pos,v_series,v_cash,true) returning id into v_map;else update public.fiscal_pos_series set fiscal_series_id=v_series,cash_number=v_cash,in_use=true,updated_at=now() where id=v_map;end if;return jsonb_build_object('ok',true,'id',v_map,'cash_number',v_cash,'series',fs.series);exception when unique_violation then return jsonb_build_object('ok',false,'error','cash_or_series_already_in_use');
end $function$;

create or replace function public.erp_fiscal_cfop_save(p_token text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v record;v_id uuid:=nullif(p_payload->>'id','')::uuid;v_code text:=regexp_replace(coalesce(p_payload->>'code',''),'\D','','g');v_name text:=trim(coalesce(p_payload->>'name',''));v_active boolean:=coalesce((p_payload->>'active')::boolean,true);
begin select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;perform private.ensure_default_cfops(v.tenant_id);if v_code!~'^[0-9]{4}$' then return jsonb_build_object('ok',false,'error','invalid_cfop_code');end if;if length(v_name)<3 then return jsonb_build_object('ok',false,'error','invalid_cfop_name');end if;if v_id is null then insert into public.fiscal_cfops(tenant_id,code,name,active) values(v.tenant_id,v_code,v_name,v_active) on conflict(tenant_id,code) do update set name=excluded.name,active=excluded.active,updated_at=now() returning id into v_id;else update public.fiscal_cfops set code=v_code,name=v_name,active=v_active,updated_at=now() where id=v_id and tenant_id=v.tenant_id returning id into v_id;if v_id is null then return jsonb_build_object('ok',false,'error','cfop_not_found');end if;end if;return jsonb_build_object('ok',true,'id',v_id,'code',v_code);exception when unique_violation then return jsonb_build_object('ok',false,'error','cfop_already_exists');end $function$;

create or replace function public.erp_fiscal_prepare_v2(p_token text,p_sale_id uuid,p_document_type text,p_series_id uuid default null) returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v record;s public.sales%rowtype;c public.companies%rowtype;b public.branches%rowtype;cfg public.fiscal_settings%rowtype;cert record;sr public.fiscal_series%rowtype;v_doc uuid;v_number bigint;v_errors jsonb:='[]'::jsonb;v_payload jsonb;v_pos uuid;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;if p_document_type not in('nfe','nfce') then return jsonb_build_object('ok',false,'error','unsupported_document_type');end if;select * into s from public.sales where id=p_sale_id and tenant_id=v.tenant_id and status='completed';if s.id is null then return jsonb_build_object('ok',false,'error','sale_not_found');end if;if exists(select 1 from public.fiscal_documents where sale_id=p_sale_id and document_type=p_document_type and status not in('cancelled','rejected')) then return jsonb_build_object('ok',false,'error','fiscal_document_already_exists');end if;perform private.ensure_fiscal_defaults(s.tenant_id,s.company_id,s.branch_id);select * into c from public.companies where id=s.company_id;select * into b from public.branches where id=s.branch_id;select * into cfg from public.fiscal_settings where tenant_id=s.tenant_id;select * into cert from private.fiscal_certificates where tenant_id=s.tenant_id and company_id=s.company_id;if nullif(c.cnpj,'') is null then v_errors:=v_errors||jsonb_build_array('Empresa sem CNPJ cadastrado');end if;if nullif(c.state_registration,'') is null then v_errors:=v_errors||jsonb_build_array('Empresa sem Inscrição Estadual');end if;if exists(select 1 from public.sale_items si join public.products p on p.id=si.product_id where si.sale_id=p_sale_id and(nullif(p.ncm,'') is null or nullif(p.cfop_default,'') is null)) then v_errors:=v_errors||jsonb_build_array('Há produtos sem NCM ou CFOP padrão');end if;if cert.company_id is null then v_errors:=v_errors||jsonb_build_array('Certificado digital A1 (.pfx/.p12) não configurado');elsif cert.valid_to is not null and cert.valid_to<now() then v_errors:=v_errors||jsonb_build_array('Certificado digital expirado');end if;
 if p_series_id is not null then select * into sr from public.fiscal_series where id=p_series_id and tenant_id=s.tenant_id and branch_id=s.branch_id and document_type=p_document_type and active;if sr.id is null then return jsonb_build_object('ok',false,'error','fiscal_series_not_found');end if;elsif p_document_type='nfce' and s.cash_session_id is not null then select cs.pos_register_id into v_pos from public.cash_sessions cs where cs.id=s.cash_session_id;select fs.* into sr from public.fiscal_pos_series fps join public.fiscal_series fs on fs.id=fps.fiscal_series_id where fps.tenant_id=s.tenant_id and fps.pos_register_id=v_pos and fps.in_use and fs.active and fs.document_type='nfce' limit 1;if sr.id is null and exists(select 1 from public.fiscal_pos_series fps where fps.tenant_id=s.tenant_id and fps.branch_id=s.branch_id and fps.in_use) then return jsonb_build_object('ok',false,'error','nfce_series_not_assigned_to_cash_register');end if;end if;if sr.id is null then select * into sr from public.fiscal_series where tenant_id=s.tenant_id and branch_id=s.branch_id and document_type=p_document_type and active and is_default limit 1;end if;if sr.id is null then return jsonb_build_object('ok',false,'error','fiscal_series_not_configured');end if;select * into sr from public.fiscal_series where id=sr.id for update;v_number:=sr.last_number+1;if v_number>999999999 then return jsonb_build_object('ok',false,'error','fiscal_number_limit_reached');end if;update public.fiscal_series set last_number=v_number,updated_at=now() where id=sr.id;
 select jsonb_build_object('sale',to_jsonb(s),'company',to_jsonb(c),'branch',to_jsonb(b),'customer',(select to_jsonb(cu) from public.customers cu where cu.id=s.customer_id),'series_id',sr.id,'items',coalesce((select jsonb_agg(jsonb_build_object('product_id',si.product_id,'sku',si.sku,'description',si.description,'unit',si.unit,'quantity',si.quantity,'unit_price',si.unit_price,'discount',si.discount,'total',si.total,'fiscal_snapshot',si.fiscal_snapshot)) from public.sale_items si where si.sale_id=s.id),'[]'::jsonb)) into v_payload;insert into public.fiscal_documents(tenant_id,company_id,branch_id,sale_id,document_type,environment,status,series,number,provider,request_payload,response_payload) values(s.tenant_id,s.company_id,s.branch_id,s.id,p_document_type,coalesce(cfg.environment,'homologation'),'draft',sr.series::text,v_number::text,'svrs_direct',v_payload,jsonb_build_object('validation_errors',v_errors)) returning id into v_doc;return jsonb_build_object('ok',true,'id',v_doc,'number',v_number,'series',sr.series,'series_id',sr.id,'validation_errors',v_errors,'ready_to_send',jsonb_array_length(v_errors)=0);
end $function$;
create or replace function public.erp_fiscal_prepare(p_token text,p_sale_id uuid,p_document_type text) returns jsonb language sql security definer set search_path='public','private','extensions' as $function$ select public.erp_fiscal_prepare_v2(p_token,p_sale_id,p_document_type,null::uuid); $function$;

create or replace function private.pdv_request_nfce(p_device_id uuid,p_tenant_id uuid,p_company_id uuid,p_branch_id uuid,p_event_id uuid,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $function$
declare v_sale public.sales%rowtype;v_doc public.fiscal_documents%rowtype;v_settings public.fiscal_settings%rowtype;v_operator uuid;v_op jsonb;v_pos uuid;v_series public.fiscal_series%rowtype;v_number bigint;
begin
 if nullif(p_payload->>'sale_id','') is not null then select * into v_sale from public.sales where id=(p_payload->>'sale_id')::uuid and tenant_id=p_tenant_id and branch_id=p_branch_id;elsif nullif(p_payload->>'sale_client_event_id','') is not null then select * into v_sale from public.sales where pdv_device_id=p_device_id and client_event_id=(p_payload->>'sale_client_event_id')::uuid and tenant_id=p_tenant_id;end if;if v_sale.id is null then return jsonb_build_object('ok',false,'error','sale_not_found');end if;if v_sale.status<>'completed' then return jsonb_build_object('ok',false,'error','sale_not_completed');end if;v_operator:=coalesce(nullif(p_payload->>'operator_user_id','')::uuid,v_sale.staff_user_id);if v_operator is null then return jsonb_build_object('ok',false,'error','operator_required');end if;v_op:=private.pdv_staff_permissions(p_tenant_id,p_branch_id,v_operator);if v_op is null then return jsonb_build_object('ok',false,'error','invalid_operator');end if;if not coalesce((v_op#>>'{permissions,fiscal,request_nfce}')::boolean,false) then return jsonb_build_object('ok',false,'error','nfce_request_not_allowed');end if;
 select * into v_doc from public.fiscal_documents where sale_id=v_sale.id and document_type='nfce' order by created_at desc limit 1;if v_doc.id is not null then return jsonb_build_object('ok',true,'sale_id',v_sale.id,'fiscal_document_id',v_doc.id,'status',v_doc.status,'access_key',v_doc.access_key,'protocol',v_doc.protocol,'pdf_path',v_doc.pdf_path,'series',v_doc.series,'number',v_doc.number,'idempotent',true);end if;perform private.ensure_fiscal_defaults(p_tenant_id,p_company_id,p_branch_id);select * into v_settings from public.fiscal_settings where tenant_id=p_tenant_id limit 1;select cs.pos_register_id into v_pos from public.cash_sessions cs where cs.id=v_sale.cash_session_id and cs.tenant_id=p_tenant_id;v_pos:=coalesce(v_pos,(select d.pos_register_id from public.pdv_devices d where d.id=p_device_id and d.tenant_id=p_tenant_id));if v_pos is not null then select fs.* into v_series from public.fiscal_pos_series fps join public.fiscal_series fs on fs.id=fps.fiscal_series_id where fps.tenant_id=p_tenant_id and fps.branch_id=p_branch_id and fps.pos_register_id=v_pos and fps.in_use and fs.active and fs.document_type='nfce' limit 1;end if;if v_series.id is null and exists(select 1 from public.fiscal_pos_series fps where fps.tenant_id=p_tenant_id and fps.branch_id=p_branch_id and fps.in_use) then return jsonb_build_object('ok',false,'error','nfce_series_not_assigned_to_cash_register','pos_register_id',v_pos);end if;if v_series.id is null then select * into v_series from public.fiscal_series where tenant_id=p_tenant_id and branch_id=p_branch_id and document_type='nfce' and active and is_default limit 1;end if;if v_series.id is null then return jsonb_build_object('ok',false,'error','fiscal_series_not_configured');end if;select * into v_series from public.fiscal_series where id=v_series.id for update;v_number:=v_series.last_number+1;if v_number>999999999 then return jsonb_build_object('ok',false,'error','fiscal_number_limit_reached');end if;update public.fiscal_series set last_number=v_number,updated_at=now() where id=v_series.id;
 insert into public.fiscal_documents(tenant_id,company_id,branch_id,sale_id,document_type,environment,status,series,number,provider,request_payload) values(p_tenant_id,p_company_id,p_branch_id,v_sale.id,'nfce',coalesce(v_settings.environment,'homologation'),'draft',v_series.series::text,v_number::text,coalesce(v_settings.provider,'svrs_direct'),jsonb_build_object('source','pdv_desktop','requested_by_device',p_device_id,'requested_by_operator',v_operator,'client_event_id',p_event_id,'requested_at',now(),'series_id',v_series.id,'pos_register_id',v_pos)) returning * into v_doc;return jsonb_build_object('ok',true,'sale_id',v_sale.id,'fiscal_document_id',v_doc.id,'status',v_doc.status,'provider',v_doc.provider,'series',v_doc.series,'number',v_doc.number,'series_id',v_series.id,'requires_provider',v_doc.provider is null or v_doc.provider='internal');
end $function$;
