create or replace function public.erp_cash_list(p_token text)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;v_data jsonb;
begin
  select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;
  select coalesce(jsonb_agg(to_jsonb(x) order by x.opened_at desc),'[]'::jsonb) into v_data from (
    select cs.id,cs.status,cs.opening_amount,cs.closing_amount,cs.opened_at,cs.closed_at,pr.name pos,pr.code,b.name branch,su.name operator,
      coalesce((select sum(s.total) from public.sales s where s.cash_session_id=cs.id and s.status='completed'),0) sales_total,
      coalesce((select sum(p.amount) from public.payments p join public.sales s on s.id=p.sale_id where s.cash_session_id=cs.id and p.status='paid'),0) received_total,
      coalesce((select sum(p.amount) from public.payments p join public.sales s on s.id=p.sale_id where s.cash_session_id=cs.id and p.status in ('paid','authorized') and p.method='cash' and s.status='completed'),0) cash_received,
      coalesce((select sum(cm.amount) from public.cash_movements cm where cm.cash_session_id=cs.id and cm.movement_type='receivable'),0) receivable_received,
      cs.opening_amount+coalesce((select sum(p.amount) from public.payments p join public.sales s on s.id=p.sale_id where s.cash_session_id=cs.id and p.status in ('paid','authorized') and p.method='cash' and s.status='completed'),0)+coalesce((select sum(cm.amount) from public.cash_movements cm where cm.cash_session_id=cs.id and cm.movement_type in ('supply','receivable')),0)-coalesce((select sum(cm.amount) from public.cash_movements cm where cm.cash_session_id=cs.id and cm.movement_type in ('withdrawal','sangria','expense','refund')),0) expected_cash
    from public.cash_sessions cs join public.pos_registers pr on pr.id=cs.pos_register_id join public.branches b on b.id=pr.branch_id left join public.staff_users su on su.id=cs.staff_user_id where cs.tenant_id=v.tenant_id limit 100
  ) x;
  return jsonb_build_object('ok',true,'data',v_data);
end $$;

create or replace function public.pdv_cash_preview(p_device_token text)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;v_cash record;v_payments jsonb;v_movements jsonb;v_sales_count int:=0;v_sales_total numeric:=0;v_opening numeric:=0;v_cash_payments numeric:=0;v_supply numeric:=0;v_receivable numeric:=0;v_withdrawal numeric:=0;v_expense numeric:=0;v_refund numeric:=0;v_expected numeric:=0;
begin
  select * into v from private.resolve_pdv_device(p_device_token);if v.device_id is null then return jsonb_build_object('ok',false,'error','invalid_device');end if;
  select cs.* into v_cash from public.cash_sessions cs where cs.tenant_id=v.tenant_id and cs.pos_register_id=v.pos_register_id and cs.status='open' order by cs.opened_at desc limit 1;if v_cash.id is null then return jsonb_build_object('ok',false,'error','cash_not_open');end if;v_opening:=coalesce(v_cash.opening_amount,0);
  select coalesce(jsonb_agg(jsonb_build_object('method',x.method,'amount',x.amount,'count',x.cnt) order by x.method),'[]'::jsonb),coalesce(sum(case when x.method='cash' then x.amount else 0 end),0) into v_payments,v_cash_payments from (select p.method,sum(p.amount)::numeric amount,count(*)::int cnt from public.payments p join public.sales s on s.id=p.sale_id where s.cash_session_id=v_cash.id and p.status in ('paid','authorized') and s.status<>'cancelled' group by p.method) x;
  select coalesce(count(*),0)::int,coalesce(sum(s.total),0)::numeric into v_sales_count,v_sales_total from public.sales s where s.cash_session_id=v_cash.id and s.status<>'cancelled';
  select coalesce(jsonb_agg(jsonb_build_object('movement_type',x.movement_type,'amount',x.amount,'count',x.cnt) order by x.movement_type),'[]'::jsonb) into v_movements from (select cm.movement_type,sum(cm.amount)::numeric amount,count(*)::int cnt from public.cash_movements cm where cm.cash_session_id=v_cash.id group by cm.movement_type) x;
  select coalesce(sum(case when movement_type='supply' then amount else 0 end),0),coalesce(sum(case when movement_type='receivable' then amount else 0 end),0),coalesce(sum(case when movement_type in ('withdrawal','sangria') then amount else 0 end),0),coalesce(sum(case when movement_type='expense' then amount else 0 end),0),coalesce(sum(case when movement_type='refund' then amount else 0 end),0) into v_supply,v_receivable,v_withdrawal,v_expense,v_refund from public.cash_movements where cash_session_id=v_cash.id;
  v_expected:=v_opening+v_cash_payments+v_supply+v_receivable-v_withdrawal-v_expense-v_refund;
  return jsonb_build_object('ok',true,'source','server','cash_session_id',v_cash.id,'client_event_id',v_cash.client_event_id,'opened_at',v_cash.opened_at,'operator_user_id',v_cash.staff_user_id,'opening_amount',v_opening,'sales_count',v_sales_count,'sales_total',v_sales_total,'payments',coalesce(v_payments,'[]'::jsonb),'movements',coalesce(v_movements,'[]'::jsonb),'cash_payments',v_cash_payments,'supply',v_supply,'receivable_received',v_receivable,'withdrawal',v_withdrawal,'expense',v_expense,'refund',v_refund,'expected_cash',v_expected,'server_time',now());
end $$;

create or replace function public.erp_sales_cash_dashboard_v2(p_token text,p_start timestamptz default null,p_end timestamptz default null,p_operator uuid default null,p_branch uuid default null,p_cash_status text default null,p_operation_filter text default null)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;v_start timestamptz:=coalesce(p_start,date_trunc('day',now()));v_end timestamptz:=coalesce(p_end,date_trunc('day',now())+interval '1 day');v_sessions jsonb;v_ops jsonb;v_operators jsonb;v_branches jsonb;v_summary jsonb;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;
 with sc as (select cs.id,cs.status,cs.opening_amount,cs.closing_amount,cs.opened_at,cs.closed_at,cs.staff_user_id,pr.name pos,pr.code pos_code,pr.branch_id,b.name branch,su.name operator,coalesce((select count(*) from public.sales s where s.cash_session_id=cs.id and s.status='completed'),0) sales_count,coalesce((select sum(s.total) from public.sales s where s.cash_session_id=cs.id and s.status='completed'),0) sales_total,coalesce((select sum(p.amount) from public.payments p join public.sales s on s.id=p.sale_id where s.cash_session_id=cs.id and s.status='completed' and p.status in ('paid','authorized') and p.method='cash'),0) cash_received,coalesce((select sum(amount) from public.cash_movements where cash_session_id=cs.id and movement_type='supply'),0) supply,coalesce((select sum(amount) from public.cash_movements where cash_session_id=cs.id and movement_type='receivable'),0) receivable_received,coalesce((select sum(amount) from public.cash_movements where cash_session_id=cs.id and movement_type in ('withdrawal','sangria')),0) withdrawal,coalesce((select sum(amount) from public.cash_movements where cash_session_id=cs.id and movement_type='expense'),0) expense,coalesce((select sum(amount) from public.cash_movements where cash_session_id=cs.id and movement_type='refund'),0) refund from public.cash_sessions cs join public.pos_registers pr on pr.id=cs.pos_register_id join public.branches b on b.id=pr.branch_id left join public.staff_users su on su.id=cs.staff_user_id where cs.tenant_id=v.tenant_id and (p_branch is null or pr.branch_id=p_branch) and (p_operator is null or cs.staff_user_id=p_operator) and (p_cash_status is null or p_cash_status='' or cs.status=p_cash_status) and (cs.status='open' or (cs.opened_at<v_end and coalesce(cs.closed_at,v_end)>=v_start))),e as (select sc.*,(opening_amount+cash_received+supply+receivable_received-withdrawal-expense-refund) expected_cash from sc) select coalesce(jsonb_agg(to_jsonb(e) order by opened_at desc),'[]'::jsonb) into v_sessions from e;
 with fs as (select cs.id,cs.staff_user_id,pr.branch_id,pr.name pos,b.name branch,su.name operator from public.cash_sessions cs join public.pos_registers pr on pr.id=cs.pos_register_id join public.branches b on b.id=pr.branch_id left join public.staff_users su on su.id=cs.staff_user_id where cs.tenant_id=v.tenant_id and (p_branch is null or pr.branch_id=p_branch) and (p_operator is null or cs.staff_user_id=p_operator)),raw as (select cs.id::text||':open' op_key,cs.id cash_session_id,null::uuid sale_id,cs.opened_at occurred_at,'opening' op_type,'Abertura de caixa' description,cs.opening_amount amount,fs.pos,fs.branch,fs.operator,cs.staff_user_id operator_id,'realized' operation_state,null::uuid fiscal_document_id,null::text document_type,null::text fiscal_status,false fiscal_pending from public.cash_sessions cs join fs on fs.id=cs.id where cs.opened_at>=v_start and cs.opened_at<v_end union all select s.id::text,s.cash_session_id,s.id,coalesce(s.completed_at,s.created_at),'sale','Venda #'||s.number::text,s.total,fs.pos,fs.branch,coalesce(su.name,fs.operator),s.staff_user_id,case when s.status='cancelled' then 'cancelled' when fd.id is not null and fd.status not in ('authorized','cancelled') then 'fiscal_pending' else 'realized' end,fd.id,fd.document_type,fd.status,(fd.id is not null and fd.status not in ('authorized','cancelled')) from public.sales s join fs on fs.id=s.cash_session_id left join public.staff_users su on su.id=s.staff_user_id left join lateral (select f.id,f.document_type,f.status from public.fiscal_documents f where f.sale_id=s.id order by f.created_at desc limit 1) fd on true where coalesce(s.completed_at,s.created_at)>=v_start and coalesce(s.completed_at,s.created_at)<v_end and (p_operator is null or s.staff_user_id=p_operator or fs.staff_user_id=p_operator) union all select cm.id::text,cm.cash_session_id,null::uuid,cm.created_at,'cash_movement',case cm.movement_type when 'supply' then 'Suprimento' when 'withdrawal' then 'Sangria' when 'sangria' then 'Sangria' when 'expense' then 'Despesa' when 'refund' then 'Devolução em dinheiro' when 'receivable' then 'Recebimento de conta a receber' else 'Movimento: '||cm.movement_type end,cm.amount,fs.pos,fs.branch,fs.operator,fs.staff_user_id,'realized',null,null,null,false from public.cash_movements cm join fs on fs.id=cm.cash_session_id where cm.created_at>=v_start and cm.created_at<v_end) select coalesce(jsonb_agg(to_jsonb(r) order by occurred_at desc),'[]'::jsonb) into v_ops from raw r where coalesce(nullif(p_operation_filter,''),'all')='all' or r.operation_state=p_operation_filter;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by name),'[]'::jsonb) into v_operators from public.staff_users where tenant_id=v.tenant_id and active=true;select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by name),'[]'::jsonb) into v_branches from public.branches where tenant_id=v.tenant_id;
 select jsonb_build_object('open_cash',count(*) filter(where status='open'),'closed_cash',count(*) filter(where status='closed'),'sales_total',coalesce((select sum(s.total) from public.sales s where s.tenant_id=v.tenant_id and s.status='completed' and coalesce(s.completed_at,s.created_at)>=v_start and coalesce(s.completed_at,s.created_at)<v_end and (p_branch is null or s.branch_id=p_branch) and (p_operator is null or s.staff_user_id=p_operator)),0),'sessions',count(*)) into v_summary from public.cash_sessions cs join public.pos_registers pr on pr.id=cs.pos_register_id where cs.tenant_id=v.tenant_id and (p_branch is null or pr.branch_id=p_branch) and (p_operator is null or cs.staff_user_id=p_operator);
 return jsonb_build_object('ok',true,'sessions',v_sessions,'operations',v_ops,'operators',v_operators,'branches',v_branches,'summary',v_summary,'start',v_start,'end',v_end);
end $$;
