alter table public.reconciliation_matches add column if not exists settlement_bank_transaction_id uuid references public.bank_transactions(id) on delete set null;
create index if not exists reconciliation_matches_settlement_tx_idx on public.reconciliation_matches(settlement_bank_transaction_id);

update public.bank_transactions bt set reconciled=false from public.bank_accounts ba where ba.id=bt.bank_account_id and ba.account_type='bank' and bt.origin_type='financial_settlement';

create or replace function public.erp_bank_transaction_add(p_token text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;v_id uuid;v_account uuid:=nullif(p_payload->>'bank_account_id','')::uuid;v_direction text:=coalesce(nullif(p_payload->>'direction',''),'credit');v_amount numeric:=abs(coalesce(nullif(p_payload->>'amount','')::numeric,0));v_type text;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;if v_amount<=0 then return jsonb_build_object('ok',false,'error','invalid_amount');end if;if v_direction not in('credit','debit') then return jsonb_build_object('ok',false,'error','invalid_direction');end if;
 select account_type into v_type from public.bank_accounts where id=v_account and tenant_id=v.tenant_id and active=true;if v_type is null then return jsonb_build_object('ok',false,'error','bank_account_not_found');end if;
 insert into public.bank_transactions(tenant_id,bank_account_id,transaction_date,description,amount,direction,external_id,reconciled,payment_method,origin_type,notes) values(v.tenant_id,v_account,coalesce(nullif(p_payload->>'transaction_date','')::date,current_date),coalesce(nullif(trim(p_payload->>'description'),''),'Lançamento manual'),v_amount,v_direction,nullif(trim(p_payload->>'external_id'),''),v_type='internal_cash',nullif(p_payload->>'payment_method',''),'manual',nullif(trim(p_payload->>'notes'),'')) returning id into v_id;
 return jsonb_build_object('ok',true,'id',v_id,'reconciled',v_type='internal_cash');
end $$;

create or replace function public.erp_financial_settle(p_token text,p_entry_id uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;fe public.financial_entries%rowtype;ba public.bank_accounts%rowtype;cs public.cash_sessions%rowtype;v_remaining numeric;v_amount numeric;v_method text:=nullif(p_payload->>'payment_method','');v_destination text:=nullif(p_payload->>'destination_type','');v_account uuid:=nullif(p_payload->>'bank_account_id','')::uuid;v_cash uuid:=nullif(p_payload->>'cash_session_id','')::uuid;v_settlement uuid:=gen_random_uuid();v_bank_tx uuid;v_internal uuid;v_cm uuid;v_settled_at timestamptz:=coalesce(nullif(p_payload->>'settled_at','')::timestamptz,now());v_balance numeric;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;select * into fe from public.financial_entries where id=p_entry_id and tenant_id=v.tenant_id for update;if fe.id is null or fe.status='cancelled' then return jsonb_build_object('ok',false,'error','financial_entry_not_found');end if;
 v_remaining:=greatest(fe.amount-fe.paid_amount,0);v_amount:=coalesce(nullif(p_payload->>'amount','')::numeric,v_remaining);if v_amount<=0 or v_amount>v_remaining+0.001 then return jsonb_build_object('ok',false,'error','invalid_settlement_amount','remaining',v_remaining);end if;
 if v_method is null or v_method='term_sale' or not exists(select 1 from public.sales_payment_methods m where m.tenant_id=v.tenant_id and m.company_id=fe.company_id and m.code=v_method and m.active=true) then return jsonb_build_object('ok',false,'error','invalid_payment_method');end if;
 if v_method='store_credit' then if fe.entry_type<>'receivable' or fe.customer_id is null then return jsonb_build_object('ok',false,'error','store_credit_requires_customer');end if;perform pg_advisory_xact_lock(hashtext(v.tenant_id::text||':'||fe.customer_id::text));v_balance:=private.customer_store_credit_balance(v.tenant_id,fe.customer_id);if v_balance+0.001<v_amount then return jsonb_build_object('ok',false,'error','insufficient_store_credit','available',v_balance);end if;v_destination:='store_credit';
 elsif v_destination='cash_session' then if v_method<>'cash' then return jsonb_build_object('ok',false,'error','cash_session_requires_cash_payment');end if;select * into cs from public.cash_sessions where id=v_cash and tenant_id=v.tenant_id and status='open' for update;if cs.id is null then return jsonb_build_object('ok',false,'error','cash_not_open');end if;
 elsif v_destination='bank_account' then select * into ba from public.bank_accounts where id=v_account and tenant_id=v.tenant_id and active=true for update;if ba.id is null then return jsonb_build_object('ok',false,'error','bank_account_not_found');end if;if ba.account_type='internal_cash' and v_method<>'cash' then return jsonb_build_object('ok',false,'error','internal_cash_requires_cash_payment');end if;else return jsonb_build_object('ok',false,'error','destination_required');end if;
 insert into public.financial_settlements(id,tenant_id,company_id,branch_id,financial_entry_id,amount,settled_at,payment_method,destination_type,bank_account_id,cash_session_id,notes,metadata) values(v_settlement,v.tenant_id,fe.company_id,fe.branch_id,fe.id,v_amount,v_settled_at,v_method,v_destination,case when v_destination='bank_account' then v_account end,case when v_destination='cash_session' then v_cash end,nullif(trim(p_payload->>'notes'),''),jsonb_build_object('entry_type',fe.entry_type,'document_type',fe.document_type));
 if v_method='store_credit' then insert into public.customer_store_credit_ledger(tenant_id,company_id,branch_id,customer_id,entry_type,amount,source_kind,source_id,sale_id,notes,metadata) values(v.tenant_id,fe.company_id,fe.branch_id,fe.customer_id,'debit',v_amount,'financial_settlement',v_settlement,fe.sale_id,'Uso de crédito da loja na quitação de '||fe.description,jsonb_build_object('financial_entry_id',fe.id)) on conflict(tenant_id,source_kind,source_id) do nothing;
 elsif v_destination='cash_session' then insert into public.cash_movements(tenant_id,cash_session_id,movement_type,amount,notes,financial_entry_id,payment_method) values(v.tenant_id,v_cash,case when fe.entry_type='receivable' then 'receivable' else 'expense' end,v_amount,'Liquidação financeira: '||fe.description,fe.id,'cash') returning id into v_cm;v_internal:=private.ensure_internal_cash_account(v.tenant_id,fe.company_id,fe.branch_id);insert into public.bank_transactions(tenant_id,bank_account_id,transaction_date,description,amount,direction,reconciled,financial_entry_id,cash_session_id,payment_method,origin_type,origin_id,notes) values(v.tenant_id,v_internal,v_settled_at::date,fe.description,v_amount,case when fe.entry_type='receivable' then 'credit' else 'debit' end,true,fe.id,v_cash,'cash','financial_settlement',v_settlement,'Liquidação vinculada ao caixa do dia.') returning id into v_bank_tx;
 else insert into public.bank_transactions(tenant_id,bank_account_id,transaction_date,description,amount,direction,reconciled,financial_entry_id,payment_method,origin_type,origin_id,notes) values(v.tenant_id,v_account,v_settled_at::date,fe.description,v_amount,case when fe.entry_type='receivable' then 'credit' else 'debit' end,ba.account_type='internal_cash',fe.id,v_method,'financial_settlement',v_settlement,case when ba.account_type='bank' then 'Lançamento previsto; aguarda conciliação com extrato bancário.' else 'Liquidação no Caixa Interno.' end) returning id into v_bank_tx;end if;
 update public.financial_settlements set bank_transaction_id=v_bank_tx where id=v_settlement;update public.financial_entries set paid_amount=least(amount,paid_amount+v_amount),status=case when paid_amount+v_amount>=amount-0.001 then 'paid' else 'partial' end,paid_at=case when paid_amount+v_amount>=amount-0.001 then v_settled_at else paid_at end,updated_at=now(),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('last_payment_method',v_method,'last_destination_type',v_destination,'last_settlement_id',v_settlement) where id=fe.id;
 return jsonb_build_object('ok',true,'settlement_id',v_settlement,'amount',v_amount,'remaining',greatest(v_remaining-v_amount,0),'status',case when v_remaining-v_amount<=0.001 then 'paid' else 'partial' end,'bank_transaction_id',v_bank_tx,'reconciliation_pending',coalesce(ba.account_type='bank',false) and v_destination='bank_account');
end $$;

create or replace function public.erp_reconciliation_data(p_token text)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;v_accounts jsonb;v_transactions jsonb;v_entries jsonb;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;perform private.ensure_internal_cash_account(v.tenant_id,v.company_id,v.branch_id);
 select coalesce(jsonb_agg(to_jsonb(x) order by x.is_system desc,x.name),'[]'::jsonb) into v_accounts from(select ba.id,ba.name,ba.bank_code,ba.agency,ba.account_number,ba.active,ba.account_type,ba.is_system,ba.opening_balance,ba.opening_balance+coalesce(sum(case when bt.direction='credit' then bt.amount else -bt.amount end),0) balance from public.bank_accounts ba left join public.bank_transactions bt on bt.bank_account_id=ba.id where ba.tenant_id=v.tenant_id and(ba.company_id=v.company_id or ba.company_id is null) group by ba.id)x;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.transaction_date desc,x.created_at desc),'[]'::jsonb) into v_transactions from(select bt.id,bt.bank_account_id,ba.name account,ba.account_type,bt.transaction_date,bt.description,bt.amount,bt.direction,bt.external_id,bt.reconciled,bt.payment_method,bt.origin_type,bt.financial_entry_id,coalesce((select sum(rm.matched_amount) from public.reconciliation_matches rm where rm.bank_transaction_id=bt.id),0) matched,bt.created_at,(bt.origin_type='manual' and ba.account_type='bank' and not bt.reconciled) eligible_for_match from public.bank_transactions bt join public.bank_accounts ba on ba.id=bt.bank_account_id where bt.tenant_id=v.tenant_id and(ba.company_id=v.company_id or ba.company_id is null) order by bt.transaction_date desc,bt.created_at desc limit 500)x;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.due_date nulls last,x.description),'[]'::jsonb) into v_entries from(select f.id,f.entry_type,f.description,f.amount,f.paid_amount,greatest(f.amount-f.paid_amount,0) remaining,f.due_date,f.status,coalesce(c.name,s.name) party,exists(select 1 from public.bank_transactions sbt where sbt.financial_entry_id=f.id and sbt.origin_type='financial_settlement' and sbt.reconciled=false) reconciliation_pending,(select ba.name from public.bank_transactions sbt join public.bank_accounts ba on ba.id=sbt.bank_account_id where sbt.financial_entry_id=f.id and sbt.origin_type='financial_settlement' and sbt.reconciled=false order by sbt.created_at limit 1) expected_account,(select sbt.amount-coalesce((select sum(rm.matched_amount) from public.reconciliation_matches rm where rm.settlement_bank_transaction_id=sbt.id),0) from public.bank_transactions sbt where sbt.financial_entry_id=f.id and sbt.origin_type='financial_settlement' and sbt.reconciled=false order by sbt.created_at limit 1) pending_reconciliation_amount from public.financial_entries f left join public.customers c on c.id=f.customer_id left join public.suppliers s on s.id=f.supplier_id where f.tenant_id=v.tenant_id and f.status<>'cancelled' and(f.status<>'paid' or exists(select 1 from public.bank_transactions sbt where sbt.financial_entry_id=f.id and sbt.origin_type='financial_settlement' and sbt.reconciled=false)) order by f.due_date limit 500)x;
 return jsonb_build_object('ok',true,'accounts',v_accounts,'transactions',v_transactions,'entries',v_entries);
end $$;

create or replace function public.erp_reconcile(p_token text,p_transaction_id uuid,p_entry_id uuid,p_amount numeric default null)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;bt public.bank_transactions%rowtype;fe public.financial_entries%rowtype;sbt public.bank_transactions%rowtype;v_remaining_tx numeric;v_remaining_entry numeric;v_remaining_expected numeric;v_match numeric;v_matched_total numeric;v_expected_matched numeric;v_settlement uuid;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;select * into bt from public.bank_transactions where id=p_transaction_id and tenant_id=v.tenant_id and origin_type='manual' for update;if bt.id is null then return jsonb_build_object('ok',false,'error','bank_transaction_not_found');end if;select * into fe from public.financial_entries where id=p_entry_id and tenant_id=v.tenant_id and status<>'cancelled' for update;if fe.id is null then return jsonb_build_object('ok',false,'error','financial_entry_not_found');end if;if(bt.direction='credit' and fe.entry_type<>'receivable')or(bt.direction='debit' and fe.entry_type<>'payable')then return jsonb_build_object('ok',false,'error','direction_entry_mismatch');end if;
 select coalesce(sum(matched_amount),0) into v_matched_total from public.reconciliation_matches where bank_transaction_id=bt.id;v_remaining_tx:=bt.amount-v_matched_total;if v_remaining_tx<=0 then return jsonb_build_object('ok',false,'error','nothing_to_reconcile');end if;select sb.* into sbt from public.bank_transactions sb where sb.tenant_id=v.tenant_id and sb.financial_entry_id=fe.id and sb.bank_account_id=bt.bank_account_id and sb.origin_type='financial_settlement' and sb.reconciled=false and sb.direction=bt.direction order by sb.created_at limit 1 for update;
 if sbt.id is not null then select coalesce(sum(matched_amount),0) into v_expected_matched from public.reconciliation_matches where settlement_bank_transaction_id=sbt.id;v_remaining_expected:=sbt.amount-v_expected_matched;v_match:=least(v_remaining_tx,v_remaining_expected,coalesce(p_amount,greatest(v_remaining_tx,v_remaining_expected)));if v_match<=0 then return jsonb_build_object('ok',false,'error','nothing_to_reconcile');end if;insert into public.reconciliation_matches(tenant_id,bank_transaction_id,financial_entry_id,settlement_bank_transaction_id,matched_amount) values(v.tenant_id,bt.id,fe.id,sbt.id,v_match);select coalesce(sum(matched_amount),0) into v_matched_total from public.reconciliation_matches where bank_transaction_id=bt.id;update public.bank_transactions set reconciled=v_matched_total>=amount-0.001 where id=bt.id;select coalesce(sum(matched_amount),0) into v_expected_matched from public.reconciliation_matches where settlement_bank_transaction_id=sbt.id;update public.bank_transactions set reconciled=v_expected_matched>=amount-0.001 where id=sbt.id;return jsonb_build_object('ok',true,'matched_amount',v_match,'transaction_reconciled',v_matched_total>=bt.amount-0.001,'expected_transaction_reconciled',v_expected_matched>=sbt.amount-0.001,'mode','settlement_confirmation');end if;
 if fe.status='paid' then return jsonb_build_object('ok',false,'error','paid_entry_has_no_pending_settlement');end if;v_remaining_entry:=fe.amount-fe.paid_amount;v_match:=least(v_remaining_tx,v_remaining_entry,coalesce(p_amount,greatest(v_remaining_tx,v_remaining_entry)));if v_match<=0 then return jsonb_build_object('ok',false,'error','nothing_to_reconcile');end if;insert into public.reconciliation_matches(tenant_id,bank_transaction_id,financial_entry_id,matched_amount) values(v.tenant_id,bt.id,fe.id,v_match);insert into public.financial_settlements(tenant_id,company_id,branch_id,financial_entry_id,amount,settled_at,payment_method,destination_type,bank_account_id,bank_transaction_id,notes,metadata) values(v.tenant_id,fe.company_id,fe.branch_id,fe.id,v_match,bt.transaction_date::timestamptz,coalesce(nullif(bt.payment_method,''),'other'),'bank_account',bt.bank_account_id,bt.id,'Baixa realizada pela conciliação bancária.',jsonb_build_object('source','reconciliation')) returning id into v_settlement;update public.financial_entries set paid_amount=least(amount,paid_amount+v_match),status=case when paid_amount+v_match>=amount-0.001 then 'paid' else 'partial' end,paid_at=case when paid_amount+v_match>=amount-0.001 then coalesce(paid_at,bt.transaction_date::timestamptz) else paid_at end,updated_at=now(),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('last_settlement_id',v_settlement,'last_destination_type','bank_account') where id=fe.id;select coalesce(sum(matched_amount),0) into v_matched_total from public.reconciliation_matches where bank_transaction_id=bt.id;update public.bank_transactions set reconciled=v_matched_total>=amount-0.001,financial_entry_id=fe.id where id=bt.id;return jsonb_build_object('ok',true,'matched_amount',v_match,'transaction_reconciled',v_matched_total>=bt.amount-0.001,'mode','direct_bank_settlement');
end $$;
