create table if not exists public.sales_management_audit(
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, sale_id uuid not null references public.sales(id) on delete cascade,
 action text not null, reason text, previous_status text, new_status text, actor_user_id uuid, actor_email text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists sales_management_audit_sale_idx on public.sales_management_audit(sale_id,created_at desc);

create or replace function public.erp_sales_cash_dashboard_v2(p_token text,p_start timestamptz default null,p_end timestamptz default null,p_operator uuid default null,p_branch uuid default null,p_cash_status text default null,p_operation_filter text default null)
returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $$
declare v record; v_start timestamptz:=coalesce(p_start,date_trunc('day',now())); v_end timestamptz:=coalesce(p_end,date_trunc('day',now())+interval '1 day'); v_sessions jsonb; v_ops jsonb; v_operators jsonb; v_branches jsonb; v_summary jsonb;
begin
 select * into v from private.resolve_temp_context(p_token); if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
 with sc as (
  select cs.id,cs.status,cs.opening_amount,cs.closing_amount,cs.opened_at,cs.closed_at,cs.staff_user_id,pr.name pos,pr.code pos_code,pr.branch_id,b.name branch,su.name operator,
   coalesce((select count(*) from sales s where s.cash_session_id=cs.id and s.status='completed'),0) sales_count,
   coalesce((select sum(s.total) from sales s where s.cash_session_id=cs.id and s.status='completed'),0) sales_total,
   coalesce((select sum(p.amount) from payments p join sales s on s.id=p.sale_id where s.cash_session_id=cs.id and s.status='completed' and p.status='paid' and p.method='cash'),0) cash_received,
   coalesce((select sum(amount) from cash_movements where cash_session_id=cs.id and movement_type='supply'),0) supply,
   coalesce((select sum(amount) from cash_movements where cash_session_id=cs.id and movement_type in ('withdrawal','sangria')),0) withdrawal,
   coalesce((select sum(amount) from cash_movements where cash_session_id=cs.id and movement_type='expense'),0) expense,
   coalesce((select sum(amount) from cash_movements where cash_session_id=cs.id and movement_type='refund'),0) refund
  from cash_sessions cs join pos_registers pr on pr.id=cs.pos_register_id join branches b on b.id=pr.branch_id left join staff_users su on su.id=cs.staff_user_id
  where cs.tenant_id=v.tenant_id and (p_branch is null or pr.branch_id=p_branch) and (p_operator is null or cs.staff_user_id=p_operator) and (p_cash_status is null or p_cash_status='' or cs.status=p_cash_status)
    and (cs.status='open' or (cs.opened_at<v_end and coalesce(cs.closed_at,v_end)>=v_start))
 ), e as (select sc.*,(opening_amount+cash_received+supply-withdrawal-expense-refund) expected_cash from sc)
 select coalesce(jsonb_agg(to_jsonb(e) order by opened_at desc),'[]'::jsonb) into v_sessions from e;
 with fs as (
  select cs.id,cs.staff_user_id,pr.branch_id,pr.name pos,b.name branch,su.name operator from cash_sessions cs join pos_registers pr on pr.id=cs.pos_register_id join branches b on b.id=pr.branch_id left join staff_users su on su.id=cs.staff_user_id
  where cs.tenant_id=v.tenant_id and (p_branch is null or pr.branch_id=p_branch) and (p_operator is null or cs.staff_user_id=p_operator)
 ), raw as (
  select cs.id::text||':open' op_key,cs.id cash_session_id,null::uuid sale_id,cs.opened_at occurred_at,'opening' op_type,'Abertura de caixa' description,cs.opening_amount amount,fs.pos,fs.branch,fs.operator,cs.staff_user_id operator_id,'realized' operation_state,null::uuid fiscal_document_id,null::text document_type,null::text fiscal_status,false fiscal_pending from cash_sessions cs join fs on fs.id=cs.id where cs.opened_at>=v_start and cs.opened_at<v_end
  union all
  select s.id::text,s.cash_session_id,s.id,coalesce(s.completed_at,s.created_at),'sale','Venda #'||s.number::text,s.total,fs.pos,fs.branch,coalesce(su.name,fs.operator),s.staff_user_id,case when s.status='cancelled' then 'cancelled' when fd.id is not null and fd.status not in ('authorized','cancelled') then 'fiscal_pending' else 'realized' end,fd.id,fd.document_type,fd.status,(fd.id is not null and fd.status not in ('authorized','cancelled')) from sales s join fs on fs.id=s.cash_session_id left join staff_users su on su.id=s.staff_user_id left join lateral (select f.id,f.document_type,f.status from fiscal_documents f where f.sale_id=s.id order by f.created_at desc limit 1) fd on true where coalesce(s.completed_at,s.created_at)>=v_start and coalesce(s.completed_at,s.created_at)<v_end and (p_operator is null or s.staff_user_id=p_operator or fs.staff_user_id=p_operator)
  union all
  select cm.id::text,cm.cash_session_id,null::uuid,cm.created_at,'cash_movement',case cm.movement_type when 'supply' then 'Suprimento' when 'withdrawal' then 'Sangria' when 'sangria' then 'Sangria' when 'expense' then 'Despesa' when 'refund' then 'Devolução em dinheiro' else 'Movimento: '||cm.movement_type end,cm.amount,fs.pos,fs.branch,fs.operator,fs.staff_user_id,'realized',null,null,null,false from cash_movements cm join fs on fs.id=cm.cash_session_id where cm.created_at>=v_start and cm.created_at<v_end
 ) select coalesce(jsonb_agg(to_jsonb(r) order by occurred_at desc),'[]'::jsonb) into v_ops from raw r where coalesce(nullif(p_operation_filter,''),'all')='all' or r.operation_state=p_operation_filter;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by name),'[]'::jsonb) into v_operators from staff_users where tenant_id=v.tenant_id and active=true;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by name),'[]'::jsonb) into v_branches from branches where tenant_id=v.tenant_id;
 select jsonb_build_object('open_cash',count(*) filter(where status='open'),'closed_cash',count(*) filter(where status='closed'),'sales_total',coalesce((select sum(s.total) from sales s where s.tenant_id=v.tenant_id and s.status='completed' and coalesce(s.completed_at,s.created_at)>=v_start and coalesce(s.completed_at,s.created_at)<v_end and (p_branch is null or s.branch_id=p_branch) and (p_operator is null or s.staff_user_id=p_operator)),0),'sessions',count(*)) into v_summary from cash_sessions cs join pos_registers pr on pr.id=cs.pos_register_id where cs.tenant_id=v.tenant_id and (p_branch is null or pr.branch_id=p_branch) and (p_operator is null or cs.staff_user_id=p_operator);
 return jsonb_build_object('ok',true,'sessions',v_sessions,'operations',v_ops,'operators',v_operators,'branches',v_branches,'summary',v_summary,'start',v_start,'end',v_end);
end $$;

create or replace function public.erp_sales_cash_sale_detail(p_token text,p_sale uuid)
returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $$
declare v record; s jsonb; its jsonb; pays jsonb; fd jsonb; aud jsonb;
begin
 select * into v from private.resolve_temp_context(p_token); if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
 select to_jsonb(x) into s from (select sa.*,b.name branch,pr.name pos,su.name operator,c.name customer from sales sa left join branches b on b.id=sa.branch_id left join cash_sessions cs on cs.id=sa.cash_session_id left join pos_registers pr on pr.id=cs.pos_register_id left join staff_users su on su.id=sa.staff_user_id left join customers c on c.id=sa.customer_id where sa.id=p_sale and sa.tenant_id=v.tenant_id) x; if s is null then return jsonb_build_object('ok',false,'error','sale_not_found'); end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at),'[]'::jsonb) into its from (select si.* from sale_items si where si.sale_id=p_sale) x;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at),'[]'::jsonb) into pays from (select p.* from payments p where p.sale_id=p_sale) x;
 select to_jsonb(x) into fd from (select f.*,case when f.authorization_at is not null then f.authorization_at+interval '30 minutes' end cancel_deadline,(f.status='authorized' and f.authorization_at is not null and now()<=f.authorization_at+interval '30 minutes') can_cancel_window,(f.status='authorized' and (nullif(f.xml_path,'') is not null or coalesce(f.response_payload->>'authorized_xml',f.response_payload->>'xml','')<>'')) xml_available from fiscal_documents f where f.sale_id=p_sale order by f.created_at desc limit 1) x;
 select coalesce(jsonb_agg(to_jsonb(a) order by a.created_at desc),'[]'::jsonb) into aud from sales_management_audit a where a.sale_id=p_sale;
 return jsonb_build_object('ok',true,'sale',s,'items',its,'payments',pays,'fiscal',fd,'audit',aud,'document_kind',case when fd is null then 'pre_sale' else coalesce(fd->>'document_type','pre_sale') end,'fiscal_cancellation_transport_ready',false);
end $$;

create or replace function public.erp_sales_cash_cancel_sale(p_token text,p_sale uuid,p_reason text)
returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $$
declare v record; sa sales%rowtype; si record; po record; oi record; v_email text; v_warning text:=null;
begin
 select * into v from private.resolve_temp_context(p_token); if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if; if length(trim(coalesce(p_reason,'')))<3 then return jsonb_build_object('ok',false,'error','cancellation_reason_required'); end if;
 select * into sa from sales where id=p_sale and tenant_id=v.tenant_id for update; if sa.id is null then return jsonb_build_object('ok',false,'error','sale_not_found'); end if; if sa.status='cancelled' then return jsonb_build_object('ok',true,'idempotent',true); end if; if exists(select 1 from fiscal_documents where sale_id=p_sale and status='authorized') then return jsonb_build_object('ok',false,'error','authorized_nfce_requires_fiscal_cancellation'); end if; select email into v_email from private.temp_users where id=v.user_id;
 for si in select x.*,coalesce(x.fiscal_snapshot->>'production_mode','stock') production_mode from sale_items x where x.sale_id=p_sale loop if si.product_id is not null and si.production_mode<>'on_demand' then insert into stock_movements(tenant_id,branch_id,product_id,movement_type,quantity,reference_type,reference_id,notes,actor_type,actor_id) values(sa.tenant_id,sa.branch_id,si.product_id,'sale_cancel',abs(si.quantity),'sale_cancel',sa.id,'Estorno por cancelamento no Gestão','temp_user',v.user_id); insert into inventory_balances(tenant_id,branch_id,product_id,quantity,reserved_quantity,updated_at) values(sa.tenant_id,sa.branch_id,si.product_id,abs(si.quantity),0,now()) on conflict(tenant_id,branch_id,product_id) do update set quantity=inventory_balances.quantity+excluded.quantity,updated_at=now(); end if; end loop;
 for po in select * from production_orders where sale_id=p_sale and order_type='on_demand' and status in ('planned','queued') for update loop for oi in select * from production_order_items where production_order_id=po.id and deduct_stock=true and consumed_quantity>0 loop insert into stock_movements(tenant_id,branch_id,product_id,movement_type,quantity,reference_type,reference_id,notes,actor_type,actor_id) values(sa.tenant_id,sa.branch_id,oi.component_product_id,'production_cancel_return',abs(oi.consumed_quantity),'production_order',po.id,'Retorno de insumo por cancelamento antes do preparo','temp_user',v.user_id); insert into inventory_balances(tenant_id,branch_id,product_id,quantity,reserved_quantity,updated_at) values(sa.tenant_id,sa.branch_id,oi.component_product_id,abs(oi.consumed_quantity),0,now()) on conflict(tenant_id,branch_id,product_id) do update set quantity=inventory_balances.quantity+excluded.quantity,updated_at=now(); end loop; update production_orders set status='canceled',canceled_at=now(),updated_at=now(),notes=concat_ws(E'\n',notes,'Cancelada junto com a venda pelo Gestão: '||trim(p_reason)) where id=po.id; end loop;
 if exists(select 1 from production_orders where sale_id=p_sale and order_type='on_demand' and status in ('in_progress','ready','delivered','completed')) then v_warning:='production_already_started_components_not_returned'; end if;
 update fiscal_documents set status='cancelled',cancellation_at=now(),updated_at=now(),response_payload=response_payload||jsonb_build_object('cancelled_before_authorization',true,'management_reason',trim(p_reason)) where sale_id=p_sale and status in ('draft','processing','rejected');
 update sales set status='cancelled',cancelled_at=now(),notes=concat_ws(E'\n',notes,'Cancelada pelo Gestão: '||trim(p_reason)) where id=p_sale; update financial_entries set status='cancelled',updated_at=now(),metadata=metadata||jsonb_build_object('cancelled_by','gestao','reason',trim(p_reason)) where sale_id=p_sale; update payments set status='cancelled',metadata=metadata||jsonb_build_object('cancelled_by','gestao','provider_reversal_required',method not in ('cash','store_credit')) where sale_id=p_sale and status in ('paid','authorized');
 insert into sales_management_audit(tenant_id,sale_id,action,reason,previous_status,new_status,actor_user_id,actor_email,metadata) values(v.tenant_id,p_sale,'management_cancel',trim(p_reason),sa.status,'cancelled',v.user_id,v_email,jsonb_build_object('warning',v_warning)); return jsonb_build_object('ok',true,'sale_id',p_sale,'warning',v_warning,'payment_warning','non_cash_payments_may_require_provider_reversal');
end $$;

create or replace function public.erp_sales_cash_cancel_nfce(p_token text,p_sale uuid,p_reason text)
returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $$
declare v record; f fiscal_documents%rowtype; begin select * into v from private.resolve_temp_context(p_token); if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if; if length(trim(coalesce(p_reason,'')))<15 then return jsonb_build_object('ok',false,'error','nfce_cancellation_reason_too_short'); end if; select * into f from fiscal_documents where sale_id=p_sale and tenant_id=v.tenant_id and document_type='nfce' order by created_at desc limit 1; if f.id is null then return jsonb_build_object('ok',false,'error','nfce_not_found'); end if; if f.status<>'authorized' then return jsonb_build_object('ok',false,'error','nfce_not_authorized'); end if; if f.authorization_at is null or now()>f.authorization_at+interval '30 minutes' then return jsonb_build_object('ok',false,'error','nfce_cancellation_window_expired','deadline',f.authorization_at+interval '30 minutes'); end if; return jsonb_build_object('ok',false,'error','fiscal_cancellation_transport_not_configured','deadline',f.authorization_at+interval '30 minutes','provider',f.provider,'message','Janela fiscal válida, mas o evento de cancelamento ainda depende da integração homologada com o provedor/SEFAZ.'); end $$;

create or replace function public.erp_sales_cash_fiscal_xml(p_token text,p_document uuid)
returns jsonb language plpgsql security definer set search_path='public','private','extensions' as $$
declare v record; f fiscal_documents%rowtype; x text; begin select * into v from private.resolve_temp_context(p_token); if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if; select * into f from fiscal_documents where id=p_document and tenant_id=v.tenant_id; if f.id is null then return jsonb_build_object('ok',false,'error','document_not_found'); end if; if f.status<>'authorized' then return jsonb_build_object('ok',false,'error','document_not_authorized'); end if; x:=coalesce(f.response_payload->>'authorized_xml',f.response_payload->>'xml'); if nullif(x,'') is null and nullif(f.xml_path,'') is null then return jsonb_build_object('ok',false,'error','xml_not_available'); end if; return jsonb_build_object('ok',true,'xml',x,'xml_path',f.xml_path,'filename','NFCe-'||coalesce(f.number,f.id::text)||'.xml'); end $$;