create or replace function public.erp_fiscal_settings_get(p_token text)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;s public.fiscal_settings%rowtype;c private.fiscal_certificates%rowtype;cs private.fiscal_csc_credentials%rowtype;d public.fiscal_danfe_settings%rowtype;co public.companies%rowtype;br public.branches%rowtype;bs public.branch_settings%rowtype;v_series jsonb;v_pos jsonb;v_cfops jsonb;v_ready jsonb;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;perform private.ensure_fiscal_defaults(v.tenant_id,v.company_id,v.branch_id);select * into s from public.fiscal_settings where tenant_id=v.tenant_id;select * into c from private.fiscal_certificates where tenant_id=v.tenant_id and company_id=v.company_id;select * into cs from private.fiscal_csc_credentials where tenant_id=v.tenant_id and branch_id=v.branch_id;select * into d from public.fiscal_danfe_settings where tenant_id=v.tenant_id and branch_id=v.branch_id;select * into co from public.companies where id=v.company_id and tenant_id=v.tenant_id;select * into br from public.branches where id=v.branch_id and tenant_id=v.tenant_id;select * into bs from public.branch_settings where branch_id=v.branch_id and tenant_id=v.tenant_id;v_ready:=private.fiscal_readiness_v076(v.tenant_id,v.company_id,v.branch_id);
 select coalesce(jsonb_agg(to_jsonb(x) order by x.document_type,x.series),'[]'::jsonb) into v_series from(select fs.id,fs.document_type,fs.series::text series,fs.label,fs.last_number,(fs.last_number+1) next_number,fs.is_default,fs.active,fs.branch_id,b.name branch,exists(select 1 from public.fiscal_pos_series fps where fps.fiscal_series_id=fs.id and fps.in_use) in_use_by_cash from public.fiscal_series fs join public.branches b on b.id=fs.branch_id where fs.tenant_id=v.tenant_id and fs.branch_id=v.branch_id)x;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.name),'[]'::jsonb) into v_pos from(select p.id,p.name,p.code,p.active,p.branch_id,b.name branch,m.id mapping_id,m.cash_number,m.in_use,m.fiscal_series_id,ser.series::text fiscal_series,ser.label fiscal_series_label from public.pos_registers p join public.branches b on b.id=p.branch_id left join lateral(select fps.* from public.fiscal_pos_series fps where fps.tenant_id=v.tenant_id and fps.pos_register_id=p.id and fps.in_use order by fps.updated_at desc limit 1)m on true left join public.fiscal_series ser on ser.id=m.fiscal_series_id where p.tenant_id=v.tenant_id and p.branch_id=v.branch_id)x;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.code),'[]'::jsonb) into v_cfops from(select id,code,name,active,case when left(code,1) in('1','2','3') then 'entry' else 'exit' end direction from public.fiscal_cfops where tenant_id=v.tenant_id)x;
 return jsonb_build_object('ok',true,'settings',jsonb_build_object('provider','svrs_direct','transport','SVRS direta','environment',coalesce(s.environment,'homologation'),'nfe_series',coalesce((select fs.series::text from public.fiscal_series fs where fs.tenant_id=v.tenant_id and fs.branch_id=v.branch_id and fs.document_type='nfe' and fs.active and fs.is_default limit 1),coalesce(s.nfe_series,'1')),'nfce_series',coalesce((select fs.series::text from public.fiscal_series fs where fs.tenant_id=v.tenant_id and fs.branch_id=v.branch_id and fs.document_type='nfce' and fs.active and fs.is_default limit 1),coalesce(s.nfce_series,'1')),'csc_id',coalesce(cs.csc_id,s.csc_id),'csc_token_configured',cs.csc_token_cipher is not null,'branch_id',v.branch_id,'company_id',v.company_id,'issuer',jsonb_build_object('cnpj',coalesce(nullif(br.cnpj,''),co.cnpj),'state_registration',coalesce(nullif(bs.state_registration,''),co.state_registration),'tax_regime',coalesce(nullif(bs.crt,''),co.tax_regime),'street',br.street,'number',br.number,'complement',br.complement,'district',br.district,'city',br.city,'state',br.state,'postal_code',br.postal_code,'ibge_city_code',br.ibge_city_code),'fiscal_readiness',v_ready,'series',v_series,'pos_registers',v_pos,'cfops',v_cfops,'danfe',jsonb_build_object('unit_decimal_places',coalesce(d.unit_decimal_places,2),'product_name_lines',coalesce(d.product_name_lines,2),'item_order',coalesce(d.item_order,'launch'),'product_name_format',coalesce(d.product_name_format,'{nome}'),'active',coalesce(d.active,true)),'configured',c.company_id is not null,'certificate',case when c.company_id is null then null else jsonb_build_object('filename',c.filename,'subject_cn',c.subject_cn,'subject_cnpj',c.subject_cnpj,'serial_number',c.serial_number,'valid_from',c.valid_from,'valid_to',c.valid_to,'fingerprint_sha256',c.fingerprint_sha256,'file_sha256',c.file_sha256,'uploaded_at',c.uploaded_at,'expired',(c.valid_to is not null and c.valid_to<now())) end));
end $$;
