alter table private.platform_pricing
  add column if not exists included_branches integer not null default 1,
  add column if not exists extra_branch_price numeric(12,2) not null default 0;

alter table public.tenant_licenses
  add column if not exists branch_limit integer not null default 1,
  add column if not exists extra_branch_price numeric(12,2) not null default 0;

update public.tenant_licenses l
set branch_limit = greatest(1, coalesce((select count(*)::int from public.branches b where b.tenant_id=l.tenant_id),1)),
    modules = coalesce(l.modules,'{}'::jsonb) || jsonb_build_object('branches',coalesce((select count(*) from public.branches b where b.tenant_id=l.tenant_id),0)>1)
where true;

create or replace function private.enforce_branch_license_limit()
returns trigger language plpgsql security definer set search_path=public,private as $$
declare v_limit int;v_count int;v_enabled boolean;v_active boolean;
begin
 if coalesce(new.is_headquarters,false) then return new;end if;
 select l.branch_limit,coalesce((l.modules->>'branches')::boolean,false),l.status in ('trial','active') and (l.expires_at is null or l.expires_at>now()) into v_limit,v_enabled,v_active from public.tenant_licenses l where l.tenant_id=new.tenant_id;
 if not coalesce(v_active,false) then raise exception 'branch_license_inactive';end if;
 if not coalesce(v_enabled,false) then raise exception 'branch_module_not_licensed';end if;
 select count(*) into v_count from public.branches where tenant_id=new.tenant_id;
 if v_count>=coalesce(v_limit,1) then raise exception 'branch_license_limit_reached: limit %',coalesce(v_limit,1);end if;
 return new;
end $$;

drop trigger if exists trg_enforce_branch_license_limit on public.branches;
create trigger trg_enforce_branch_license_limit before insert on public.branches for each row execute function private.enforce_branch_license_limit();

create or replace function public.erp_branch_save(p_token text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;l public.tenant_licenses%rowtype;v_id uuid;v_count int;v_company uuid;v_existing public.branches%rowtype;v_cnpj text;v_state text;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;
 select * into l from public.tenant_licenses where tenant_id=v.tenant_id;if l.tenant_id is null then return jsonb_build_object('ok',false,'error','license_not_found');end if;
 v_id:=nullif(p_payload->>'id','')::uuid;v_cnpj:=regexp_replace(coalesce(p_payload->>'cnpj',''),'\D','','g');v_state:=upper(trim(coalesce(p_payload->>'state','')));
 if v_id is null then
  if not coalesce((l.modules->>'branches')::boolean,false) then return jsonb_build_object('ok',false,'error','branch_module_not_licensed');end if;
  select count(*) into v_count from public.branches where tenant_id=v.tenant_id;
  if v_count>=greatest(coalesce(l.branch_limit,1),1) then return jsonb_build_object('ok',false,'error','branch_license_limit_reached','branch_limit',l.branch_limit,'branches_count',v_count);end if;
  if trim(coalesce(p_payload->>'name',''))='' then return jsonb_build_object('ok',false,'error','branch_name_required');end if;
  if v_cnpj<>'' and length(v_cnpj)<>14 then return jsonb_build_object('ok',false,'error','invalid_cnpj');end if;
  if v_state<>'' and v_state!~'^[A-Z]{2}$' then return jsonb_build_object('ok',false,'error','invalid_state');end if;
  if v_cnpj<>'' and exists(select 1 from public.branches b where b.tenant_id=v.tenant_id and regexp_replace(coalesce(b.cnpj,''),'\D','','g')=v_cnpj) then return jsonb_build_object('ok',false,'error','branch_cnpj_already_registered');end if;
  v_company:=coalesce(nullif(p_payload->>'company_id','')::uuid,v.company_id);if not exists(select 1 from public.companies c where c.id=v_company and c.tenant_id=v.tenant_id) then return jsonb_build_object('ok',false,'error','company_not_found');end if;
  insert into public.branches(tenant_id,company_id,name,cnpj,is_headquarters,street,number,complement,district,city,state,postal_code,ibge_city_code)
  values(v.tenant_id,v_company,trim(p_payload->>'name'),nullif(v_cnpj,''),false,nullif(trim(coalesce(p_payload->>'street','')),''),nullif(trim(coalesce(p_payload->>'number','')),''),nullif(trim(coalesce(p_payload->>'complement','')),''),nullif(trim(coalesce(p_payload->>'district','')),''),nullif(trim(coalesce(p_payload->>'city','')),''),nullif(v_state,'')::char(2),nullif(regexp_replace(coalesce(p_payload->>'postal_code',''),'\D','','g'),''),nullif(trim(coalesce(p_payload->>'ibge_city_code','')),'')) returning id into v_id;
  insert into public.branch_settings(branch_id,tenant_id,email,phone,state_registration,municipal_registration,crt,contact,responsible,updated_at)
  values(v_id,v.tenant_id,nullif(trim(coalesce(p_payload->>'email','')),''),nullif(trim(coalesce(p_payload->>'phone','')),''),nullif(trim(coalesce(p_payload->>'state_registration','')),''),nullif(trim(coalesce(p_payload->>'municipal_registration','')),''),nullif(trim(coalesce(p_payload->>'crt','')),''),nullif(trim(coalesce(p_payload->>'contact','')),''),nullif(trim(coalesce(p_payload->>'responsible','')),''),now()) on conflict(branch_id) do nothing;
 else
  select * into v_existing from public.branches where id=v_id and tenant_id=v.tenant_id;if v_existing.id is null then return jsonb_build_object('ok',false,'error','branch_not_found');end if;if v_existing.is_headquarters then return jsonb_build_object('ok',false,'error','headquarters_managed_in_matrix');end if;
  if v_cnpj<>'' and length(v_cnpj)<>14 then return jsonb_build_object('ok',false,'error','invalid_cnpj');end if;if v_state<>'' and v_state!~'^[A-Z]{2}$' then return jsonb_build_object('ok',false,'error','invalid_state');end if;
  if v_cnpj<>'' and exists(select 1 from public.branches b where b.tenant_id=v.tenant_id and b.id<>v_id and regexp_replace(coalesce(b.cnpj,''),'\D','','g')=v_cnpj) then return jsonb_build_object('ok',false,'error','branch_cnpj_already_registered');end if;
  update public.branches set name=coalesce(nullif(trim(p_payload->>'name'),''),name),cnpj=case when p_payload?'cnpj' then nullif(v_cnpj,'') else cnpj end,street=case when p_payload?'street' then nullif(trim(p_payload->>'street'),'') else street end,number=case when p_payload?'number' then nullif(trim(p_payload->>'number'),'') else number end,complement=case when p_payload?'complement' then nullif(trim(p_payload->>'complement'),'') else complement end,district=case when p_payload?'district' then nullif(trim(p_payload->>'district'),'') else district end,city=case when p_payload?'city' then nullif(trim(p_payload->>'city'),'') else city end,state=case when p_payload?'state' then nullif(v_state,'')::char(2) else state end,postal_code=case when p_payload?'postal_code' then nullif(regexp_replace(coalesce(p_payload->>'postal_code',''),'\D','','g'),'') else postal_code end,ibge_city_code=case when p_payload?'ibge_city_code' then nullif(trim(p_payload->>'ibge_city_code'),'') else ibge_city_code end,updated_at=now() where id=v_id;
 end if;
 select count(*) into v_count from public.branches where tenant_id=v.tenant_id;return jsonb_build_object('ok',true,'id',v_id,'branches_count',v_count,'branch_limit',l.branch_limit,'remaining',greatest(l.branch_limit-v_count,0));
end $$;
grant execute on function public.erp_branch_save(text,jsonb) to anon,authenticated,service_role;

create or replace function public.erp_license_get(p_token text)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v record;l public.tenant_licenses%rowtype;v_branches int;
begin
 select * into v from private.resolve_temp_context(p_token);if v.user_id is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;select * into l from public.tenant_licenses where tenant_id=v.tenant_id;if l.tenant_id is null then return jsonb_build_object('ok',false,'error','license_not_found');end if;select count(*) into v_branches from public.branches where tenant_id=v.tenant_id;
 return jsonb_build_object('ok',true,'tenant_id',v.tenant_id,'status',l.status,'plan_name',l.plan_name,'modules',l.modules,'management_user_limit',l.management_user_limit,'pdv_terminal_limit',l.pdv_terminal_limit,'branch_limit',l.branch_limit,'branches_count',v_branches,'branch_remaining',greatest(l.branch_limit-v_branches,0),'monthly_amount',l.monthly_amount,'expires_at',l.expires_at);
end $$;

create or replace function public.platform_pricing_save(p_token text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare a uuid;r private.platform_pricing%rowtype;
begin
 a:=private.resolve_platform_admin(p_token);if a is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;
 update private.platform_pricing set base_erp_price=greatest(coalesce(nullif(p_payload->>'base_erp_price','')::numeric,base_erp_price),0),included_management_users=greatest(coalesce(nullif(p_payload->>'included_management_users','')::int,included_management_users),0),extra_management_user_price=greatest(coalesce(nullif(p_payload->>'extra_management_user_price','')::numeric,extra_management_user_price),0),included_pdv_terminals=greatest(coalesce(nullif(p_payload->>'included_pdv_terminals','')::int,included_pdv_terminals),0),extra_pdv_terminal_price=greatest(coalesce(nullif(p_payload->>'extra_pdv_terminal_price','')::numeric,extra_pdv_terminal_price),0),included_branches=greatest(coalesce(nullif(p_payload->>'included_branches','')::int,included_branches),1),extra_branch_price=greatest(coalesce(nullif(p_payload->>'extra_branch_price','')::numeric,extra_branch_price),0),updated_at=now() where id=1 returning * into r;return jsonb_build_object('ok',true,'pricing',to_jsonb(r));
end $$;

create or replace function public.platform_license_update(p_token text,p_tenant uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare a uuid;oldrow public.tenant_licenses%rowtype;newrow public.tenant_licenses%rowtype;pr private.platform_pricing%rowtype;v_users int;v_pdvs int;v_branches int;v_current_branches int;v_monthly numeric;v_modules jsonb;
begin
 a:=private.resolve_platform_admin(p_token);if a is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;select * into oldrow from public.tenant_licenses where tenant_id=p_tenant for update;if oldrow.tenant_id is null then return jsonb_build_object('ok',false,'error','license_not_found');end if;select * into pr from private.platform_pricing where id=1;v_modules:=coalesce(p_payload->'modules',oldrow.modules);v_users:=greatest(coalesce(nullif(p_payload->>'management_user_limit','')::int,oldrow.management_user_limit),0);v_pdvs:=greatest(coalesce(nullif(p_payload->>'pdv_terminal_limit','')::int,oldrow.pdv_terminal_limit),0);v_branches:=greatest(coalesce(nullif(p_payload->>'branch_limit','')::int,oldrow.branch_limit),1);if not coalesce((v_modules->>'branches')::boolean,false) then v_branches:=1;end if;select count(*) into v_current_branches from public.branches where tenant_id=p_tenant;if v_branches<v_current_branches then return jsonb_build_object('ok',false,'error','branch_limit_below_current_usage','branches_count',v_current_branches,'requested_limit',v_branches);end if;
 v_monthly:=coalesce(nullif(p_payload->>'monthly_amount','')::numeric,pr.base_erp_price+greatest(v_users-pr.included_management_users,0)*pr.extra_management_user_price+greatest(v_pdvs-pr.included_pdv_terminals,0)*pr.extra_pdv_terminal_price+greatest(v_branches-pr.included_branches,0)*pr.extra_branch_price);
 update public.tenant_licenses set status=coalesce(nullif(p_payload->>'status',''),status),plan_name=coalesce(nullif(p_payload->>'plan_name',''),plan_name),modules=v_modules,management_user_limit=v_users,pdv_terminal_limit=v_pdvs,branch_limit=v_branches,base_monthly_amount=pr.base_erp_price,extra_management_user_price=pr.extra_management_user_price,extra_pdv_terminal_price=pr.extra_pdv_terminal_price,extra_branch_price=pr.extra_branch_price,monthly_amount=greatest(v_monthly,0),expires_at=case when p_payload?'expires_at' then nullif(p_payload->>'expires_at','')::timestamptz else expires_at end,notes=case when p_payload?'notes' then nullif(p_payload->>'notes','') else notes end,updated_at=now() where tenant_id=p_tenant returning * into newrow;
 insert into public.license_audit(tenant_id,action,before_data,after_data,actor_admin_id) values(p_tenant,'license_updated',to_jsonb(oldrow),to_jsonb(newrow),a);return jsonb_build_object('ok',true,'license',to_jsonb(newrow));
end $$;

create or replace function public.platform_customer_create(p_token text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare a uuid;v_tenant uuid;v_company uuid;v_branch uuid;v_user uuid;v_temp_password text;v_email_hash text;pr private.platform_pricing%rowtype;v_modules jsonb;v_users int;v_pdvs int;v_branches int;v_monthly numeric;v_legal text;v_trade text;v_cnpj text;v_admin_email text;v_license_status text;v_crt text;v_cep text;v_uf text;
begin
 a:=private.resolve_platform_admin(p_token);if a is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;v_legal:=trim(coalesce(p_payload->>'legal_name',''));v_trade:=trim(coalesce(p_payload->>'trade_name',''));v_cnpj:=regexp_replace(coalesce(p_payload->>'cnpj',''),'\D','','g');v_admin_email:=lower(trim(coalesce(p_payload->>'admin_email','')));v_license_status:=coalesce(nullif(p_payload->>'license_status',''),'trial');v_crt:=trim(coalesce(p_payload->>'tax_regime',''));v_cep:=regexp_replace(coalesce(p_payload->>'postal_code',''),'\D','','g');v_uf:=upper(trim(coalesce(p_payload->>'state','')));
 if v_legal='' then return jsonb_build_object('ok',false,'error','legal_name_required');end if;if length(v_cnpj)<>14 then return jsonb_build_object('ok',false,'error','invalid_cnpj');end if;if v_admin_email='' or position('@' in v_admin_email)=0 then return jsonb_build_object('ok',false,'error','admin_email_required');end if;if v_license_status not in ('trial','active') then return jsonb_build_object('ok',false,'error','invalid_initial_license_status');end if;if v_crt<>'' and v_crt not in ('1','2','3','4') then return jsonb_build_object('ok',false,'error','invalid_tax_regime');end if;if v_cep<>'' and length(v_cep)<>8 then return jsonb_build_object('ok',false,'error','invalid_postal_code');end if;if v_uf<>'' and v_uf!~'^[A-Z]{2}$' then return jsonb_build_object('ok',false,'error','invalid_state');end if;if exists(select 1 from public.tenants where document=v_cnpj) or exists(select 1 from public.companies where cnpj=v_cnpj) then return jsonb_build_object('ok',false,'error','cnpj_already_registered');end if;v_email_hash:=encode(extensions.digest(v_admin_email,'sha256'),'hex');if exists(select 1 from private.temp_users where email_hash=v_email_hash and active=true) then return jsonb_build_object('ok',false,'error','admin_email_already_in_use');end if;
 select * into pr from private.platform_pricing where id=1;v_modules:=coalesce(p_payload->'modules',private.default_license_modules());v_users:=greatest(coalesce(nullif(p_payload->>'management_user_limit','')::int,pr.included_management_users),0);v_pdvs:=greatest(coalesce(nullif(p_payload->>'pdv_terminal_limit','')::int,pr.included_pdv_terminals),0);v_branches:=greatest(coalesce(nullif(p_payload->>'branch_limit','')::int,pr.included_branches),1);if not coalesce((v_modules->>'branches')::boolean,false) then v_branches:=1;end if;v_monthly:=pr.base_erp_price+greatest(v_users-pr.included_management_users,0)*pr.extra_management_user_price+greatest(v_pdvs-pr.included_pdv_terminals,0)*pr.extra_pdv_terminal_price+greatest(v_branches-pr.included_branches,0)*pr.extra_branch_price;
 insert into public.tenants(name,document,status) values(coalesce(nullif(v_trade,''),v_legal),v_cnpj,'active') returning id into v_tenant;insert into public.companies(tenant_id,legal_name,trade_name,cnpj,state_registration,municipal_registration,tax_regime,email,phone,status) values(v_tenant,v_legal,coalesce(nullif(v_trade,''),v_legal),v_cnpj,nullif(trim(coalesce(p_payload->>'state_registration','')),''),nullif(trim(coalesce(p_payload->>'municipal_registration','')),''),nullif(v_crt,''),nullif(trim(coalesce(p_payload->>'company_email','')),''),nullif(trim(coalesce(p_payload->>'phone','')),''),'active') returning id into v_company;
 insert into public.branches(tenant_id,company_id,name,cnpj,is_headquarters,street,number,complement,district,city,state,postal_code,ibge_city_code) values(v_tenant,v_company,coalesce(nullif(trim(p_payload->>'branch_name'),''),coalesce(nullif(v_trade,''),'Matriz')),v_cnpj,true,nullif(trim(coalesce(p_payload->>'street','')),''),nullif(trim(coalesce(p_payload->>'number','')),''),nullif(trim(coalesce(p_payload->>'complement','')),''),nullif(trim(coalesce(p_payload->>'district','')),''),nullif(trim(coalesce(p_payload->>'city','')),''),nullif(v_uf,'')::char(2),nullif(v_cep,''),nullif(trim(coalesce(p_payload->>'ibge_city_code','')),'')) returning id into v_branch;
 insert into public.branch_settings(branch_id,tenant_id,email,phone,state_registration,municipal_registration,crt,contact,responsible,updated_at) values(v_branch,v_tenant,nullif(trim(coalesce(p_payload->>'company_email','')),''),nullif(trim(coalesce(p_payload->>'phone','')),''),nullif(trim(coalesce(p_payload->>'state_registration','')),''),nullif(trim(coalesce(p_payload->>'municipal_registration','')),''),nullif(v_crt,''),nullif(trim(coalesce(p_payload->>'contact','')),''),nullif(trim(coalesce(p_payload->>'responsible','')),''),now()) on conflict(branch_id) do update set email=excluded.email,phone=excluded.phone,state_registration=excluded.state_registration,municipal_registration=excluded.municipal_registration,crt=excluded.crt,contact=excluded.contact,responsible=excluded.responsible,updated_at=now();
 insert into public.tenant_licenses(tenant_id,status,plan_name,modules,management_user_limit,pdv_terminal_limit,branch_limit,base_monthly_amount,extra_management_user_price,extra_pdv_terminal_price,extra_branch_price,monthly_amount,starts_at,expires_at,notes) values(v_tenant,v_license_status,coalesce(nullif(p_payload->>'plan_name',''),'ThorERP Personalizado'),v_modules,v_users,v_pdvs,v_branches,pr.base_erp_price,pr.extra_management_user_price,pr.extra_pdv_terminal_price,pr.extra_branch_price,v_monthly,now(),nullif(p_payload->>'expires_at','')::timestamptz,nullif(p_payload->>'notes',''));
 v_temp_password:='Thor#'||upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,12));insert into private.temp_users(email,email_hash,password_hash,must_change_password,active) values(v_admin_email,v_email_hash,extensions.crypt(v_temp_password,extensions.gen_salt('bf',12)),true,true) returning id into v_user;insert into private.temp_user_context(user_id,tenant_id,company_id,branch_id) values(v_user,v_tenant,v_company,v_branch);insert into public.license_audit(tenant_id,action,after_data,actor_admin_id) values(v_tenant,'customer_created',jsonb_build_object('cnpj',v_cnpj,'admin_email',v_admin_email,'modules',v_modules,'management_user_limit',v_users,'pdv_terminal_limit',v_pdvs,'branch_limit',v_branches,'monthly_amount',v_monthly),a);return jsonb_build_object('ok',true,'tenant_id',v_tenant,'company_id',v_company,'branch_id',v_branch,'admin_email',v_admin_email,'temporary_password',v_temp_password,'monthly_amount',v_monthly,'branch_limit',v_branches);
end $$;

create or replace function public.platform_dashboard(p_token text)
returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare a uuid;v_clients jsonb;v_pricing jsonb;v_summary jsonb;v_fiscal jsonb;
begin
 a:=private.resolve_platform_admin(p_token);if a is null then return jsonb_build_object('ok',false,'error','invalid_session');end if;select to_jsonb(p) into v_pricing from private.platform_pricing p where id=1;
 select coalesce(jsonb_agg(x order by x->>'name'),'[]'::jsonb) into v_clients from (select jsonb_build_object('tenant_id',t.id,'name',t.name,'document',t.document,'tenant_status',t.status,'company_id',c.id,'legal_name',c.legal_name,'trade_name',c.trade_name,'cnpj',c.cnpj,'state_registration',c.state_registration,'municipal_registration',c.municipal_registration,'tax_regime',c.tax_regime,'company_email',c.email,'phone',c.phone,'branch_id',b.id,'branch_name',b.name,'street',b.street,'number',b.number,'complement',b.complement,'district',b.district,'city',b.city,'state',b.state,'postal_code',b.postal_code,'ibge_city_code',b.ibge_city_code,'admin_email',(select u.email from private.temp_user_context uc join private.temp_users u on u.id=uc.user_id where uc.tenant_id=t.id order by uc.created_at limit 1),'license_status',l.status,'plan_name',l.plan_name,'modules',l.modules,'management_user_limit',l.management_user_limit,'pdv_terminal_limit',l.pdv_terminal_limit,'branch_limit',l.branch_limit,'branch_count',(select count(*) from public.branches bx where bx.tenant_id=t.id),'branch_remaining',greatest(l.branch_limit-(select count(*) from public.branches bx where bx.tenant_id=t.id),0),'monthly_amount',l.monthly_amount,'starts_at',l.starts_at,'expires_at',l.expires_at,'license_notes',l.notes,'blocked_at',l.blocked_at,'blocked_reason',l.blocked_reason,'status_before_block',l.status_before_block,'pdv_devices',(select count(*) from public.pdv_devices d where d.tenant_id=t.id and d.status<>'blocked'),'fiscal_documents',(select count(*) from public.fiscal_documents fd where fd.tenant_id=t.id)) x from public.tenants t left join lateral(select * from public.companies cx where cx.tenant_id=t.id order by cx.created_at limit 1)c on true left join lateral(select * from public.branches bx where bx.tenant_id=t.id order by bx.is_headquarters desc,bx.created_at limit 1)b on true left join public.tenant_licenses l on l.tenant_id=t.id)q;
 select jsonb_build_object('clients',(select count(*) from public.tenants),'active_licenses',(select count(*) from public.tenant_licenses where status in ('trial','active') and (expires_at is null or expires_at>now())),'blocked_licenses',(select count(*) from public.tenant_licenses where status='suspended'),'monthly_recurring',coalesce((select sum(monthly_amount) from public.tenant_licenses where status='active'),0),'pdv_devices',(select count(*) from public.pdv_devices where status<>'blocked'),'branches',(select count(*) from public.branches),'fiscal_today',(select count(*) from public.fiscal_documents where created_at>=date_trunc('day',now()))) into v_summary;
 select coalesce(jsonb_agg(to_jsonb(f) order by f.created_at desc),'[]'::jsonb) into v_fiscal from(select fd.id,fd.tenant_id,t.name tenant_name,fd.company_id,coalesce(c.trade_name,c.legal_name) company,fd.branch_id,b.name branch,fd.sale_id,s.number sale_number,fd.document_type,fd.environment,fd.status,fd.series,fd.number,fd.access_key,fd.protocol,fd.authorization_at,fd.cancellation_protocol,fd.cancellation_at,fd.rejection_code,fd.rejection_message,fd.xml_path,fd.pdf_path,fd.created_at,fd.updated_at,fd.response_payload from public.fiscal_documents fd join public.tenants t on t.id=fd.tenant_id join public.companies c on c.id=fd.company_id join public.branches b on b.id=fd.branch_id left join public.sales s on s.id=fd.sale_id order by fd.created_at desc limit 200)f;
 return jsonb_build_object('ok',true,'clients',v_clients,'pricing',v_pricing,'summary',v_summary,'fiscal',v_fiscal);
end $$;
